<?php
// foreach ($notams as $notam) {
//   print_r(strpos ( $notam['raw'] , 'LF'));
// }
?>


<tr>
    <td><?=$afis->getName()?></td>
    <td>
        <div class="togglebutton">
        <label>
            <input 
                   data-id="<?=$afis->getId()?>"
                   class="btn-switch-af" type="checkbox" <?=($afis->getState() ? 'checked="checked"' : '')?>
                   
                   <?php
                        ($this->isGranted('afis.write')) ? '' : 'disabled="disabled"';
                   ?>
            />
        </label>
        </div>
    </td>
    <td>
        <?php $openedHours = $afis->getOpenedhours(); 
        if ($openedHours) { ?>
            <span class="glyphicon glyphicon-time" title="<?php echo $openedHours; ?>"></span>
        <?php } ?>
    </td>

    <td>
        <?php $contacts = $afis->getContacts();
        if ($contacts) { ?>
            <span class="glyphicon glyphicon-phone" title="<?php echo $contacts; ?>"></span>
        <?php } ?>
    </td>
</tr>
