
<tr>
    <td><?=$afis->getName()?></td>
    <td>
        <div class="togglebutton">
        <label>
            <input 
                   data-id="<?=$afis->getId()?>"
                   class="btn-switch-af" type="checkbox" <?=($afis->getState() ? 'checked="checked"' : '')?>
                   
                   <?php
                        ($this->isGranted('afis.write')) ? '' : 'disabled="disabled"';
                   ?>
            />
<!--             <span class="toggle"></span> -->
        </label>
        </div>
    </td>
</tr>
