<?php ($afis->isDecommissionned()) ? $classicon = 'remove': $classicon = 'ok'; ?>
<tr>
    <td id = '<?php echo $afis->getId(); ?>'><?php echo $afis->getId(); ?></td>
    <td><?php echo $afis->getCode(); ?></td>
    <td><?php echo $afis->getName(); ?></td>
    <td><?php echo $afis->getOrganisation()->getName(); ?></td>
    <td>
        <span class="glyphicon glyphicon-<?php echo $classicon; ?>"></span>
    </td>

    <td>
        <?php $openedHours = $afis->getOpenedhours(); 
        if ($openedHours) { ?>
            <span class="glyphicon glyphicon-time" title="<?php echo $openedHours; ?>"></span>
        <?php } ?>
    </td>

    <td>
        <?php $contacts = $afis->getContacts();
        if ($contacts) { ?>
            <span class="glyphicon glyphicon-phone" title="<?php echo $contacts; ?>"></span>
        <?php } ?>
    </td>

    <td>
        <a  title="Modifier"
            href="#mdl-edit-af"
            class="a-edit-af"
            data-id="<?=$afis->getId()?>"
            data-toggle="modal">
            <span class="glyphicon glyphicon-pencil"></span>
        </a> 
        <a  title="Supprimer"
            href="#mdl-del-af"
            class="a-del-af"
            data-id="<?=$afis->getId()?>"
            data-name="<?=$afis->getCode()?>"
            data-toggle="modal">
            <span class="glyphicon glyphicon-trash"></span>
        </a>
    </td>
</tr>