<?php ($afis->isDecommissionned()) ? $classicon = 'remove': $classicon = 'ok'; ?>
<tr>
    <td id = '<?=$afis->getId()?>'><?=$afis->getId()?></td>
    <td><?=$afis->getName()?></td>
    <td><?=$afis->getShortname()?></td>
    <td><?=$afis->getOrganisation()->getName()?></td>
    <td>
        <span class="glyphicon glyphicon-<?=$classicon?>"></span>
    </td>
    <td>
        <a  title="Modifier"
            href="#mdl-edit-af"
            class="a-edit-af"
            data-id="<?=$afis->getId()?>"
            data-toggle="modal">
            <span class="glyphicon glyphicon-pencil"></span>
        </a> 
        <a  title="Supprimer"
            href="#mdl-del-af"
            class="a-del-af"
            data-id="<?=$afis->getId()?>"
            data-name="<?=$afis->getName()?>"
            data-toggle="modal">
            <span class="glyphicon glyphicon-trash"></span>
        </a>
    </td>
</tr>