<div class="col-md-2" id="sidebar">
    <ul class="nav sidenav">
        <li><a href="#afis">1. AFIS</a></li>
        <ul>
            <?php 
           /* foreach ($allAfis as $afis) {
                if (!$afis->isDecommissionned()) 
                {
                    ?>
                    <li><a href = "#<?=$afis->getId()?>"> <?=$afis->getName()?></li>
                    <?php
                }
            }*/
            ?>
        </ul>
        <li><a href="#oldafis">2. Anciens AFIS</a></li>
        <ul>
            <?php 
            /*
            foreach ($allAfis as $afis) {
                if ($afis->isDecommissionned()) 
                {
                    ?>
                    <li><a href = "#<?=$afis->getId()?>"> <?=$afis->getName()?></li>
                    <?php
                }
            }*/
            ?>
        </ul>
    </ul>
</div>