<?php echo $this->doctype(); ?>

<html lang="fr">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Epeires² - Administration'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/assets/css/core.css') 
                        ->prependStylesheet($this->basePath() . '/assets/css/admin.css')
                        ->prependStylesheet($this->basePath() . '/components/pick-a-color/build/1.2.3/css/pick-a-color-1.2.3.min.css')
                        ->prependStylesheet($this->basePath() . '/components/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/google_material_font.css')
                        ->prependStylesheet($this->basePath() . '/components/bootstrap-material-design/dist/css/ripples.min.css')
                        ->prependStylesheet($this->basePath() . '/components/bootstrap-material-design/dist/css/material-fullpalette.min.css')
                        ->prependStylesheet($this->basePath() . '/components/bootstrap-material-design/dist/css/roboto.min.css')
                        ->prependStylesheet($this->basePath() . '/components/bootstrap/dist/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/components/jquery-ui/themes/smoothness/jquery-ui.min.css')
        				?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/assets/js/application.js')
        							  ->prependFile($this->basePath() . '/components/pick-a-color/build/1.2.3/js/pick-a-color-1.2.3.min.js')
        							  ->prependFile($this->basePath() . '/components/pick-a-color/build/dependencies/tinycolor-0.9.15.min.js')
                        ->prependFile($this->basePath() . '/components/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js')
                        ->prependFile($this->basePath() . '/components/momentjs/min/moment.min.js')
                        ->prependFile($this->basePath() . '/components/jquery-mousewheel/jquery.mousewheel.min.js')
                        ->prependFile($this->basePath() . '/components/bootstrap-material-design/dist/js/material.min.js')
                        ->prependFile($this->basePath() . '/components/bootstrap-material-design/dist/js/ripples.min.js')
                        ->prependFile($this->basePath() . '/components/jquery-mousewheel/jquery.mousewheel.min.js')
                        ->prependFile($this->basePath() . '/components/bootstrap/dist/js/bootstrap.min.js')
                        ->prependFile($this->basePath() . '/components/noty/js/noty/packaged/jquery.noty.packaged.min.js')
                        ->prependFile($this->basePath() . '/components/jquery-ui/ui/minified/i18n/datepicker-fr.min.js')
                        ->prependFile($this->basePath() . '/components/jquery-ui/jquery-ui.min.js')
                        ->prependFile($this->basePath() . '/components/jquery/dist/jquery.min.js')
        							   ?>

    </head>
    <body data-spy="scroll" data-target="#sidebar">
    	<div class="header">
    		<ul class="inline">
    				<?php echo $this->userMenu(); ?>
    				<li id="clock" class="pull-right"></li>
    		</ul>
    	</div>
	<div class="navbar navbar-after-top">
		<div class="navbar-inner">
			<a class="brand" href="<?php echo $this->url('administration'); ?>">Epeires<sup>2</sup></a>
			<?php if($this->title){?>
			<a class="brand" href="#">
				<?php 
					echo " : <small>".$this->title."</small>"; 
				?>
			</a>
			<?php }?>
			<ul class="nav">
				<li><a
					href="<?php echo $this->url('administration', array('controller'=>'config', 'action'=>'index')) ?>"
					data-original-title="Paramètres globaux de l'application"
					data-placement="bottom" data-toggle="tooltip">Paramètres</a>
				</li>
                                <?php if($this->isGranted('admin.centre')) : ?>
				<li class="dropdown">
					<a href="#"
					class="dropdown-toggle"
					data-toggle="dropdown">Centres <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><a
							href="<?php echo $this->url('administration', array('controller'=>'centre', 'action'=>'index'))?>"
							data-title="Centres > Général">Général</a>
						</li>
						<li><a
							href="<?php echo $this->url('administration', array('controller'=>'radio', 'action'=>'index'))?>"
							data-title="Centres > Radio">Radio</a>
						</li>
						<li>
							<a
							href="<?php echo $this->url('administration', array('controller'=>'radars', 'action'=>'index'))?>"
							data-title="Centres > Radars">Radars</a>
						</li>
					</ul>
				</li>
                                <?php endif; ?>
                                <?php if($this->isGranted('admin.users')) : ?>
				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">Utilisateurs <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><a
							data-title="Utilisateurs > Administration"
							href="<?php echo $this->url('administration', array('controller'=>'users', 'action'=>'index')) ?>">Liste</a>
						</li>
						<li><a
							data-title="Utilisateurs > Roles"
							href="<?php echo $this->url('administration', array('controller'=>'roles', 'action'=>'index')) ?>">Rôles</a>
						</li>
						<li><a
							data-title="Utilisateurs > IPO"
							href="<?php echo $this->url('administration', array('controller'=>'ipos', 'action'=>'index')) ?>">Liste IPO</a>
						</li>
						<li><a
							data-title="Utilisateurs > Op Sup"
							href="<?php echo $this->url('administration', array('controller'=>'opsups', 'action'=>'index')) ?>">Liste Op Sup</a>
						</li>
					</ul>
				</li>
                <?php endif; ?>
                <?php if($this->isGranted('admin.categories') ||
                         $this->isGranted('admin.models')) : ?>
				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">Personnalisation <b class="caret"></b></a>
					<ul class="dropdown-menu">
                        <?php if($this->isGranted('admin.categories')) : ?>
						<li><a
							data-title="Personnalisation > Catégories"
							href="<?php echo $this->url('administration', array('controller'=>'categories', 'action'=>'index')) ?>">Catégories</a>
						</li>
                        <li><a
                             data-title="Personnalisation > Catégories par défaut"
                             href="<?php echo $this->url('administration', array('controller' => 'categories', 'action' => 'defaultindex'))?>">Catégories par défaut</a>
                        </li>
                        <?php endif; ?>
                        <?php if($this->isGranted('admin.models')) : ?>
						<li><a
							data-title="Personnalisation > Modèles"
							href="<?php echo $this->url('administration', array('controller'=>'models', 'action'=>'index')) ?>"
							>Modèles</a></li>
                        <?php endif; ?>
					</ul>
				</li>
                <?php endif; ?>
                <?php if($this->isGranted('admin.radio') || 
                		$this->isGranted('admin.zonesmil') ||
                		$this->isGranted('admin.tabs')) : ?>
                <li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">Onglets <b class="caret"></b></a>
					<ul class="dropdown-menu">
					    <?php if($this->isGranted('admin.tabs')) : ?>
						<li>
						<a data-title="Onglets > Gestion"
							href="<?php echo $this->url('administration', array('controller' => 'tabs', 'action' => 'index'))?>">Gestion des onglets</a>
						</li>
						<?php endif;?>
					    <?php if($this->isGranted('admin.radio')) : ?>
						<li><a
							data-title="Onglets > Fréquences"
							href="<?php echo $this->url('administration', array('controller'=> 'radio', 'action' => 'config'))?>">Onglet fréquences</a>
						</li>
                        <?php endif; ?>
                        <?php if($this->isGranted('admin.zonesmil')) : ?>
                        <li><a
							data-title="Onglets > Zones militaires"
							href="<?php echo $this->url('administration', array('controller'=> 'mil', 'action' => 'config'))?>">Onglet zones militaires</a>
						</li>
						<?php endif;?>
					</ul>
				</li>
                <?php endif;?>
			</ul>
		</div>
	</div>
	
	<div class="content">
		<div class="warnings">
		<?php if (isset($this->messages['successMessages'])) { ?>
			<?php foreach ($this->messages['successMessages'] as $message) { ?>
				<div class="alert alert-success">
					<a class="close" data-dismiss="alert" href="#">&times;</a>
					<?php echo $message ?>
				</div>
			<?php }?>
		<?php } ?>

		<?php if (isset($this->messages['errorMessages'])) { ?>
			<?php foreach ($this->messages['errorMessages'] as $message) { ?>
				<div class="alert alert-error">
					<a class="close" data-dismiss="alert" href="#">&times;</a>
					<?php echo $message ?>
				</div>
			<?php }?>
		<?php } ?>
		</div>
	
        <?php echo $this->content; ?>
    
    </div> <!-- /container -->
        
    <?php 
	if(!$this->zfcuserIdentity()){
			echo $this->modalWindow("loginwindow", "<h3>Connexion</h3>", "", $this->zfcUserLoginWidget(array('redirect'=>$this->url('administration'))));
	} ?>
        
    <?php echo $this->inlineScript() ?>
    </body>
</html>
