<?php echo $this->doctype(); ?>

<html lang="fr">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('PV CdS'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/application.css') 
                        ->prependStylesheet($this->basePath() . '/css/admin.css')
                        ->prependStylesheet($this->basePath() . '/css/spectrum.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui.min.css')
        				?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/application.js')
        							  ->prependFile($this->basePath() . '/js/spectrum.js')
        							  ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/noty/themes/default.js')
                                      ->prependFile($this->basePath() . '/js/noty/layouts/bottomRight.js')
                                      ->prependFile($this->basePath() . '/js/noty/jquery.noty.js')
                                      ->prependFile($this->basePath() . '/js/jquery-ui.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js')
        							   ?>

    </head>
    <body>
    	<div class="header">
    		<ul class="inline">
    				<li class="dropdown">
    					<a class="dropdown-toggle" data-toggle="dropdown" href="#">
    					<i class="icon-user"></i>
    					<?php if($this->zfcUserIdentity()) {
    							echo $this->zfcUserIdentity()->getUserName();
    					} else {
								echo "Non connecté";
						}		
    					?>
    					 	<b class="caret"></b>
    					</a>
    					<ul class="dropdown-menu">
    					<?php if($this->zfcUserIdentity()) {
    						echo "<li><a href=\"".$this->url('zfcuser/logout')."?redirect=".$this->url('application')."\">Se déconnecter</a></li>";
    					} else {
    						echo "<li><a href=\"#loginwindow\" data-toggle=\"modal\" >Se connecter</a></li>";
    					}
    					?>
    					</ul>
    				</li>
    				<li id="clock" class="pull-right"></li>
    		</ul>
    	</div>
	<div class="navbar navbar-after-top">
		<div class="navbar-inner">
			<a class="brand" href="<?php echo $this->url('administration'); ?>">Epeires<sup>2</sup></a>
			<?php if($this->title){?>
			<a class="brand" href="#">
				<?php 
					echo " : <small>".$this->title."</small>"; 
				?>
			</a>
			<?php }?>
			<ul class="nav">
				<?php if($this->actions) {?>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle"
					data-toggle="dropdown">Actions <b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<?php echo $this->actions;?>
					</ul>
				</li>
				<li class="divider-vertical"></li>
				<?php }?>
				<li><a
					href="<?php echo $this->url('administration', array('controller'=>'config', 'action'=>'index')) ?>"
					data-original-title="Paramètres globaux de l'application"
					data-placement="bottom" data-toggle="tooltip">Paramètres</a>
				</li>
				<li class="dropdown">
					<a href="#"
					class="dropdown-toggle"
					data-toggle="dropdown">Centres <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><a
							href="<?php echo $this->url('administration', array('controller'=>'centre', 'action'=>'index'))?>"
							data-title="Centres > Général">Général</a>
						</li>
						<li><a
							href="<?php echo $this->url('administration', array('controller'=>'radio', 'action'=>'index'))?>"
							data-title="Centres > Radio">Radio</a>
						</li>
						<li>
							<a
							href="<?php echo $this->url('administration', array('controller'=>'radars', 'action'=>'index'))?>"
							data-title="Centres > Radars">Radars</a>
						</li>
					</ul>
				</li>
				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">Utilisateurs <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><a
							data-title="Utilisateurs > Administration"
							href="<?php echo $this->url('administration', array('controller'=>'users', 'action'=>'index')) ?>">Administration</a>
						</li>
						<li><a
							data-title="Utilisateurs > Roles"
							href="<?php echo $this->url('administration', array('controller'=>'roles', 'action'=>'index')) ?>">Rôles</a>
						</li>
						
					</ul>
				</li>
				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">Personnalisation <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><a
							data-title="Personnalisation > Catégories"
							href="<?php echo $this->url('administration', array('controller'=>'categories', 'action'=>'index')) ?>">Catégories</a>
						</li>
						<li><a href="<?php echo $this->url('administration', array('controller'=>'fields', 'action'=>'index')) ?>"
							class="disabled">Champs</a></li>
						<li><a
							href="<?php echo $this->url('administration', array('controller'=>'models', 'action'=>'index')) ?>"
							>Modèles</a></li>
					</ul>
				</li>
			</ul>
		</div>
	</div>
	
	<div class="content">
		<div class="warnings">
		<?php if (isset($this->messages['successMessages'])) { ?>
			<?php foreach ($this->messages['successMessages'] as $message) { ?>
				<div class="alert alert-success">
					<a class="close" data-dismiss="alert" href="#">&times;</a>
					<?php echo $message ?>
				</div>
			<?php }?>
		<?php } ?>

		<?php if (isset($this->messages['errorMessages'])) { ?>
			<?php foreach ($this->messages['errorMessages'] as $message) { ?>
				<div class="alert alert-error">
					<a class="close" data-dismiss="alert" href="#">&times;</a>
					<?php echo $message ?>
				</div>
			<?php }?>
		<?php } ?>
		</div>
	
        <?php echo $this->content; ?>
    
    </div> <!-- /container -->
        
    <?php 
	if(!$this->zfcuserIdentity()){
			echo $this->modalWindow("loginwindow", "<h3>Connexion</h3>", "", $this->zfcUserLoginWidget(array('redirect'=>$this->url('administration'))));
	} ?>
        
    <?php echo $this->inlineScript() ?>
    </body>
</html>
