<?php $this->headScript()->appendFile($this->basePath() . '/js/roles.js')?>

<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
<table class="table table-bordered table-condensed">

<!-- Permission titles -->
<thead>
<tr>
<th class="no-border" colspan="3"></th>
<?php 

foreach ($this->config as $key => $value){
	echo "<th colspan=\"".count($value)."\">".$key."</th>";
}
?>
</tr>
</thead>

<!-- Permissions -->
<tr>
<td><a class="btn btn-mini" href="#role-container" data-toggle="modal" id="add-role">Ajouter</a></td>
<td><b>Nom</b></td>
<td><b>Parent</b></td>
<?php 

$permissions = array();

foreach($this->config as $key => $value){
	foreach ($value as $code => $name){
		echo "<td>".$name."</td>";
		$permissions[] = $code;
	}
}?>
</tr>

<!-- Roles -->
<?php foreach($this->roles as $role){
	echo "<tr>";
	echo "<td>";
		echo "<a 
				title=\"Modifier\" 
				href=\"#role-container\" 
				class=\"mod-role\" 
				data-id=\"".$role->getId()."\" 
				data-name=\"".$role->getName()."\" 
				data-toggle=\"modal\"><i class=\"icon-pencil\"></i></a>  ";
		echo "<a 
				title=\"Supprimer\" 
				href=\"#confirm-delete-role\" 
				data-href=\"".$this->url('administration', array('controller'=>'roles', 'action'=>'deleterole'), array('query'=>array('id'=>$role->getId())))."\" 
				class=\"delete-role\" 
				data-id=\"".$role->getId()."\" 
				data-name=\"".$role->getName()."\" 
				data-toggle=\"modal\"><i class=\"icon-trash\"></i> </a>";
	echo '</td>';
	echo "<td>".$role->getName()."</td>";
	echo "<td>".($role->getParent() ? $role->getParent()->getName() : "<em>Aucun</em>")."</td>";
	foreach ($permissions as $permission){
		echo "<td>";
			$inherited = false;
			echo "<input class=\"permission\" 
					data-roleid=\"".$role->getId()."\"
					data-permission=\"".$permission."\"  
					type=\"checkbox\" ";
			if($role->hasPermission($permission)){
				if(!$role->hasPermission($permission, false)){
					//inherited -> can't be modified
					$inherited = true;
					echo "disabled=\"disabled\" ";
				}
				echo "checked=\"checked\"";
			}
			echo ">";
		if($inherited){
			echo " (hérité)";
		}
		echo "</td>";
	}
	echo "</tr>";	
}?>

</table>
</div>
</div>
</div>

<?php echo $this->modalWindow("role-container", "<h3>Nouveau rôle</h3>", "", "<div id=\"role-form\"></div>")?>

<?php echo $this->modalwindow("confirm-delete-role",
						"<h3>Confirmer la suppression ?</h3>",
						"", 
						null, 
						"<p>Voulez-vous vraiment supprimer le rôle <em><span id=\"role-name\"></span></em> ?</p>",
						"<a class=\"btn btn-danger\" id=\"delete-role-href\">Confirmer</a>
						<a class=\"btn\" href=\"#\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</a>") ?>	



<?php $this->inlineScript()->captureStart();?>

roles('<?php echo $this->url('administration'); ?>');

<?php $this->inlineScript()->captureEnd();?>