<?php $this->headScript()->appendFile($this->basePath() . '/components/jquery-stupid-table/stupidtable.min.js');
      $this->headScript()->appendFile($this->basePath() . '/assets/js/zonesmil.js');
?>

<div class="container-fluid">
    <div class="row">
	<div class="col-md-9">
		<p></p>
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title">Zones militaires </h4>
			</div>
			<div class="panel-body">
				<table class="table table-striped sortable">
                                    <thead>
                                    <tr>
                                        <th>id</th>
                                        <th data-sort="string">Nom</th>
                                        <th>Couleur</th>
                                        <th>Filtre d'import</th>
                                        <th data-sort="string">Zones associées</th>
                                        <th>NM B2B</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                        <?php 
                                        foreach ($this->cats as $cat){
                                            echo '<tr>';
                                            echo '<td>'.$cat->getId().'</td>';
                                            echo '<td>'.$cat->getName().'</td>';
                                            echo "<td><span class=\"label\" style=\"background-color:".$cat->getColor()."\">".$cat->getColor()."</span></td>";
                                            echo '<td>'.$cat->getFilter().'</td>';
                                            echo '<td>'.$cat->getZonesRegex().'</td>';
                                            echo '<td>'.($cat->isNMB2B()?"<span class=\"glyphicon glyphicon-ok\"></span>":"<span class=\"glyphicon glyphicon-remove\"></span>").'</td>';
                                            echo '<td><a '
                                                    . 'href="#zone-container" '
                                                    . 'class="mod-mil" '
                                                    . 'data-id="'.$cat->getId().'" '
                                                    . 'data-name="'.$cat->getName().'" '
                                                    . 'title="Modifier" '
                                                    . 'data-toggle="modal"><span class="glyphicon glyphicon-pencil"></span></a></td>';
                                            echo '</tr>';
                                        }
                                        ?>
                                    </tbody>
                                </table>
			</div>
		</div>
	</div>
        <div class="col-md-3">
            <p></p>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">Aide</h4>
                </div>
                <div class="panel-body">
                    <p>Cette page permet de configurer les zones militaires affectées aux catégories de type "Zone militaire".</p>
                    <p>Il est nécessaire de créer au préalable les catégories via <a href="<?php echo $this->url('administration', array('controller' => 'categories', 'action' => 'index'))?>">la page de configuration des catégories</a>.</p>
                    <p>La création d'un oglet spécifique doit se faire dans la page de configuration spécifique.</p>
                    <p>La récupération des données via NM B2B nécessite que la connexion soit préalablement configurée par l'administrateur technique.</p>
                </div>
            </div>
        </div>
    </div>

</div>

			
<?php echo $this->modalwindow("zone-container", "<h4 id=\"zone-title\"></h4>", "", "<div id=\"zone-form\"></div>") ?>


<?php $this->inlineScript()->captureStart();?>

mil('<?php echo $this->url('administration'); ?>');

$(".sortable").stupidtable();

$(".sortable").bind('aftertablesort', function(event, data){
	var th = $(this).find("th");
    th.find(".arrow").remove();
    var arrow = data.direction === "asc" ? "<span class=\"glyphicon glyphicon-arrow-down\"></span>" : "<span class=\"glyphicon glyphicon-arrow-up\"></span>";
    th.eq(data.column).append('<span class="arrow"> ' + arrow +'</span>');
});

$("table th:eq(1)").trigger('click');

<?php echo $this->notifications($this->messages); ?>
                                        
<?php $this->inlineScript()->captureEnd();?>
