

<?php 
$this->form->setAttribute('action', $this->url('administration', array('controller'=>'mil', 'action'=>'save')));
$this->form->setAttribute('class', 'form-horizontal');
$this->form->prepare();

echo $this->form()->openTag($this->form);
?>
<div class="modal-body">
<?php


echo $this->formHidden($this->form->get('id'));

echo $this->controlGroup($this->formLabel($this->form->get('name')->setLabelAttributes(array('class' => 'control-label'))),
						$this->formInput($this->form->get('name')));

echo $this->controlGroup($this->formLabel($this->form->get('color')->setLabelAttributes(array('class' => 'control-label'))),
						$this->formInput($this->form->get('color')->setAttribute('class', 'pick-a-color')));

echo $this->controlGroup($this->formLabel($this->form->get('filter')->setLabelAttributes(array('class' => 'control-label'))),
		$this->formInput($this->form->get('filter')));

echo $this->controlGroup($this->formLabel($this->form->get('zonesRegex')->setLabelAttributes(array('class' => 'control-label'))),
		$this->formInput($this->form->get('zonesRegex')));

echo $this->controlGroup($this->formLabel($this->form->get('nmB2B')->setLabelAttributes(array('class' => 'control-label'))),
		$this->formCheckbox($this->form->get('nmB2B')));

echo $this->formHidden($this->form->get('shortname'));
						
echo $this->formHidden($this->form->get('compactmode'));

echo $this->formHidden($this->form->get('timeline'));

echo $this->formSelect($this->form->get('readroles')->setAttributes(array('class' => 'unvisible')));
?>


</div>
<div class="modal-footer">
<?php 

	echo $this->formSubmit($this->form->get('submit'));
?>
<a id="cancel-form" class="btn" href="#" data-dismiss="modal" aria-hidden="true">Annuler</a>
</div>
<?php 
echo $this->form()->closeTag();
?>
