<?php $this->headScript()->appendFile($this->basePath() . '/assets/js/ipos.js')?>
<div class="container-fluid">
<div class="row">
<div class="col-md-12">
<p></p>
<div class="panel panel-default">
<div class="panel-heading">
	<h4 class="panel-title">Liste des <?php echo $this->translate('IPO') ?></h4>
</div>
<div class="panel-body">
<table class="table table-striped sortable">
<thead>
	<tr>
		<th data-sort="int">Id</th>
		<th data-sort="string" data-autosort="true">Nom</th>
		<th>Organisation</th>
		<th><a class="btn btn-xs btn-primary" href="#ipo-container" data-toggle="modal" id="add-ipo">Ajouter</a></th>
	</tr>
</thead>

<tbody>
	<?php 
	foreach ($this->ipos as $ipo){
		echo '<tr>';
		echo '<td>'.$ipo->getId().'</td>';
		echo '<td>'.$ipo->getName().'</td>';
		echo '<td>'.$ipo->getOrganisation()->getName().'</td>';
		echo '<td>';
		echo "<a 
				title=\"Modifier\" 
				href=\"#ipo-container\" 
				class=\"mod-ipo\" 
				data-id=\"".$ipo->getId()."\" 
				data-name=\"".$ipo->getName()."\" 
				data-toggle=\"modal\"><span class=\"glyphicon glyphicon-pencil\"></span></a>  ";
		echo "<a 
				title=\"Supprimer\" 
				href=\"#confirm-delete-ipo\" 
				data-href=\"".$this->url('administration', array('controller'=>'ipos', 'action'=>'deleteipo'), array('query'=>array('id'=>$ipo->getId())))."\" 
				class=\"delete-ipo\" 
				data-id=\"".$ipo->getId()."\" 
				data-name=\"".$ipo->getName()."\" 
				data-toggle=\"modal\"><span class=\"glyphicon glyphicon-trash\"></span> </a>";
		echo '</td>';
		echo '</tr>';
	}
	?>
</tbody>

</table>
</div>
</div>
</div>
</div>
</div>
<?php echo $this->modalWindow("ipo-container", "<h4 id=\"ipo-title\">Nouvel ".$this->translate('IPO')."</h4>", "", "<div id=\"ipo-form\"></div>")?>

<?php echo $this->modalwindow("confirm-delete-ipo",
						"<h4>Confirmer la suppression ?</h4>",
						"", 
						null, 
						"<p>Voulez-vous vraiment supprimer l'IPO <em><span id=\"ipo-name\"></span></em> ?</p>",
						"<a class=\"btn btn-danger\" id=\"delete-ipo-href\">Confirmer</a>
						<button class=\"btn\" href=\"#\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</button>") ?>	


<?php $this->inlineScript()->captureStart();?>

ipos('<?php echo $this->url('administration')?>');

<?php echo $this->notifications($this->messages); ?>

<?php $this->inlineScript()->captureEnd();?>