stages:
  - test
  - build_image

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
  - vendor/

.before_script_test:
  before_script:
  # Setup Selenium
  - export DISPLAY=:99
  - Xvfb :99 &
  - sleep 3
  # WARNING - Takes a long time to start up. Php extensions compilation time should assure us that it's launched correctly
  - wget -O selenium.jar https://selenium-release.storage.googleapis.com/3.9/selenium-server-standalone-3.9.1.jar
  - java -jar selenium.jar -port 4444 >/dev/null 2>&1 &
  #download sonar scanner
  - wget -O sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
  - unzip ./sonar-scanner.zip
  #donwload dependencies
  - composer --version
  - composer install --no-interaction --prefer-dist
  #configure database
  - cp $DOCTRINE config/autoload/doctrine.local.php
  #populate database
  - touch logs/epeires2.log
  - chmod -Rf a+rwx logs
  - vendor/bin/laminas-development-mode enable
  - vendor/bin/doctrine-module migrations:migrate --no-interaction -vvv
  - vendor/bin/doctrine-module orm:generate-proxies
  - vendor/bin/laminas epeires2:initdb --no-interaction
  - vendor/bin/doctrine-module data-fixture:import default_group --no-interaction
  - chmod a+rwx -Rf ./data
  - chmod +x ./local-php-security-checker
  #launch server
  - cp -f tests/build/vhost.conf /etc/apache2/sites-enabled/
  - sed -e "s?%BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-enabled/vhost.conf
  - echo ServerName localhost >> /etc/apache2/apache2.conf
  - rm /etc/apache2/sites-enabled/000-default.conf
  - a2enmod rewrite
  - service apache2 restart
    # Make sure Webdriver is running
  - curl http://localhost:4444/wd/hub/status
    #Make sure webserver is running
  - curl http://localhost/app/events/testAuthentication
  - apache2ctl -S

variables:
  MYSQL_DATABASE: epeires2
  MYSQL_ROOT_PASSWORD: epeires2
  APP_ENV: development
  TIMEZONE: Europe/Paris

test:8.0-mariadb105:
  extends: .before_script_test
  image: registry.asap.dsna.fr/bruno.spyckerelle/epeires-test-images:php80.1
  stage: test
  services:
    - mariadb:10.5
  variables:
    DOCTRINE: "config/autoload/doctrine.gitlab-ci.mariadb.php"
  script:
    - php vendor/bin/codecept run acceptance
    - php vendor/bin/codecept run unit --coverage-text --no-colors
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - tests/_output/

test:8.0-mariadb106:
  extends: .before_script_test
  image: registry.asap.dsna.fr/bruno.spyckerelle/epeires-test-images:php80.1
  stage: test
  services:
    - mariadb:10.6
  variables:
    DOCTRINE: "config/autoload/doctrine.gitlab-ci.mariadb.php"
  script:
    - php vendor/bin/codecept run acceptance
    - php vendor/bin/codecept run unit --coverage-text --no-colors
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - tests/_output/

test:8.0-mariadb107:
  extends: .before_script_test
  image: registry.asap.dsna.fr/bruno.spyckerelle/epeires-test-images:php80.1
  stage: test
  services:
    - mariadb:10.7
  variables:
    DOCTRINE: "config/autoload/doctrine.gitlab-ci.mariadb.php"
  script:
    - php vendor/bin/codecept run acceptance
    - php vendor/bin/codecept run unit --coverage-text --no-colors
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - tests/_output/

test:8.0-mariadb108:
  extends: .before_script_test
  image: registry.asap.dsna.fr/bruno.spyckerelle/epeires-test-images:php80.1
  stage: test
  services:
    - mariadb:10.8
  variables:
    DOCTRINE: "config/autoload/doctrine.gitlab-ci.mariadb.php"
  script:
    - php vendor/bin/codecept run acceptance
    - php vendor/bin/codecept run unit --coverage-text --no-colors
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - tests/_output/

test:8.0-mariadb109:
  extends: .before_script_test
  image: registry.asap.dsna.fr/bruno.spyckerelle/epeires-test-images:php80.1
  stage: test
  services:
    - mariadb:10.9
  variables:
    DOCTRINE: "config/autoload/doctrine.gitlab-ci.mariadb.php"
  script:
    - php vendor/bin/codecept run acceptance
    - php vendor/bin/codecept run unit --coverage-text --no-colors
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - tests/_output/

test:8.0-mysql57:
  extends: .before_script_test
  image: registry.asap.dsna.fr/bruno.spyckerelle/epeires-test-images:php80.1
  stage: test
  services:
    - mysql:5.7
  variables:
    DOCTRINE: "config/autoload/doctrine.gitlab-ci.mysql.php"
  script:
    - php vendor/bin/codecept run acceptance
    - php vendor/bin/codecept run unit --coverage-text --no-colors
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - tests/_output/

test:8.0-mysql80:
  extends: .before_script_test
  image: registry.asap.dsna.fr/bruno.spyckerelle/epeires-test-images:php80.1
  stage: test
  services:
    - mysql:8.0
  variables:
    DOCTRINE: "config/autoload/doctrine.gitlab-ci.mysql.php"
  script:
    - php vendor/bin/codecept run acceptance
    - php vendor/bin/codecept run unit --coverage-text --no-colors
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - tests/_output/

test:8.1-mariadb105:
  extends: .before_script_test
  image: registry.asap.dsna.fr/bruno.spyckerelle/epeires-test-images:php81
  stage: test
  services:
    - mariadb:10.5
  variables:
    DOCTRINE: "config/autoload/doctrine.gitlab-ci.mariadb.php"
  script:
    - php vendor/bin/codecept run acceptance
    - php vendor/bin/codecept run unit --coverage-text --no-colors
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - tests/_output/

test:8.1-mariadb106:
  extends: .before_script_test
  image: registry.asap.dsna.fr/bruno.spyckerelle/epeires-test-images:php81
  stage: test
  services:
    - mariadb:10.6
  variables:
    DOCTRINE: "config/autoload/doctrine.gitlab-ci.mariadb.php"
  script:
    - php vendor/bin/codecept run acceptance
    - php vendor/bin/codecept run unit --coverage-text --no-colors
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - tests/_output/

test:8.1-mariadb107:
  extends: .before_script_test
  image: registry.asap.dsna.fr/bruno.spyckerelle/epeires-test-images:php81
  stage: test
  services:
    - mariadb:10.7
  variables:
    DOCTRINE: "config/autoload/doctrine.gitlab-ci.mariadb.php"
  script:
    - php vendor/bin/codecept run acceptance
    - php vendor/bin/codecept run unit --coverage-text --no-colors
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - tests/_output/

test:8.1-mariadb108:
  extends: .before_script_test
  image: registry.asap.dsna.fr/bruno.spyckerelle/epeires-test-images:php81
  stage: test
  services:
    - mariadb:10.8
  variables:
    DOCTRINE: "config/autoload/doctrine.gitlab-ci.mariadb.php"
  script:
    - php vendor/bin/codecept run acceptance
    - php vendor/bin/codecept run unit --coverage-text --no-colors
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - tests/_output/

test:8.1-mariadb109:
  extends: .before_script_test
  image: registry.asap.dsna.fr/bruno.spyckerelle/epeires-test-images:php81
  stage: test
  services:
    - mariadb:10.9
  variables:
    DOCTRINE: "config/autoload/doctrine.gitlab-ci.mariadb.php"
  script:
    - php vendor/bin/codecept run acceptance
    - php vendor/bin/codecept run unit --coverage-text --no-colors
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - tests/_output/

test:8.1-mysql57:
  extends: .before_script_test
  image: registry.asap.dsna.fr/bruno.spyckerelle/epeires-test-images:php81
  stage: test
  services:
    - mysql:5.7
  variables:
    DOCTRINE: "config/autoload/doctrine.gitlab-ci.mysql.php"
  script:
    - php vendor/bin/codecept run acceptance
    - php vendor/bin/codecept run unit --coverage-text --no-colors
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - tests/_output/

test:8.1-mysql80:
  extends: .before_script_test
  image: registry.asap.dsna.fr/bruno.spyckerelle/epeires-test-images:php81
  stage: test
  services:
    - mysql:8.0
  variables:
    DOCTRINE: "config/autoload/doctrine.gitlab-ci.mysql.php"
  script:
    - php vendor/bin/codecept run acceptance
    - php vendor/bin/codecept run unit --coverage-text --no-colors
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - tests/_output/

test:8.2-mariadb105:
  extends: .before_script_test
  image: registry.asap.dsna.fr/bruno.spyckerelle/epeires-test-images:php82
  stage: test
  services:
    - mariadb:10.5
  variables:
    DOCTRINE: "config/autoload/doctrine.gitlab-ci.mariadb.php"
  script:
    - php vendor/bin/codecept run acceptance
    - php vendor/bin/codecept run unit --coverage-text --no-colors
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - tests/_output/

test:8.2-mariadb106:
  extends: .before_script_test
  image: registry.asap.dsna.fr/bruno.spyckerelle/epeires-test-images:php82
  stage: test
  services:
    - mariadb:10.6
  variables:
    DOCTRINE: "config/autoload/doctrine.gitlab-ci.mariadb.php"
  script:
    - php vendor/bin/codecept run acceptance
    - php vendor/bin/codecept run unit --coverage-text --no-colors
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - tests/_output/

test:8.2-mariadb107:
  extends: .before_script_test
  image: registry.asap.dsna.fr/bruno.spyckerelle/epeires-test-images:php82
  stage: test
  services:
    - mariadb:10.7
  variables:
    DOCTRINE: "config/autoload/doctrine.gitlab-ci.mariadb.php"
  script:
    - php vendor/bin/codecept run acceptance
    - php vendor/bin/codecept run unit --coverage-text --no-colors
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - tests/_output/

test:8.2-mariadb108:
  extends: .before_script_test
  image: registry.asap.dsna.fr/bruno.spyckerelle/epeires-test-images:php82
  stage: test
  services:
    - mariadb:10.8
  variables:
    DOCTRINE: "config/autoload/doctrine.gitlab-ci.mariadb.php"
  script:
    - php vendor/bin/codecept run acceptance
    - php vendor/bin/codecept run unit --coverage-text --no-colors
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - tests/_output/

test:8.2-mariadb109:
  extends: .before_script_test
  image: registry.asap.dsna.fr/bruno.spyckerelle/epeires-test-images:php82
  stage: test
  services:
    - mariadb:10.9
  variables:
    DOCTRINE: "config/autoload/doctrine.gitlab-ci.mariadb.php"
  script:
    - php vendor/bin/codecept run acceptance
    - php vendor/bin/codecept run unit --coverage-text --no-colors
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - tests/_output/

test:8.2-mysql57:
  extends: .before_script_test
  image: registry.asap.dsna.fr/bruno.spyckerelle/epeires-test-images:php82
  stage: test
  services:
    - mysql:5.7
  variables:
    DOCTRINE: "config/autoload/doctrine.gitlab-ci.mysql.php"
  script:
    - php vendor/bin/codecept run acceptance
    - php vendor/bin/codecept run unit --coverage-text --no-colors
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - tests/_output/

test:8.2-mysql80:
  extends: .before_script_test
  image: registry.asap.dsna.fr/bruno.spyckerelle/epeires-test-images:php82
  stage: test
  services:
    - mysql:8.0
  variables:
    DOCTRINE: "config/autoload/doctrine.gitlab-ci.mysql.php"
  script:
    - php vendor/bin/codecept run acceptance
    - php vendor/bin/codecept run unit --coverage-text --no-colors
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - tests/_output/

test:docker:
  extends: .before_script_test
  image: registry.asap.dsna.fr/bruno.spyckerelle/epeires-test-images:php80.1
  stage: test
  services:
  - mariadb:10.5.15
  variables:
    DOCTRINE: "config/autoload/doctrine.gitlab-ci.mariadb.php"
  script:
  - ./sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner -Dsonar.login=${SONAR_TOKEN}
  - php vendor/bin/codecept run acceptance
  - php vendor/bin/codecept run unit --coverage-text --no-colors
  - ./local-php-security-checker

docker_images:
  stage: build_image
  image: docker:git
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
