language: php

php:
  - 5.6
  - 7.0

services:
  - mysql

install:
   - composer install --dev --no-interaction

env:
   - APP_ENV=development

before_script:
  - mysql -e 'create database epeires2;'
  - php public/index.php migrations:migrate --no-interaction
  - php public/index.php orm:generate-proxies
  - php public/index.php data-fixture:import --no-interaction --append

script:
  - php codecept run --coverage-xml
  
after_success:
  - php vendor/bin/coveralls -v -x tests/_output/coverage.xml
