language: php

php:
  - 5.6
  - 7.0

services:
  - mysql

install:
   - composer install --dev --no-interaction

env:
   - APP_ENV=development

before_script:
  - if [ $(phpenv version-name) = "7.0" ]; then phpenv config-rm xdebug.ini; fi
  - mysql -e 'create database epeires2;'
  - php public/index.php migrations:migrate --no-interaction
  - php public/index.php orm:generate-proxies
  - php public/index.php data-fixture:import --no-interaction --append

script: 
  - mkdir -p build/logs
  - if [ $(phpenv version-name) = "5.6" ]; then phpunit --stderr; fi
  - if [ $(phpenv version-name) = "7.0" ]; then phpdbg -qrr phpunit --stderr; fi
  
after_success:
  - php vendor/bin/coveralls -v -x coverage.xml
