language: php

php:
  - 5.6
  - 7.0

services:
  - mysql

install:
   - composer install --dev --no-interaction

before_script:
  - phpenv config-rm xdebug.ini
  - mysql -e 'create database epeires2;'
  - php public/index.php migrations:migrate --no-interaction
  - php public/index.php orm:generate-proxies
  - php public/index.php data-fixture:import --no-interaction --append

script: 
  - mkdir -p build/logs
  - phpunit --stderr
  
after_success:
  - php vendor/bin/coveralls -v -x coverage.xml
