language: php

php:
  - 5.6
  - 7.0

services:
  - mysql

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/travis/php-cache
    - ${TRAVIS_BUILD_DIR}/travis/lib-cache
    - $HOME/.composer/cache

before_install:
  # Setup Selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - sh -c "if [ ! -e ${TRAVIS_BUILD_DIR}/travis/lib-cache/selenium.jar ]; then wget -O ${TRAVIS_BUILD_DIR}/travis/lib-cache/selenium.jar https://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.0.jar; fi;"
  - java -jar ${TRAVIS_BUILD_DIR}/travis/lib-cache/selenium.jar -port 4444 >/dev/null 2>&1 & # WARNING - Takes a long time to start up. Keep here

install:
   - composer install --dev --no-interaction --prefer-dist

env:
   - APP_ENV=development

before_script:
  # Disable xdebug when we don't need coverage to speed up testing
  #- phpenv config-rm xdebug.ini
  - mysql -e 'create database epeires2;'
  - php public/index.php migrations:migrate --no-interaction
  - php public/index.php orm:generate-proxies
  - php public/index.php data-fixture:import --no-interaction --append

  # Make sure Webdriver is running
  - curl http://localhost:4444/wd/hub/status

script:
  - php vendor/bin/codecept run acceptance --env firefox
  - php vendor/bin/codecept run unit --coverage-xml
  
after_success:
  - travis_retry php vendor/bin/coveralls -v
