<?php
// Init Form
$form = $this->form;
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('action', $this->url('application', array('controller' => 'file', 'action' => 'form')));
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?>

<div class="modal-body">
    <?php
    //
    // Progress id hidden field.
    // *NOTE* The hidden element MUST be before the file elements.
    //
    echo $this->formFileSessionProgress();
    ?>

    
    
    <?php
    
    echo $this->controlGroup($this->form->get('reference'));
    
    echo $this->controlGroup($this->form->get('name'));
    
    echo $this->controlGroup($this->form->get('file'), array('group_id' => 'file-controls'));
    ?>


    <div id="output"></div>

</div>

<div class="modal-footer">
    <div id="action-buttons" class="control-group">
        <div class="controls">
            <button class="btn btn-primary">Envoyer</button>
            <button id="cancel-form-upload" class="btn" href="#" data-dismiss="modal" aria-hidden="true">Annuler</button>
        </div>
    </div>
    
</div>
    
    
<?php echo $this->form()->closeTag($form); ?>
