<tr>
    <td>
    <?=$fp->getAircraftid()?>
    </td>
    <td>
        <svg class = "imgFp" xmlns="http://www.w3.org/2000/svg" version="1.1" width="500" height="70">
            <title>Plan simplifié de <?=$fp->getAircraftid()?></title>
            <desc></desc>

            <line x1="10" y1="5" x2="500" y2="5" stroke="black" stroke-width="2"/>
            <polyline points="280,0 290,5 280,10"
                      style="fill:none;stroke:black;stroke-width:1" />
            <text x="0" y="20"><?=$fp->getStartterrain()?></text>
            <text x="460" y="20"><?=$fp->getDestinationterrain()?></text>
            <text x="420" y="40">ETA : <?=($fp->getEstimatedtimeofarrival()) ? $fp->getEstimatedtimeofarrival()->format('H:i') : null?></text>
            <text x="420" y="60">TOA : <?=($fp->getTimeofarrival()) ? $fp->getTimeofarrival()->format('H:i') : null?></text>

        </svg>
    </td>
    <td>
        <?php foreach ($typesAlerte as $type => $params) :?>
        <a title="alerfa"
           href="#fp-cont-alt"
           class="btn btn-<?=$params['btnType']?> btn-xs fp-a-alt"
           data-fp-id="<?=$fp->getId()?>"
           data-fp-alt-type="<?=$type?>"
           data-fp-aircraft-id="<?=$fp->getAircraftid()?>"
           data-toggle="modal">
            <span><?=$type?></span>
        </a>
        <?php endforeach;?>
    </td>
<td>
    <a title="Modifier" 
       href="#fp-cont-form" 
       class="fp-a-edit" 
       data-fp-id="<?=$fp->getId()?>"
       data-fp-aircraft-id="<?=$fp->getAircraftid()?>"
       data-toggle="modal">
       <span class="glyphicon glyphicon-pencil"></span>
    </a>
    <a  title="Supprimer"
        href="#fp-cont-del"
        class="fp-a-del"
        data-fp-id="<?=$fp->getId()?>"
        data-fp-aircraft-id="<?=$fp->getAircraftid()?>"
        data-toggle="modal">
        <span class="glyphicon glyphicon-trash"></span>
    </a>
</td>
</tr>