<?php $this->headScript()->appendFile($this->basePath() . '/assets/js/radar.js')?>

<div class="container-fluid">
	<p></p>
	<div class="row">
		<div class="col-sm-4 col-sm-offset-4">
			<table class="table table-striped table-hover table-bordered sortable" id="radars">
				<thead>
					<tr>
						<th data-sort="string" data-autosort="true">Nom</th>
						<th>État</th>
					</tr>
				</thead>
				<tbody>
				<?php 
				foreach ($this->radars as $radarid => $radar){
					echo '<tr>';
					echo '<td>'.$radar['name'].'</td>';
					echo '<td>';
					
					echo	'<div class="togglebutton">';
					    echo '<label>';
						echo '<input
	                            id="switch_'.$radarid.'" 
								data-radarid="'.$radarid.'"
								data-radar="'.$radar['name'].'" 
								data-href="'.$this->url('application', 
													array('controller'=>'radars', 'action' => 'switchradar'), 
													array('query' => array('radarid' => $radarid))).'" 
	                            class="radar-switch" type="checkbox" '.($radar['status'] ? 'checked="checked"' : '').
								($this->isGranted('events.write') ? '' : ' disabled="disabled"').
								'>';
						echo '</label>';
					echo '</div>';

					echo '</td>';
					echo '</tr>';
				}
				?>
				</tbody>
			</table>
		</div>
	</div>
</div>

<?php 

$this->form->setAttribute('class', 'form-horizontal');
$this->form->prepare();

$form = $this->form()->openTag($this->form);

$form .= '<div class="modal-body">';
$form .= '<div id="message"></div>';
foreach ($this->form->get('custom_fields')->getElements() as $element) {
    $form .= $this->controlGroup($element);
}
$form .= '</div>';
$form .= '<div class="modal-footer">';
$form .= '<button class="btn btn-danger" id="end-radar-href" type="submit">Confirmer</button>';
$form .= "<button class=\"btn\" href=\"#\" id=\"cancel-radar\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</button>";

$form .= '</div>';
$form .= $this->form()->closeTag();


echo $this->modalwindow("confirm-end-event", 
						"<h3>Radar <em><span id=\"radar_name\"></span></em></h3>",
						"",
						null,
						$form);
?>
<?php $this->inlineScript()->captureStart();?>

$("#home").removeClass("dropdown-toggle")
		  .attr('data-toggle', '')
		  .html('<span class="glyphicon glyphicon-home"></span> Évènements');

$("#create-link").remove();		  

$("#zoomform").remove();

$('#search').remove();
	
radar('<?php echo $this->url('application'); ?>');
		  
<?php $this->inlineScript()->captureEnd();?>
