<?php $this->headScript()->appendFile($this->basePath() . '/js/stupidtable.min.js')?>
<?php $this->headScript()->appendFile($this->basePath() . '/assets/js/radar.js')?>

<div class="container-fluid">
	<p></p>
	<div class="row-fluid">
		<div class="span4 offset4">
			<table class="table table-striped table-bordered sortable">
				<thead>
					<tr>
						<th data-sort="string">Nom</th>
						<th>État</th>
					</tr>
				</thead>
				<tbody>
				<?php 
				foreach ($this->radars as $radarid => $radar){
					echo '<tr>';
					echo '<td>'.$radar['name'].'</td>';
					echo '<td>';
					
					echo	'<div id="switch_'.$radarid.'" 
								data-radarid="'.$radarid.'"
								data-radar="'.$radar['name'].'" 
								data-href="'.$this->url('application', 
													array('controller'=>'radars', 'action' => 'switchradar'), 
													array('query' => array('radarid' => $radarid))).'" 
								class="radar-switch make-switch switch-small" 
								data-off="danger" 
								data-on="success" 
								data-on-label="OPE" 
								data-off-label="HS" 
								data-text-label="État">';
						echo '<input type="checkbox" '.($radar['status'] ? 'checked="checked"' : '').
								($this->isGranted('events.write') ? '' : ' disabled="disabled"').
								'>';
					echo '</div>';

					echo '</td>';
					echo '</tr>';
				}
				?>
				</tbody>
			</table>
		</div>
	</div>
</div>

<?php echo $this->modalwindow("confirm-end-event", 
						"<h3>Radar <em><span id=\"radar_name\"></span></em></h3>",
						"",
						null,
						"<p>Voulez-vous vraiment terminer l'évènement radar en cours ?</p>
						<p>L'heure actuelle sera utilisée comme heure de fin.</p>",
						"<a class=\"btn btn-danger\" id=\"end-radar-href\">Confirmer</a>
						<a class=\"btn\" href=\"#\" id=\"cancel-radar\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</a>");
?>
<?php $this->inlineScript()->captureStart();?>

$("#home").removeClass("dropdown-toggle")
		  .attr('data-toggle', '')
		  .html('<i class="icon-home"></i> Évènements');

$("#create-link").remove();		  

$("#zoom").remove();

$('#search').remove();

$(".sortable").stupidtable();

$(".sortable").bind('aftertablesort', function(event, data){
	var th = $(this).find("th");
    th.find(".arrow").remove();
    var arrow = data.direction === "asc" ? "<i class=\"icon-arrow-down\"></i>" : "<i class=\"icon-arrow-up\"></i>";
    th.eq(data.column).append('<span class="arrow"> ' + arrow +'</span>');
});

//sort the table by name
$("table th:first").trigger('click');
	
radar('<?php echo $this->url('application'); ?>');
		  
<?php $this->inlineScript()->captureEnd();?>
