<?php $this->headScript()->appendFile($this->basePath() . '/js/stupidtable.min.js')?>

<div class="container-fluid">
	<div class="row-fluid">
		<div class="span8 offset2">
			<table class="table table-striped table-bordered sortable">
				<thead>
					<tr>
					<th data-sort="string">Nom</th>
					<th>État</th>
					</tr>
				</thead>
				<tbody>
				<?php 
				foreach ($this->radars as $radar){
					echo '<tr>';
					echo '<td>'.$radar['name'].'</td>';
					echo '<td>';
					if(!$radar['status']) {
						echo '<span class="label label-important">Indisponible</span>';
					} else {
						echo '<span class="label label-success">Opérationnel</span>';
					}
					echo '</td>';
					echo '</tr>';
				}
				?>
				</tbody>
			</table>
		</div>
	</div>
</div>

<?php $this->inlineScript()->captureStart();?>

$("#home").removeClass("dropdown-toggle")
		  .attr('data-toggle', '')
		  .html('<i class="icon-home"></i> Évènements');
		  
$(".sortable").stupidtable();

$(".sortable").bind('aftertablesort', function(event, data){
	var th = $(this).find("th");
    th.find(".arrow").remove();
    var arrow = data.direction === "asc" ? "<i class=\"icon-arrow-down\"></i>" : "<i class=\"icon-arrow-up\"></i>";
    th.eq(data.column).append('<span class="arrow"> ' + arrow +'</span>');
});
		  
<?php $this->inlineScript()->captureEnd();?>
