<?php $this->headScript()->appendFile($this->basePath() . '/assets/js/jquery.ui.timeline.js');
$this->headScript()->appendFile($this->basePath() . '/components/jquery-form/jquery.form.js');
$this->headScript()->appendFile($this->basePath() . '/assets/js/fileupload.js');
$this->headScript()->appendFile($this->basePath() . '/assets/js/search.js');
$this->headScript()->appendFile($this->basePath() . '/assets/js/postit.js');
$this->headLink()->prependStylesheet($this->basePath() . '/assets/css/form.css');
$this->headLink()->prependStylesheet($this->basePath() . '/assets/css/fullcalendar.material.css');
$this->headLink()->prependStylesheet($this->basePath() . '/assets/css/postit.css');
$this->headLink()->prependStylesheet($this->basePath() . '/components/fullcalendar/dist/fullcalendar.min.css');

?>

<?php if($this->isGranted('events.create') || $this->isGranted('events.write')):?>
    <div id="create-evt" data-toggle="modal" data-backdrop="static" class="modal fade in" data-spy="affix" data-offset-top="80">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="loading"></div>
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="form-title">Nouvel évènement</h4>
                </div>
                <div id="event">
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>

<div id="search-results" class="popover fade bottom in">
        <div class="arrow"></div>
        <div class="loading"></div>
        <div id="results">
                <div>Chargement...</div>
        </div>
</div>

<input type="checkbox" class="main-nav-check" id="main-nav-check" autocomplete="off"/>

<?php if($this->panel == true) :?>
<div id="fiche" class="panel-left panel-fixed" data-url="/events/getfiche">
</div>

<div class="page-wrap">
<?php endif; ?>

<div id="timeline">
    <div class="loading"></div>
    <div id="calendar">
        <p><a href="#" id="day-backward"><span class="glyphicon glyphicon-backward"></span></a> <input id="date" type="text" class="date input-sm"></input> <a href="#" id="day-forward"><span class="glyphicon glyphicon-forward"></span></a> <a href="#" id="print" title="Imprimer la timeline"><span class="glyphicon glyphicon-print"></span></a> <a href="#" id="export" title="Exporter le rapport journalier"><span class="glyphicon glyphicon-export"></span></a></p>
    </div>
</div>

<div id="calendarview">
    <div class="loading" style="display: none;"></div>
</div>

<?php if($this->panel == true) :?>
</div>
<?php endif; ?>

<div class="floating-notes">
    <?php if($this->postitAllowed):?>
    <button data-toggle="modal"
            href="#add-postit-modal"
            class="btn btn-sm btn-fab btn-default btn-mdi-raised" id="add-postit-btn"><span class="glyphicon glyphicon-tag"></span></button>
    <?php endif; ?>
    <ul id="notes">
    
    </ul>
</div>

<div id="alert-bottom"></div>

<?php 
//modal windows to modify or delete file
echo $this->modalwindow("confirm-delete-file",
					"<h4>Confirmer la suppression du fichier ?</h4>",
					"",
					null,
					"<p>Voulez-vous vraiment supprimer le fichier <em><span id=\"file_name\"></span></em> ?</p>",
					"<button class=\"btn btn-danger\" id=\"delete-file-href\">Confirmer</button>
					<button class=\"btn\" href=\"#\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</button>");
?>

<?php

echo $this->modalwindow(
    "add-file",
    "<h4>Ajout d'un fichier</h4>",
    "",
    "<div id=\"file-upload-form\"></div>"
    );

echo $this->modalwindow("add-alarm",
	"<h3 id=\"alarm-title\">Ajout d'un mémo</h3>",
	"",
	"<div id=\"alarm-form\"></div>");
    
echo $this->modalwindow('add-note-modal',
        "<h4>Ajout d'une note</h4>",
        "",
        "<form id=\"add-note\" class=\"form-horizontal\" action=\"<?php echo $this->url('application', array('controller' => 'events', 'action' => 'addnote'))?>\">"
        . "<div class=\"modal-body\">"
            . "<div class=\"form-group\">"
                . "<label class=\"control-label col-sm-2\">Contenu : </label>"
                . "<div class=\"col-sm-10\">"
                    . "<textarea class=\"form-control\" name=\"new-update\" placeholder=\"Ajouter une note.\"></textarea>"
                . "</div>"
            . "</div>"
        . "</div>"
        . "<div class=\"modal-footer\">"
            . "<input type=\"submit\" class=\"btn btn-sm btn-primary\" value=\"Ajouter la note\"></input>"
        . "</div>"
        . "</form>");

echo $this->modalwindow('add-postit-modal',
    "<h4>Ajout d'un postit</h4>",
    "",
    "<form id=\"add-postit\" class=\"form-horizontal\" action=\"<?php echo $this->url('application', array('controller' => 'events', 'action' => 'addpostit'))?>\">"
    . "<div class=\"modal-body\">"
    . "<div class=\"form-group\">"
    . "<label class=\"control-label col-sm-2\">Titre : </label>"
    . "<div class=\"col-sm-10\">"
    . "<input type='text' class=\"form-control\" name=\"name\" placeholder=\"Titre.\"></input>"
    . "</div>"
    . "</div>"
    . "<div class=\"form-group\">"
    . "<label class=\"control-label col-sm-2\">Contenu : </label>"
    . "<div class=\"col-sm-10\">"
    . "<textarea class=\"form-control\" name=\"content\" placeholder=\"Contenu.\"></textarea>"
    . "</div>"
    . "</div>"
    . "</div>"
    . "<div class=\"modal-footer\">"
    . "<input type=\"submit\" class=\"btn btn-sm btn-primary\" value=\"Enregistrer\"></input>"
    . "</div>"
    . "</form>");

echo $this->partial('events/recurrence-form.html');

if($this->isGranted('events.recurrent')) {
    echo $this->modalwindow('confirm-recurr',
        '<h4 class="modal-title">Modifier tous les évènements ?</h4>',
        "",
        null,
        "<p>Cet évènement fait partie d'une série d'évènements récurrents.</p>"
        . "<p>Voulez-vous modifier toute la série ou seulement cet évènement ?</p>"
        . "<p>Si vous modifiez toute la série :"
        . "<ul><li>les évènements passés seront exclus de la série ;</li>"
        . "<li>le changement d'heure de fin concernera uniquement l'évènement choisi.</li></ul></p>"
        . "<p>Modifier uniquement cet évènement l'exclura de la série.</p>",
        "<button class=\"btn btn-danger\" id=\"confirm-modify-series\">Toute la série</button>
     <button class=\"btn btn-primary\" id=\"confirm-modify-one\">Seulement cet évènement</button>
	 <button class=\"btn\" href=\"#\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</button>");
} else {
    echo $this->modalwindow('confirm-recurr',
        '<h4 class="modal-title">Modifier l\'évènement ?</h4>',
        "",
        null,
        "<p>Cet évènement fait partie d'une série d'évènements récurrents.</p>"
        . "<p>Le modifier le supprimera de la récurrence et le rendra indépendant.</p>",
        "<button class=\"btn btn-primary\" id=\"confirm-modify-one\">Modifier cet évènement</button>
	 <button class=\"btn\" href=\"#\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</button>");
}

?>

<?php $this->inlineScript()->captureStart();?>
<?php

if($this->cats) {
    $catsString = "";
    $i = 0;
    foreach ($this->cats as $cat) {
        if(strlen($catsString) > 0) {
            $catsString .= "&";
        }
        $catsString .= 'cats[' . $i . ']=' . $cat;
        $i++;
    }
    echo 'cats = "'.$catsString.'";';
} else {
    echo 'cats = null;';
}

//used in application.js to determine fullcalendar view
if($this->onlyroot) {
    echo 'var onlyroot = 1;';
} else {
    echo 'var onlyroot = 0;';
}
if($this->default) {
  echo 'var defaultTimeline = 1;';
} else {
  echo 'var defaultTimeline = 0;';
}
?>

$('#timeline').timeline({
    controllerUrl: '<?php echo $this->url('application', array('controller' => 'events', '')) ?>',
    eventUrl: '<?php echo $this->url('application', array('controller' => 'events', 'action' => 'getevents'),
    												array('query' => array('cats' => $this->cats,
                                'default' => ($this->default ? true : false))))?>',
    categoriesUrl: '<?php echo $this->url('application', 
    										array('controller' => 'events', 'action' => 'getcategories'), 
    												array('query' => array('rootonly' => ($this->onlyroot ? true : false),
    																		'cats' => $this->cats))) ?>',
    topOffset: <?php echo ($this->isGranted('ihm.light') ? 50 : 100)  ?>,
    leftOffset: 120,
    rightOffset: 85,
    tabCats: cats,
    showOnlyRootCategories: '<?php  echo ($this->onlyroot ? true : false) ?>',
    view: Cookies.get("timelineview"),
    day: Cookies.get("timelineday"),
    initComplete: function(){
        $("#timeline .loading").hide();
<?php if($this->isGranted('chat.access') && $this->viewModel()->getRoot()->mattermost) {
        echo '$(".chat-container") . mattermost("initialize");';
}
?>
    }<?php if($this->isGranted('chat.access') && $this->viewModel()->getRoot()->mattermost){echo ',';
      echo 'mattermost: true';
    }
    ?>
});

//init form
form('<?php echo $this->url('application');?>', '<?php echo $this->basePath() ?>', cats, <?php echo (int) $this->sunrise ?>, '<?php echo $this->url('application', array('controller' => "sunrisesunset")) ?>');

fileupload('<?php echo $this->url('application')?>');

//search
search('<?php echo $this->url('application', array('controller'=>'events'));?>');

postit('<?php echo $this->url('application');?>');

let initializeMattermost = false;

<?php echo $this->notifications($this->messages); ?>

<?php $this->inlineScript()->captureEnd();?>