<?php $this->headScript()->appendFile($this->basePath() . '/assets/js/jquery.ui.timeline.js');
$this->headScript()->appendFile($this->basePath() . '/components/jquery-form/jquery.form.js');
$this->headScript()->appendFile($this->basePath() . '/assets/js/fileupload.js');
$this->headScript()->appendFile($this->basePath() . '/assets/js/search.js');
$this->headLink()->prependStylesheet($this->basePath() . '/assets/css/form.css');
$this->headLink()->prependStylesheet($this->basePath() . '/assets/css/fullcalendar.material.css');
$this->headLink()->prependStylesheet($this->basePath() . '/components/fullcalendar/dist/fullcalendar.min.css');

?>

<?php if($this->isGranted('events.create') || $this->isGranted('events.write')):?>
    <div id="create-evt" data-toggle="modal" class="modal fade in" data-spy="affix" data-offset-top="80">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="loading"></div>
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="form-title">Nouvel évènement</h4>
                </div>
                <div id="event">
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>

<div id="search-results" class="popover fade bottom in">
        <div class="arrow"></div>
        <div class="loading"></div>
        <div id="results">
                <div>Chargement...</div>
        </div>
</div>

<input type="checkbox" class="main-nav-check" id="main-nav-check" />

<div id="fiche" class="panel-left panel-fixed" data-url="events/getfiche">
</div>

<div class="page-wrap">

<div id="timeline">
    <div class="loading"></div>
    <div id="calendar">
        <p><a href="#" id="day-backward"><span class="glyphicon glyphicon-backward"></span></a> <input id="date" type="text" class="date input-small"></input> <a href="#" id="day-forward"><span class="glyphicon glyphicon-forward"></span></a> <a href="#" id="export"><span class="glyphicon glyphicon-print"></span></a></p>
    </div>
</div>

<div id="calendarview">
    <div class="loading" style="display: none;"></div>
</div>
</div>

<?php 
//modal windows to modify or delete file
echo $this->modalwindow("confirm-delete-file",
					"<h4>Confirmer la suppression du fichier ?</h4>",
					"",
					null,
					"<p>Voulez-vous vraiment supprimer le fichier <em><span id=\"file_name\"></span></em> ?</p>",
					"<button class=\"btn btn-danger\" id=\"delete-file-href\">Confirmer</button>
					<button class=\"btn\" href=\"#\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</button>");
?>

<?php

echo $this->modalwindow(
    "add-file",
    "<h4>Ajout d'un fichier</h4>",
    "",
    "<div id=\"file-upload-form\"></div>"
    );

echo $this->modalwindow("add-alarm",
	"<h3 id=\"alarm-title\">Ajout d'un mémo</h3>",
	"",
	"<div id=\"alarm-form\"></div>");
    
echo $this->modalwindow('add-note-modal',
        "<h4>Ajout d'une note</h4>",
        "",
        "<form id=\"add-note\" class=\"form-horizontal\" action=\"<?php echo $this->url('application', array('controller' => 'events', 'action' => 'addnote'))?>\">"
        . "<div class=\"modal-body\">"
            . "<div class=\"control-group\">"
                . "<label class=\"control-label\">Contenu : </label>"
                . "<div class=\"controls\"><textarea name=\"new-update\" placeholder=\"Ajouter une note.\"></textarea></div>"
            . "</div>"
        . "</div>"
        . "<div class=\"modal-footer\">"
            . "<div class=\"control-group\">"
                . "<div class=\"controls\">"
                    . "<div style=\"display:inline-block; position:relative;\">"
                        . "<input type=\"submit\" class=\"btn btn-sm btn-primary pull-right\" value=\"Ajouter la note\"></input>"
                    . "</div>"
                . "</div>"
            . "</div>"
        . "</div>"
        . "</form>");
?>

<?php $this->inlineScript()->captureStart();?>

$("#home").removeClass("dropdown-toggle")
		  .attr('data-toggle', '')
		  .html('<span class="glyphicon glyphicon-home"></span> Évènements');

<?php
if($this->view == "30") {
    echo 'forceMonth = true;';
    if($this->cats) {
        $catsString = "";
        $i = 0;
        foreach ($this->cats as $cat) {
            if(strlen($catsString) > 0) {
                $catsString .= "&";
            }
            $catsString .= 'cats[' . $i . ']=' . $cat;
            $i++;
        }
        echo 'cats = "'.$catsString.'";';
    } else {
        echo 'cats = null;';
    }
}
?>

$('#timeline').timeline({
    controllerUrl: '<?php echo $this->url('application', array('controller' => 'events', '')) ?>',
    eventUrl: '<?php echo $this->url('application', array('controller' => 'events', 'action' => 'getevents'),
    												array('query' => array('cats' => $this->cats)))?>',
    categoriesUrl: '<?php echo $this->url('application', 
    										array('controller' => 'events', 'action' => 'getcategories'), 
    												array('query' => array('rootonly' => ($this->onlyroot ? true : false),
    																		'cats' => $this->cats,
    																		'timeline' => false))) ?>',
    topOffset: 100,
    leftOffset: 120,
    rightOffset: 85,
    showOnlyRootCategories: '<?php  echo ($this->onlyroot ? true : false) ?>',
    initComplete: function(){
        $("#timeline .loading").hide();
        <?php
        if($this->view == "24") {
            echo '$("#viewday").trigger("click");';
            if($this->day !== null) {
                echo '$("#calendar input[type=text].date").val('.$this->day.');';
                echo '$("#calendar input[type=text].date").trigger("change");';
            }
        }
        ?>
    }
});
//init form
form('<?php echo $this->url('application');?>', '<?php echo $this->tabid; ?>');

fileupload('<?php echo $this->url('application')?>');

//search
search('<?php echo $this->url('application', array('controller'=>'events'));?>');

<?php echo $this->notifications($this->messages); ?>

<?php $this->inlineScript()->captureEnd();?>