<p></p>
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-offset-1 col-sm-10">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title">Statuts</h4>
				</div>
				<div class="panel-body">
					<table class="table table-striped">
						<thead>
							<tr>
								<th>Id</th>
								<th>Nom</th>
								<th>Ouvert</th>
								<th>Affiché</th>
								<th>Default</th>
							</tr>
						</thead>
						<tbody>
							<?php 
							foreach ($this->status as $statut){
								echo '<tr>';
									echo '<td>'.$statut->getId().'</td>';
									echo '<td>'.$statut->getName().'</td>';
									echo '<td>'.($statut->isOpen() ? '<span class="glyphicon glyphicon-ok"></span>':'<span class="glyphicon glyphicon-remove"></span>').'</td>';
									echo '<td>'.($statut->isDisplay() ? '<span class="glyphicon glyphicon-ok"></span>':'<span class="glyphicon glyphicon-remove"></span>').'</td>';
									echo '<td>'.($statut->isDefault() ? '<span class="glyphicon glyphicon-ok"></span>':'<span class="glyphicon glyphicon-remove"></span>').'</td>';
								echo '</tr>';
							}							
							?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		
		<div class="col-sm-offset-1 col-sm-10">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title">Champs types disponibles</h4>
				</div>
				<div class="panel-body">
					<table class="table table-striped">
						<thead>
							<tr>
								<th>Id</th>
								<th>Nom</th>
								<th>Type</th>
							</tr>
						</thead>
						<tbody>
							<?php 
							foreach ($this->fields as $field){
								echo '<tr>';
									echo '<td>'.$field->getId().'</td>';
									echo '<td>'.$field->getName().'</td>';
									echo '<td>'.$field->getType().'</td>';
								echo '</tr>';
							}							
							?>
						</tbody>
					</table>
				</div>
			</div>
		</div>

        <div class="col-sm-offset-1 col-sm-10">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">Paramètres divers</h4>
                </div>
                <div class="panel-body">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Nom</th>
                            <th>Valeur</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        foreach ($this->params as $key => $value){
                            echo '<tr>';
                            echo '<td>'.$key.'</td>';
                            echo '<td>'.$value.'</td>';
                            echo '</tr>';
                        }
                        ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

	</div>
</div>