<p></p>
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-4">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title">Statuts</h4>
				</div>
				<div class="panel-body">
					<table class="table table-striped">
						<thead>
							<tr>
								<th>Id</th>
								<th>Nom</th>
								<th>Ouvert</th>
								<th>Affiché</th>
								<th>Default</th>
							</tr>
						</thead>
						<tbody>
							<?php 
							foreach ($this->status as $statut){
								echo '<tr>';
									echo '<td>'.$statut->getId().'</td>';
									echo '<td>'.$statut->getName().'</td>';
									echo '<td>'.($statut->isOpen() ? '<span class="glyphicon glyphicon-ok"></span>':'<span class="glyphicon glyphicon-remove"></span>').'</td>';
									echo '<td>'.($statut->isDisplay() ? '<span class="glyphicon glyphicon-ok"></span>':'<span class="glyphicon glyphicon-remove"></span>').'</td>';
									echo '<td>'.($statut->isDefault() ? '<span class="glyphicon glyphicon-ok"></span>':'<span class="glyphicon glyphicon-remove"></span>').'</td>';
								echo '</tr>';
							}							
							?>
						</tbody>
					</table>
				</div>
			</div>
		</div>

		<div class="col-sm-4">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title">Impacts</h4>
				</div>
				<div class="panel-body">
					<table class="table table-striped">
						<thead>
							<tr>
								<th>Id</th>
								<th>Nom</th>
								<th>Valeur</th>
								<th>Style</th>
							</tr>
						</thead>
						<tbody>
							<?php 
							foreach ($this->impacts as $impact){
								echo '<tr>';
									echo '<td>'.$impact->getId().'</td>';
									echo '<td>'.$impact->getName().'</td>';
									echo '<td>'.$impact->getValue().'</td>';
									echo '<td><span class="label label-'.$impact->getStyle().'">'.$impact->getName().'</span></td>';
								echo '</tr>';
							}							
							?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		
		<div class="col-sm-4">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title">Champs types disponibles</h4>
				</div>
				<div class="panel-body">
					<table class="table table-striped">
						<thead>
							<tr>
								<th>Id</th>
								<th>Nom</th>
								<th>Type</th>
							</tr>
						</thead>
						<tbody>
							<?php 
							foreach ($this->fields as $field){
								echo '<tr>';
									echo '<td>'.$field->getId().'</td>';
									echo '<td>'.$field->getName().'</td>';
									echo '<td>'.$field->getType().'</td>';
								echo '</tr>';
							}							
							?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		
	</div>
</div>