<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');
echo $this->form()->openTag($form);
?>

<div class="modal-body">

<?php

echo $this->formElementErrors($form->get('identity'));

echo $this->controlGroup($this->formLabel($form->get('identity')->setLabelAttributes(array('class'=>'control-label'))),
						$this->formInput($form->get('identity')));
       
echo $this->controlGroup($this->formLabel($form->get('credential')->setLabelAttributes(array('class'=>'control-label'))),
				$this->formInput($form->get('credential')));

?>

        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>

</div>        
<div class="modal-footer">  
        <?php echo $this->formButton($form->get('submit')) ?>
</div>
<?php echo $this->form()->closeTag() ?>

