<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('coreuser/login') . '?redirect=' . $this->redirect);
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');
echo $this->form()->openTag($form);
?>

<div class="modal-body">

<?php

echo $this->formElementErrors($form->get('identity'));

echo $this->controlGroup($form->get('identity'));
       
echo $this->controlGroup($form->get('credential'));

?>

        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>

</div>        
<div class="modal-footer">  
        <?php echo $this->formButton($form->get('submit')->setAttribute('class', 'btn btn-primary')) ?>
</div>
<?php echo $this->form()->closeTag() ?>

