<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');
echo $this->form()->openTag($form);
?>

<div class="modal-body">

<?php

echo $this->formElementErrors($form->get('identity'));

echo $this->controlGroup($this->formLabel($form->get('identity')->setLabelAttributes(array('class'=>'control-label col-sm-2'))),
						$this->formInput($form->get('identity')->setAttribute('class', 'form-control')));
       
echo $this->controlGroup($this->formLabel($form->get('credential')->setLabelAttributes(array('class'=>'col-sm-2 control-label'))),
				$this->formInput($form->get('credential')->setAttribute('class', 'form-control')));

?>

        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>

</div>        
<div class="modal-footer">  
        <?php echo $this->formButton($form->get('submit')->setAttribute('class', 'btn btn-primary')) ?>
</div>
<?php echo $this->form()->closeTag() ?>

