<?php
    $class_alert = [
        'INCERFA' => 'info',
        'ALERFA' => 'warning',
        'DETRESFA' => 'danger'
    ];

    $typealert = (isset($ip['Alerte']['Type'])) ? $ip['Alerte']['Type'] : null;
?>
<li data-id="<?php echo $ip['id']; ?>" class="list-group-item list-group-item-<?php echo (array_key_exists($typealert, $class_alert)) ? $class_alert[$typealert] : 'primary'; ?>">
    <h1 class="list-group-item-heading"><?php echo $ip['start_date']->format('d-m-Y H:i:s') ?></h1>
    <div class = "list-ip-content <?php //echo ($i>0)?'cache':''; ?>">
        <p class="list-group-item-text">Latitude: <?php echo $ip['Latitude']?></p>
        <p class="list-group-item-text">Longitude: <?php echo $ip['Longitude']?></p>
        <p class="list-group-item-text">Type : <?php echo $ip['Type']?></p>
        <p class="list-group-item-text">Alerte : <?php echo (isset($typealert)) ? $typealert : NIL; ?></p>
        <!-- <h3 class="list-group-item-heading">Alerte</h3> -->
        <p class="list-group-item-text comment">Cause : <?php echo (isset($ip['Alerte']['Cause'])) ? $ip['Alerte']['Cause'] : null; ?></p>
        <a href="#mdl-start-ip" data-toggle="modal" class = "btn-edit-ip">
        <!-- <span class="glyphicon glyphicon-pencil"></span> -->
        Informations
        </a><br />

        <?php if (isset($ip['fields'])) : ?> 
            <h3 class="list-group-item-heading">Terrains interrogés</h3>
            <?php foreach ($ip['fields'] as $i => $f) : ?> 
                <h4 class="list-group-item-heading">#<?php echo $i++?> <?php echo $f['Nom'];?> [<?php echo $f['start_date']->format('H:i:s');?>]</h4>
                <?php if (isset($f['updates'])) : ?>
                    <?php foreach($f['updates'] as $updates) :?>
                    <p class="list-group-item-text comment"><?php echo $updates['text'];?></p>
                    <?php endforeach; ?>
                <?php endif; ?>
            <?php endforeach; ?>
        <?php endif; ?>
        
        <a href="#" class = "btn-show-ip">
        <!-- <span class="glyphicon glyphicon-pencil"></span> -->
        Plans interrogés
        </a><br />
        <a href="#" class = "btn-print-ip">
        <!-- <span class="glyphicon glyphicon-pencil"></span> -->
        Imprimer
        </a><br />
        <a href="#" class = "btn-mail-ip">
        <!-- <span class="glyphicon glyphicon-pencil"></span> -->
        Courriel
        </a><br />
        <a href="#mdl-end-ip" data-toggle="modal" class = "btn-end-ip">
        <!-- <span class="glyphicon glyphicon-pencil"></span> -->
        Clôturer
        </a>
    </div>
</li>