<?php
    $class_alert = [
        'INCERFA' => 'info',
        'ALERFA' => 'warning',
        'DETRESFA' => 'danger'
    ];

    $typealert = (isset($ip['Alerte']['Type'])) ? $ip['Alerte']['Type'] : null;
?>
<a href="#mdl-show-ip" data-toggle="modal" data-id="<?php echo $ip['id']; ?>" class="list-group-item"><?php echo $ip['Type']; ?> <?php echo $ip['start_date']->format('\à H:i:s \l\e d-m-Y'); ?>
</a>