<?php
    $class_alert = [
        'INCERFA' => 'info',
        'ALERFA' => 'warning',
        'DETRESFA' => 'danger'
    ];

    $typealert = (isset($ip['Alerte']['Type'])) ? $ip['Alerte']['Type'] : null;
    $class = $class_alert[$typealert];
?>
<a href="#mdl-show-ip" data-toggle="modal" data-id="<?php echo $ip['id']; ?>" class="list-group-item list-group-item-<?php echo $class; ?>">
    <h4><?php echo $ip['start_date']->format('d-m-y H:i:s'); ?> <?php echo $ip['Alerte']['Type']; ?></h4>
</a>