<?php
$branchname = shell_exec("git rev-parse --abbrev-ref HEAD"); // get the one that is always the branch name

$revision = shell_exec("git log -n 1 --pretty=format:'%h' --abbrev-commit");

$commit = shell_exec("git log -n 1 --pretty=format:'%s (%ci)' --abbrev-commit");

$tag = shell_exec("git describe --exact-match --tags");

$hostname = getenv('COMPUTERNAME') ? getenv('COMPUTERNAME') : shell_exec('uname -n');

$hasTag = ! (substr($tag, 0, strlen("fatal")) === "fatal" || substr($tag, 0, strlen("warning")) === "warning" || empty($tag));
?>
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12">
			<p></p>
    		<div class="panel panel-default">
    			<div class="panel-heading">
    				<h3 class="panel-title">Serveur</h3>
    			</div>
    
    			<div class="panel-body">
    				<p>
    					Nom d'hôte : <em><?php echo $hostname; ?></em>
    				</p>
    			</div>
    		</div>
    
    		<div class="panel panel-default">
    			<div class="panel-heading">
    				<h3 class="panel-title">Version</h3>
    			</div>
    
    			<div class="panel-body">
    				<p>
    					Branche : <em><?php echo $branchname; ?></em>
    				</p>
    				<?php if($hasTag) { echo '<p> Tag : <em>'.$tag.'</em></p>'; }?>
    				<p>
    					Révision : <em><?php echo $revision." : ".$commit; ?></em>
    				</p>
    			</div>
    		</div>
    
       		<div class="panel panel-default">
    			<div class="panel-heading">
    				<h4 class="panel-title">Base de données</h4>
    			</div>
    			<div class="panel-body">
                    <?php if($this->migrations != '0') : ?>
                    <div class="alert alert-danger">
    					<strong>Attention !</strong> La base de données n'est pas à jour !
    				</div>
                    <?php endif; ?>
            <table class="table table-striped table-bordered">
              <tr>
                <td>Base de données</td>
                <td><em><?php echo $this->db;?></em></td>
              </tr>
              <tr>
                <td>Table des migrations</td>
                <td><em><?php echo $this->table; ?></em></td>
              </tr>
              <tr>
                <td>Version courante</td>
                <td><em><?php echo $this->version; ?></em></td>
              </tr>
              <tr>
                <td>Dernière version </td>
                <td><em><?php echo $this->latestversion; ?></em></td>
              </tr>
              <tr>
                <td>Migrations non exécutées</td>
                <td><em><?php echo $this->migrations; ?></em></td>
              </tr>
            </table>
    			</div>
    		</div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">Extensions PHP</h4>
        </div>
        <div class="panel-body">
            <?php
            $ok = true;
            foreach ($this->extensions as $key => $value) {
              $ok *= $value;
            }
            if(!$ok) {
              echo '<div class="alert alert-danger">'
                    .'<strong>Attention !</strong> Une ou plusieures extensions PHP ne sont pas activées !'
                    .'</div>';
            }
            ?>
          <table class="table table-striped table-bordered">
            <tr>
              <td>Extension GD</td>
              <td><?php if($this->extensions['gd']) {
                      echo '<span class="label label-success">Activée</span>';
                  } else {
                      echo '<span class="label label-danger">Absente</span>';
                  } ?></td>
            </tr>
            <tr>
              <td>Extension Iconv</td>
              <td><?php if($this->extensions['iconv']) {
                      echo '<span class="label label-success">Activée</span>';
                  } else {
                      echo '<span class="label label-danger">Absente</span>';
                  } ?></td>
            </tr>
            <tr>
              <td>Extension Intl</td>
              <td><?php if($this->extensions['intl']) {
                      echo '<span class="label label-success">Activée</span>';
                  } else {
                      echo '<span class="label label-danger">Absente</span>';
                  } ?></td>
            </tr>
            <tr>
              <td>Extension Soap</td>
              <td><?php if($this->extensions['soap']) {
                      echo '<span class="label label-success">Activée</span>';
                  } else {
                      echo '<span class="label label-danger">Absente</span>';
                  } ?></td>
            </tr>
            <tr>
              <td>Extension OpenSSL</td>
              <td><?php if($this->extensions['openssl']) {
                      echo '<span class="label label-success">Activée</span>';
                  } else {
                      echo '<span class="label label-danger">Absente</span>';
                  } ?></td>
            </tr>
            <?php if($this->phpversionid > 70200) :?>
              <tr>
                  <td>Extension Mcrypt <?php echo $this->phpversionid ?></td>
                  <td><?php if($this->extensions['mcrypt']) {
                          echo '<span class="label label-success">Activée</span>';
                      } else {
                          echo '<span class="label label-danger">Absente</span>';
                      } ?></td>
              </tr>
            <?php endif; ?>
          </table>
        </div>
      </div>

		</div>
	</div>
</div>
