<?php 

    $stringfromfile = file('.git/HEAD', FILE_USE_INCLUDE_PATH);

    $stringfromfile = $stringfromfile[0]; //get the string from the array

    $explodedstring = explode("/", $stringfromfile); //seperate out by the "/" in the string
    
    $branchname = $explodedstring[2]; //get the one that is always the branch name

    $stringfromfile = file('.git/FETCH_HEAD', FILE_USE_INCLUDE_PATH);

    $stringfromfile = $stringfromfile[0]; //get the string from the array
    
    $explodedstring = explode("\t", $stringfromfile);
       
    $revision = $explodedstring[0];
?>
<div class="container-fluid">
	<div class="row-fluid">
            	<div class="span12">
			<div class="block">
				<div class="navbar navbar-inner block-header">
					<div class="muted pull-left">Version</div>
				</div>
				<div class="block-content collapse in">
					<div class="span12">
                                            <p> Branche : <em><?php echo $branchname; ?></em></p>
                                            <p> Revision : <em><?php echo $revision; ?></em></p>
					</div>
				</div>
			</div>
		</div>
        </div>
        <div class="row-fluid">
            	<div class="span12">
			<div class="block">
				<div class="navbar navbar-inner block-header">
					<div class="muted pull-left">Base de données</div>
				</div>
				<div class="block-content collapse in">
					<div class="span12">
                                            <?php if($this->migrations != '0') : ?>
                                            <div class="alert alert-error">
                                                <strong>Attention !</strong> La base de données n'est pas à jour !
                                            </div>
                                            <?php endif; ?>
                                            <p> Base de données : <em><?php echo $this->db;?></em></p>
                                            <p> Table des migrations : <em><?php echo $this->table; ?></em></p>
                                            <p> Version courante : <em><?php echo $this->version; ?></em></p>
                                            <p> Dernière version : <em><?php echo $this->latestversion; ?></em></p>
                                            <p> Migrations non exécutées : <em><?php echo $this->migrations; ?></em></p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>