<?php $this->headScript()->appendFile($this->basePath() . '/components/jquery-stupid-table/stupidtable.min.js')?>
<?php $this->headScript()->appendFile($this->basePath() . '/assets/js/radio.js')?>


<div class="container-fluid">
	<div class="row">
	<div class="col-md-3" id="sidebar">
		<ul class="nav sidenav">
			<li><a href="#groups">1. Regroupements</a></li>
			<li><a href="#reflex">2. Fiches reflexes</a></li>
		</ul>	
	</div>
	<div class="col-md-9">
		<p></p>
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title" id="groups">Regroupements affichés </h4>
			</div>
			<div class="panel-body">
				<table class="table table-striped sortable">
					<thead>
						<tr>
							<th data-sort="string">Id<span class="arrow"> <span class="glyphicon glyphicon-arrow-down"></span></span></th>
							<th data-sort="string">Organisation</th>
							<th data-sort="string">Zone</th>
							<th data-sort="string">Nom</th>
							<th>Affiché</th>
							<th>Position</th>
						</tr>
					</thead>
					<tbody>
						<?php 
						$i = 0;
						$total = count($this->sectorsgroups);
						foreach ($this->sectorsgroups as $sectorsgroup){
							$i++;
							echo '<tr>';
								echo '<td>'.$sectorsgroup->getId().'</td>';
								echo '<td>'.$sectorsgroup->getZone()->getOrganisation()->getName().'</td>';
								echo '<td>'.$sectorsgroup->getZone()->getName().'</td>';
								echo '<td>'.$sectorsgroup->getName().'</td>';
								echo '<td>';
								
								echo '<div class="togglebutton"><label>';
								echo '<input type="checkbox"
		                                    class="switch_display" 
							                id="switch_'.$sectorsgroup->getId().'"
							                data-sectorgroupid="'.$sectorsgroup->getId().'"
											data-href="'.$this->url('administration',
																		array('controller'=>'radio', 'action' => 'switchdisplay'),
																		array('query' => array('id' => $sectorsgroup->getId()))).'"
											'.($sectorsgroup->isDisplay() ? 'checked="checked"' : '').'>';
								echo '</label></div>';
								
								echo '</td>';
								echo "<td>";
								echo '<a
										href="'.$this->url('administration', array('controller'=>'radio', 'action'=>'groupdown'), array('query'=>array('id'=>$sectorsgroup->getId()))).'"'.
										'class="groupdown'.($i == $total ? ' disabled':'').'">
									<span class="caret middle"></span></a>
									<a
										href="'.$this->url('administration', array('controller'=>'radio', 'action'=>'groupup'), array('query'=>array('id'=>$sectorsgroup->getId()))).'"'.
										'class="groupup'.($i == 1 ? ' disabled' : '').'">  <span class="up-caret middle"></span></a>';
								echo "</td>";
							echo '</tr>';
							}							
							?>
						</tbody>
					</table>
			</div>
		</div>

		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title" id="reflex">Fiches réflexes des antennes </h4>
			</div>
			<div class="panel-body">
				<table class="table table-striped sortable">
					<thead>
						<tr>
							<th data-sort="string">Antenne</th>
							<th>Fiche réflexe</th>
                            <th></th>
						</tr>
					</thead>
					<tbody>
						<?php 
						foreach ($this->antennas as $antenna){
							echo '<tr>';
								echo '<td data-id="'.$antenna->getId().'">'.$antenna->getName().'</td>';
								echo '<td>'.($antenna->getModel() ? $antenna->getModel()->getName() : 'Aucun modèle associé.').'</td>';
                                echo '<td><a href="#model-container" '
                                . 'data-toggle="modal" '
                                . 'data-name="'.$antenna->getName().'" '
                                . 'data-id="'.$antenna->getId().'" '
                                . 'class="change-model"><span class="glyphicon glyphicon-pencil"></span></a></td>';
                            echo '</tr>';
						}							
						?>
						</tbody>
					</table>
    			</div>
    		</div>
    	</div>
	</div>
</div>

			
<?php echo $this->modalwindow("model-container", "<h4 id=\"model-title\"></h4>", "", "<div id=\"model-form\"></div>") ?>


<?php $this->inlineScript()->captureStart();?>

$('.sidenav').affix();

$('body').scrollspy({target:'#sidebar', offset:120});

$(".sortable").stupidtable();

$(".sortable").bind('aftertablesort', function(event, data){
	var th = $(this).find("th");
    th.find(".arrow").remove();
    var arrow = data.direction === "asc" ? "<span class=\"glyphicon glyphicon-arrow-down\"></span>" : "<span class=\"glyphicon glyphicon-arrow-up\"></span>";
    th.eq(data.column).append('<span class="arrow"> ' + arrow +'</span>');
});

$("table th:eq(1)").trigger('click');

radio('<?php echo $this->url('administration'); ?>');

<?php echo $this->notifications($this->messages); ?>
                                        
<?php $this->inlineScript()->captureEnd();?>