<?php $this->headScript()->appendFile($this->basePath() . '/js/stupidtable.min.js')?>
<?php $this->headScript()->appendFile($this->basePath() . '/assets/js/radio.js')?>


<div class="container-fluid">
	<div class="span12">
		<div class="block">
			<div class="navbar navbar-inner block-header">
				<div class="muted pull-left">Regroupements affichés </div>
			</div>
			<div class="block-content collapse in">
				<div class="span12">
				<table class="table table-striped sortable">
					<thead>
						<tr>
							<th data-sort="string">Id<span class="arrow"> <i class="icon-arrow-down"></i></span></th>
							<th data-sort="string">Organisation</th>
							<th data-sort="string">Zone</th>
							<th data-sort="string">Nom</th>
							<th>Affiché</th>
							<th>Position</th>
						</tr>
					</thead>
					<tbody>
						<?php 
						$i = 0;
						$total = count($this->sectorsgroups);
						foreach ($this->sectorsgroups as $sectorsgroup){
							$i++;
							echo '<tr>';
								echo '<td>'.$sectorsgroup->getId().'</td>';
								echo '<td>'.$sectorsgroup->getZone()->getOrganisation()->getName().'</td>';
								echo '<td>'.$sectorsgroup->getZone()->getName().'</td>';
								echo '<td>'.$sectorsgroup->getName().'</td>';
								echo '<td>';
								
								echo '<div id="switch_'.$sectorsgroup->getId().'"
											data-sectorgroupid="'.$sectorsgroup->getId().'"
											data-href="'.$this->url('administration',
																		array('controller'=>'radio', 'action' => 'switchdisplay'),
																		array('query' => array('id' => $sectorsgroup->getId()))).'"
											class="group-switch make-switch switch-small"
											data-off="danger"
											data-on="success"
											data-on-label="O"
											data-off-label="N"
											>';
								echo '<input type="checkbox" '.($sectorsgroup->isDisplay() ? 'checked="checked"' : '').'>';
								echo '</div>';
								
								echo '</td>';
								echo "<td>";
								echo '<a
										href="'.$this->url('administration', array('controller'=>'radio', 'action'=>'groupdown'), array('query'=>array('id'=>$sectorsgroup->getId()))).'"'.
										'class="groupdown'.($i == $total ? ' disabled':'').'">
									<span class="caret middle"></span></a>
									<a
										href="'.$this->url('administration', array('controller'=>'radio', 'action'=>'groupup'), array('query'=>array('id'=>$sectorsgroup->getId()))).'"'.
										'class="groupup'.($i == 1 ? ' disabled' : '').'">  <span class="up-caret middle"></span></a>';
								echo "</td>";
							echo '</tr>';
							}							
							?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
	
        <div class="span12">
		<div class="block">
			<div class="navbar navbar-inner block-header">
				<div class="muted pull-left">Fiches réflexes des antennes </div>
			</div>
			<div class="block-content collapse in">
				<div class="span12">
				<table class="table table-striped sortable">
					<thead>
						<tr>
							<th data-sort="string">Antenne</th>
							<th>Fiche réflexe</th>
                                                        <th></th>
						</tr>
					</thead>
					<tbody>
						<?php 
						foreach ($this->antennas as $antenna){
							echo '<tr>';
								echo '<td data-id="'.$antenna->getId().'">'.$antenna->getName().'</td>';
								echo '<td>'.($antenna->getModel() ? $antenna->getModel()->getName() : 'Aucun modèle associé.').'</td>';
                                                                echo '<td><a href="#model-container" '
                                                                . 'data-toggle="modal" '
                                                                . 'data-name="'.$antenna->getName().'" '
                                                                . 'data-id="'.$antenna->getId().'" '
                                                                . 'class="change-model"><i class="icon-pencil"></i></a></td>';
                                                        echo '</tr>';
							}							
							?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>

			
<?php echo $this->modalwindow("model-container", "<h3 id=\"model-title\"></h3>", "", "<div id=\"model-form\"></div>") ?>


<?php $this->inlineScript()->captureStart();?>

$(".sortable").stupidtable();

$(".sortable").bind('aftertablesort', function(event, data){
	var th = $(this).find("th");
    th.find(".arrow").remove();
    var arrow = data.direction === "asc" ? "<i class=\"icon-arrow-down\"></i>" : "<i class=\"icon-arrow-up\"></i>";
    th.eq(data.column).append('<span class="arrow"> ' + arrow +'</span>');
});

$("table th:eq(1)").trigger('click');

radio('<?php echo $this->url('administration'); ?>');

<?php if (isset($this->messages['success'])) { ?>
	<?php foreach ($this->messages['success'] as $message) { ?>
		var n = noty({text:'<?php echo $message ?>', 
					type:'success',
					layout: 'bottomRight',});
	<?php }?>
<?php } ?>

<?php if (isset($this->messages['error'])) { ?>
	<?php foreach ($this->messages['error'] as $message) { ?>
		var n = noty({text:'<?php echo $message ?>', 
					type:'error',
					layout: 'bottomRight',});
	<?php }?>
<?php } ?>
                                        
<?php $this->inlineScript()->captureEnd();?>