

<?php 
$this->form->setAttribute('action', $this->url('administration', array('controller'=>'radio', 'action'=>'savefrequency')));
$this->form->setAttribute('class', 'form-horizontal');
$this->form->prepare();

echo $this->form()->openTag($this->form);
?>
<div class="modal-body">
<?php


echo $this->formHidden($this->form->get('id'));

echo $this->controlGroup($this->form->get('defaultsector'));

echo $this->controlGroup($this->form->get('othername'));

echo $this->controlGroup($this->form->get('comment'));

echo $this->controlGroup($this->form->get('value'));

echo $this->controlGroup($this->form->get('organisation'));

echo $this->controlGroup($this->form->get('mainantenna'));

echo $this->controlGroup($this->form->get('backupantenna'));

echo $this->controlGroup($this->form->get('mainantennaclimax'));

echo $this->controlGroup($this->form->get('backupantennaclimax'));

echo $this->controlGroup($this->form->get('backupfrequencies'));

echo $this->controlGroup($this->form->get('decommissionned'));


?>


</div>
<div class="modal-footer">
<?php 

	echo $this->formSubmit($this->form->get('submit'));
?>
<button id="cancel-form" class="btn" href="#" data-dismiss="modal" aria-hidden="true">Annuler</button>
</div>
<?php 
echo $this->form()->closeTag();
?>
