

<?php 
$this->form->setAttribute('action', $this->url('administration', array('controller'=>'radio', 'action'=>'savefrequency')));
$this->form->setAttribute('class', 'form-horizontal');
$this->form->prepare();

echo $this->form()->openTag($this->form);
?>
<div class="modal-body">
<?php


echo $this->formHidden($this->form->get('id'));

echo $this->controlGroup($this->formLabel($this->form->get('defaultsector')->setLabelAttributes(array('class' => 'control-label'))),
						$this->formSelect($this->form->get('defaultsector')));

echo $this->controlGroup($this->formLabel($this->form->get('value')->setLabelAttributes(array('class' => 'control-label'))),
						$this->formInput($this->form->get('value')));

echo $this->controlGroup($this->formLabel($this->form->get('mainantenna')->setLabelAttributes(array('class' => 'control-label'))),
		$this->formSelect($this->form->get('mainantenna')));

echo $this->controlGroup($this->formLabel($this->form->get('backupantenna')->setLabelAttributes(array('class' => 'control-label'))),
		$this->formSelect($this->form->get('backupantenna')));

?>


</div>
<div class="modal-footer">
<?php 

	echo $this->formSubmit($this->form->get('submit'));
?>
<a id="cancel-form" class="btn" href="#" data-dismiss="modal" aria-hidden="true">Annuler</a>
</div>
<?php 
echo $this->form()->closeTag();
?>
