

<?php 
$this->form->setAttribute('action', $this->url('administration', array('controller'=>'radio', 'action'=>'saveantennamodel')));
$this->form->setAttribute('class', 'form-horizontal');
$this->form->prepare();

echo $this->form()->openTag($this->form);
?>
<div class="modal-body">
<?php


echo $this->formHidden($this->form->get('id'));

echo $this->controlGroup($this->formLabel($this->form->get('models')->setLabelAttributes(array('class' => 'control-label'))),
						$this->formSelect($this->form->get('models')));

?>


</div>
<div class="modal-footer">
<?php 

	echo $this->formSubmit($this->form->get('submit'));
?>
<a class="btn" href="#" data-dismiss="modal" aria-hidden="true">Annuler</a>
</div>
<?php 
echo $this->form()->closeTag();
?>
