

<?php 
$this->form->setAttribute('action', $this->url('administration', array('controller'=>'radio', 'action'=>'saveantenna')));
$this->form->setAttribute('class', 'form-horizontal');
$this->form->prepare();

echo $this->form()->openTag($this->form);
?>
<div class="modal-body">
<?php

echo $this->formHidden($this->form->get('id'));

echo $this->controlGroup($this->form->get('organisation'));

echo $this->controlGroup($this->form->get('name'));

echo $this->controlGroup($this->form->get('shortname'));

echo $this->controlGroup($this->form->get('location'));

echo $this->controlGroup($form->get('decommissionned'));

?>


</div>
<div class="modal-footer">
<?php 

	echo $this->formSubmit($this->form->get('submit'));
?>
<button id="cancel-form" class="btn" href="#" data-dismiss="modal" aria-hidden="true">Annuler</button>
</div>
<?php 
echo $this->form()->closeTag();
?>
