<?php $this->headScript()->appendFile($this->basePath() . '/assets/js/radio.js')?>

<div class="container-fluid">
	<div class="row">
		<div class="col-md-3" id="sidebar">
			<ul class="nav sidenav">
				<li>
					<a href="#antennas">
						1. Antennes
					</a>
				</li>
				<li>
					<a href="#frequencies">
						2. Fréquences
					</a>
				</li>
				<li>
					<a href="#oldantennas">
						3. Anciennes antennes
					</a>
				</li>
				<li>
					<a href="#oldfrequencies">
						4. Anciennes fréquences
					</a>
				</li>
			</ul>		
		</div>
		
		<div class="col-md-9">
			<p></p>
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title" id="antennas">1. Antennes </h4>
				</div>
				<div class="panel-body">
					<table class="table table-striped sortable">
						<thead>
							<tr>
								<th data-sort="int" data-autosort="true">Id</th>
								<th data-sort="string">Nom</th>
								<th data-sort="string">Nom abrégé</th>
								<th data-sort="string">Organisation</th>
								<th>Localisation</th>
								<th><a href="#antenna-container" id="add-antenna" data-toggle="modal" class="btn btn-xs btn-primary">Ajouter</a></th>
							</tr>
						</thead>
						<tbody>
							<?php 
							foreach ($this->antennas as $antenna){
								if(!$antenna->isDecommissionned()) {
									echo '<tr>';
										echo '<td>'.$antenna->getId().'</td>';
										echo '<td>'.$antenna->getName().'</td>';
										echo '<td>'.$antenna->getShortname().'</td>';
										echo '<td>'.$antenna->getOrganisation()->getName().'</td>';
										echo '<td>'.$antenna->getLocation().'</td>';
										echo "<td>";
											echo "<a 
													title=\"Modifier\"
													href=\"#antenna-container\"
													class=\"mod-antenna\"
													data-id=\"".$antenna->getId()."\"
													data-name=\"".$antenna->getName()."\" data-toggle=\"modal\"><span class=\"glyphicon glyphicon-pencil\"></span></a> ";
											echo "<a 
													title=\"Supprimer\"
													href=\"#confirm-delete-antenna\"
													data-href=\"".$this->url('administration', array('controller' => 'radio', 'action' => 'deleteantenna'))."?id=".$antenna->getId()."\"
													class=\"delete-antenna\"
													data-id=\"".$antenna->getId()."\"
													data-name=\"".$antenna->getName()."\" data-toggle=\"modal\"><span class=\"glyphicon glyphicon-trash\"></span> </a>";
										echo "</td>";
									echo '</tr>';
									}
								}							
								?>
							</tbody>
						</table>
				</div>
			</div>

			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title" id="frequencies">2. Fréquences</h4>
				</div>
				<div class="panel-body">
					<table class="table table-striped sortable">
						<thead>
							<tr>
								<th data-sort="int" data-autosort="true">Id</th>
								<th data-sort="string">Valeur</th>
								<th data-sort="string">Secteur par défaut</th>
                                <th>Commentaire</th>
								<th data-sort="string">Organisation</th>
								<th>Antenne principale</th>
								<th>Antenne principale climax</th>
								<th>Antenne secours</th>
								<th>Antenne secours climax</th>
                                <th>Fréquences secours préconisées</th>
								<th><a href="#frequency-container" id="add-frequency" data-toggle="modal" class="btn btn-xs btn-primary">Ajouter</a></th>
							</tr>
						</thead>
						<tbody>
							<?php 
							foreach ($this->frequencies as $frequency){
								if(!$frequency->isDecommissionned()) {
									echo '<tr id="frequency_'.$frequency->getId().'">';
										echo '<td>'.$frequency->getId().'</td>';
										echo '<td>'.$frequency->getValue().'</td>';
										echo '<td>'.($frequency->getDefaultsector() ? $frequency->getDefaultsector()->getName(): $frequency->getOthername()).'</td>';
										echo '<td>'.($frequency->getComment() ? $frequency->getComment() : "").'</td>';
										echo '<td>'.($frequency->getOrganisation() ? $frequency->getOrganisation()->getName() : "").'</td>';
										echo '<td>'.$frequency->getMainantenna()->getName().'</td>';
										echo '<td>'.($frequency->getMainantennaclimax() ? $frequency->getMainantennaclimax()->getName() : "").'</td>';
										echo '<td>'.($frequency->getBackupantenna() ? $frequency->getBackupantenna()->getName() : "").'</td>';
										echo '<td>'.($frequency->getBackupantennaclimax() ? $frequency->getBackupantennaclimax()->getName() : "").'</td>';
										echo '<td>';
										foreach ($frequency->getBackupfrequencies() as $f){
										    echo $f->getValue().' (' . ($f->getDefaultsector() ? $f->getDefaultsector()->getName(): $f->getOthername()).')<br>';
                                        }
										echo '</td>';
										echo "<td>";
											echo "<a
													title=\"Modifier\"
													href=\"#frequency-container\"
													class=\"mod-frequency\"
													data-id=\"".$frequency->getId()."\"
													data-name=\"".$frequency->getValue()."\" data-toggle=\"modal\"><span class=\"glyphicon glyphicon-pencil\"></span></a> ";
											echo "<a
													title=\"Supprimer\"
													href=\"#confirm-delete-frequency\"
													data-href=\"".$this->url('administration', array('controller' => 'radio', 'action' => 'deletefrequency'))."?id=".$frequency->getId()."\"
													class=\"delete-frequency\"
													data-id=\"".$frequency->getId()."\"
													data-name=\"".$frequency->getValue()."\" data-toggle=\"modal\"><span class=\"glyphicon glyphicon-trash\"></span> </a>";
										echo "</td>";
									echo '</tr>';
								}
							}							
							?>
						</tbody>
					</table>
				</div>
			</div>
	
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title" id="oldantennas">3. Anciennes antennes </h4>
				</div>
				<div class="panel-body">
					<table class="table table-striped sortable">
						<thead>
							<tr>
								<th data-sort="int" data-autosort="true">Id</th>
								<th data-sort="string">Nom</th>
								<th data-sort="string">Nom abrégé</th>
								<th data-sort="string">Organisation</th>
								<th>Localisation</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							<?php 
							foreach ($this->antennas as $antenna){
								if($antenna->isDecommissionned()) {
									echo '<tr>';
										echo '<td>'.$antenna->getId().'</td>';
										echo '<td>'.$antenna->getName().'</td>';
										echo '<td>'.$antenna->getShortname().'</td>';
										echo '<td>'.$antenna->getOrganisation()->getName().'</td>';
										echo '<td>'.$antenna->getLocation().'</td>';
										echo "<td>";
											echo "<a 
													title=\"Modifier\"
													href=\"#antenna-container\"
													class=\"mod-antenna\"
													data-id=\"".$antenna->getId()."\"
													data-name=\"".$antenna->getName()."\" data-toggle=\"modal\"><span class=\"glyphicon glyphicon-pencil\"></span></a> ";
											echo "<a 
													title=\"Supprimer\"
													href=\"#confirm-delete-antenna\"
													data-href=\"".$this->url('administration', array('controller' => 'radio', 'action' => 'deleteantenna'))."?id=".$antenna->getId()."\"
													class=\"delete-antenna\"
													data-id=\"".$antenna->getId()."\"
													data-name=\"".$antenna->getName()."\" data-toggle=\"modal\"><span class=\"glyphicon glyphicon-trash\"></span> </a>";
										echo "</td>";
									echo '</tr>';
									}
								}							
								?>
						</tbody>
					</table>
				</div>
			</div>

			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title" id="oldfrequencies">4. Anciennes fréquences</h4>
				</div>
				<div class="panel-body">
					<table class="table table-striped sortable">
						<thead>
							<tr>
								<th data-sort="int" data-autosort="true">Id</th>
								<th data-sort="string">Valeur</th>
								<th data-sort="string">Secteur par défaut</th>
                                <th>Commentaire</th>
								<th data-sort="string">Organisation</th>
								<th>Antenne principale</th>
								<th>Antenne principale climax</th>
								<th>Antenne secours</th>
								<th>Antenne secours climax</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							<?php 
							foreach ($this->frequencies as $frequency){
								if($frequency->isDecommissionned()){
									echo '<tr id="frequency_'.$frequency->getId().'">';
										echo '<td>'.$frequency->getId().'</td>';
										echo '<td>'.$frequency->getValue().'</td>';
										echo '<td>'.($frequency->getDefaultsector() ? $frequency->getDefaultsector()->getName(): $frequency->getOthername()).'</td>';
										echo '<td>'.($frequency->getComment() ? $frequency->getComment() : "").'</td>';
										echo '<td>'.($frequency->getOrganisation() ? $frequency->getOrganisation()->getName() : "").'</td>';
										echo '<td>'.$frequency->getMainantenna()->getName().'</td>';
										echo '<td>'.($frequency->getMainantennaclimax() ? $frequency->getMainantennaclimax()->getName() : "").'</td>';
										echo '<td>'.$frequency->getBackupantenna()->getName().'</td>';
										echo '<td>'.($frequency->getBackupantennaclimax() ? $frequency->getBackupantennaclimax()->getName() : "").'</td>';
										echo "<td>";
											echo "<a
													title=\"Modifier\"
													href=\"#frequency-container\"
													class=\"mod-frequency\"
													data-id=\"".$frequency->getId()."\"
													data-name=\"".$frequency->getValue()."\" data-toggle=\"modal\"><span class=\"glyphicon glyphicon-pencil\"></span></a> ";
											echo "<a
													title=\"Supprimer\"
													href=\"#confirm-delete-frequency\"
													data-href=\"".$this->url('administration', array('controller' => 'radio', 'action' => 'deletefrequency'))."?id=".$frequency->getId()."\"
													class=\"delete-frequency\"
													data-id=\"".$frequency->getId()."\"
													data-name=\"".$frequency->getValue()."\" data-toggle=\"modal\"><span class=\"glyphicon glyphicon-trash\"></span> </a>";
										echo "</td>";
									echo '</tr>';
								}
							}							
							?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>



<?php echo $this->modalwindow("antenna-container", "<h4 id=\"antenna-title\"></h4>", "", "<div id=\"antenna-form\"></div>") ?>

<?php echo $this->modalwindow("confirm-delete-antenna",
						"<h4>Confirmer la suppression ?</h4>",
						"", 
						null, 
						"<p>Voulez-vous vraiment supprimer l'antenne <em><span id=\"antenna-name\"></span></em> ?</p>",
						"<a class=\"btn btn-danger\" id=\"delete-antenna-href\">Confirmer</a>
						<button class=\"btn\" href=\"#\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</button>") ?>
						
<?php echo $this->modalwindow("frequency-container", "<h4 id=\"frequency-title\"></h4>", "", "<div id=\"frequency-form\"></div>") ?>

<?php echo $this->modalwindow("confirm-delete-frequency",
						"<h4>Confirmer la suppression ?</h4>",
						"", 
						null, 
						"<p>Voulez-vous vraiment supprimer la fréquence <em><span id=\"frequency-name\"></span></em> ?</p>",
						"<a class=\"btn btn-danger\" id=\"delete-frequency-href\">Confirmer</a>
						<button class=\"btn\" href=\"#\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</button>") ?>				



<?php $this->inlineScript()->captureStart();?>

$('.sidenav').affix();

$('body').scrollspy({target:'#sidebar', offset:120});

radio('<?php echo $this->url('administration'); ?>');

<?php echo $this->notifications($this->messages); ?>

<?php $this->inlineScript()->captureEnd();?>