<?php 
$form = $this->form;
$form->add(	
	['name' => 'submit',
    	'attributes' => [
            'type' => 'submit',
            'value' => 'Enregistrer',
            'class' => 'btn btn-primary btn-small'
        ]
    ]);
$form->setAttribute('action', $this->url('application', array('controller'=>'afis', 'action'=>'save')));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>

<?php echo $this->form()->openTag($form) ?>

<div class="modal-body">

    <?php 

    echo $this->formHidden($form->get('id'));
    echo $this->formHidden($form->get('state'));
    echo $this->controlGroup($form->get('code'));
    echo $this->controlGroup($form->get('name'));

    echo $this->controlGroup($form->get('organisation'));
    echo $this->controlGroup($form->get('decommissionned'));
    echo $this->controlGroup($form->get('openedhours'));
    echo $this->controlGroup($form->get('contacts'));
    ?>

</div>

<div class="modal-footer">
<?=$this->formSubmit($this->form->get('submit')); ?>
</div>
  
<?php echo $this->form()->closeTag() ?>
