<?php $this->headLink()->prependStylesheet($this->basePath() . '/assets/css/afis.css'); ?>
<?php $this->headScript()->appendFile($this->basePath() . '/assets/js/headerbar.js'); ?>
<?php $this->headScript()->appendFile($this->basePath() . '/assets/js/notams.js'); ?>
<?php $this->headScript()->appendFile($this->basePath() . '/assets/js/afis.js'); ?>

<div class="row col-sm-8 col-sm-offset-2">
    <?php if(count($cats) == 0): ?>
    <p class="text-warning">Aucune catégorie d'événement 'Afis' n'existe, impossible de continuer.</p>
    <?php else: ?>

     <div id="search-afis" class="form-group form-group-material-blue-500 has-feedback">
        <input class="form-control" placeholder="LFXX" type="text"><span class="glyphicon glyphicon-search form-control-feedback"></span>
    </div>

     <div class="panel panel-default">
        <div class="panel-body">
            <table class="table t-usr table-striped table-hover sortable">
                <thead>
                    <tr>
                        <th data-sort="string">Code OACI</th>
                        <th data-sort="string">Nom</th>
                        <th data-sort="bool">État</th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody id = "list-afis">
                <?php
                foreach ($this->afis as $af)
                {
                    echo $this->afViewHelper()->renderRow($af);
                }
                ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php endif; ?>
</div>

<?=$this->modalwindow(  "mdl-show-not",
                        "<h3 id='title-show-not'></h3>",
                        "",
                        null,
                        "<div class='loading'></div>".
                        '<div class="list-group" id="show-not">
                          <div>
                            <a data-toggle="collapse" data-parent="#show-not" href="">
                            </a> <strong class="rapid-not-info"></strong>
                            <p class="collapse">

                            </p>
                            <hr>
                          </div>
                        </div>',
                        '<div><a id="refresh-not" class="btn btn-primary" href="#" aria-hidden="true">RAFRAICHIR</a><a class="btn btn-primary" href="#" data-dismiss="modal" aria-hidden="true">FERMER</a></div>',
                        'modal-lg'
                    ) ?>

<?php $this->inlineScript()->captureStart(); ?>

$("#create-link").remove();

$("#changeview").remove();

$('#search').remove();

afis('<?php echo $this->url('application'); ?>');

<?php $this->inlineScript()->captureEnd();?>
