<?php $this->headLink()->prependStylesheet($this->basePath() . '/assets/css/afis.css'); ?>
<?php $this->headScript()->appendFile($this->basePath() . '/assets/js/headerbar.js'); ?>
<?php $this->headScript()->appendFile($this->basePath() . '/assets/js/afis.js'); ?>

<div class="row col-sm-8 col-sm-offset-2">

    <!-- <div class="panel panel-default"> -->
        <!-- <div class="panel-body"> -->
             <div id="search-afis" class="form-group form-group-material-blue-500 has-feedback">
                <input class="form-control" placeholder="LFXX" type="text"><span class="glyphicon glyphicon-search form-control-feedback"></span>
            </div>       
        <!-- </div> -->
    <!-- </div> -->

     <div class="panel panel-default">
        <div class="panel-body">
            <table class="table t-usr table-striped table-hover sortable">
                <thead>
                    <tr>
                        <th data-sort="string">Code OACI</th>
                        <th data-sort="string">Nom</th>
                        <th>État</th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody id = "list-afis">

                </tbody>
            </table>
        </div>
    </div>
</div>

<?=$this->modalWindow(  "mdl-show-not", 
                        "<h3 id='title-show-not'></h3>", 
                        "", 
                        '<div class="list-group" id="show-not">
                          <div>
                            <a data-toggle="collapse" data-parent="#show-not" href="">
                            </a>
                            <p class="collapse">
                              
                            </p>
                          </div>
                        </div>'); 
                        ?>

<?php $this->inlineScript()->captureStart(); ?>

$("#home").removeClass("dropdown-toggle")
		  .attr('data-toggle', '')
		  .html('<span class="glyphicon glyphicon-home"></span> Évènements');

$("#create-link").remove();		  

$("#changeview").remove();

$('#search').remove();

afis('<?php echo $this->url('application'); ?>');

<?php $this->inlineScript()->captureEnd();?>