<?php echo $this->doctype(); ?>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Epeires² - IPO'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/assets/css/ipo.css') 
                        ->prependStylesheet($this->basePath() . '/assets/css/core.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-switch.css')
                        ->prependStylesheet($this->basePath() . '/components/bootstrap-default/css/bootstrap-responsive.css')
                        ->prependStylesheet($this->basePath() . '/components/bootstrap-default/css/bootstrap.css')
                        ->prependStylesheet($this->basePath() . '/components/jquery-ui/themes/smoothness/jquery-ui.min.css')
        				?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/assets/js/application.js')
                                        ->prependFile($this->basePath() . '/js/bootstrap-switch.js')
        				->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                        ->prependFile($this->basePath() . '/components/bootstrap/js/bootstrap.min.js')
                        ->prependFile($this->basePath() . '/js/noty/packaged/jquery.noty.packaged.min.js')
                        ->prependFile($this->basePath() . '/components/jquery-ui/ui/minified/i18n/datepicker-fr.min.js')
                        ->prependFile($this->basePath() . '/components/jquery-ui/jquery-ui.min.js')
                        ->prependFile($this->basePath() . '/components/jquery/jquery.min.js')

        							   ?>

    </head>
    <body data-spy="scroll" data-target="#sidebar">
    	<div class="header">
    		<ul class="inline">
    				<?php echo $this->userMenu(); ?>
    				<li id="clock" class="pull-right"></li>
    		</ul>
    	</div>
	<div class="navbar navbar-after-top">
		<div class="navbar-inner">
			<a class="brand" href="<?php echo $this->url('ipo'); ?>">Epeires<sup>2</sup> : IPO</a>
			<?php if($this->title){?>
			<a class="brand" href="#">
				<?php 
					echo " : <small>".$this->title."</small>"; 
				?>
			</a>
			<?php }?>
			<ul class="nav">
			</ul>
		</div>
	</div>
	
	<div class="content">
		<div class="warnings">
		<?php if (isset($this->messages['successMessages'])) { ?>
			<?php foreach ($this->messages['successMessages'] as $message) { ?>
				<div class="alert alert-success">
					<a class="close" data-dismiss="alert" href="#">&times;</a>
					<?php echo $message ?>
				</div>
			<?php }?>
		<?php } ?>

		<?php if (isset($this->messages['errorMessages'])) { ?>
			<?php foreach ($this->messages['errorMessages'] as $message) { ?>
				<div class="alert alert-error">
					<a class="close" data-dismiss="alert" href="#">&times;</a>
					<?php echo $message ?>
				</div>
			<?php }?>
		<?php } ?>
		</div>
	
        <?php echo $this->content; ?>
    
    </div> <!-- /container -->
        
    <?php 
	if(!$this->zfcuserIdentity()){
			echo $this->modalWindow("loginwindow", "<h3>Connexion</h3>", "", $this->zfcUserLoginWidget(array('redirect'=>$this->url('ipo'))));
	} ?>
        
    <?php echo $this->inlineScript() ?>
    </body>
</html>
