<?php echo $this->doctype(); ?>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Epeires² - IPO'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/assets/css/ipo.css') 
                        ->prependStylesheet($this->basePath() . '/assets/css/core.css')
                        ->prependStylesheet($this->basePath() . '/components/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/google_material_font.css')
                        ->prependStylesheet($this->basePath() . '/components/bootstrap-material-design/dist/css/ripples.min.css')
                        ->prependStylesheet($this->basePath() . '/components/bootstrap-material-design/dist/css/material-epeirespalette.min.css')
                        ->prependStylesheet($this->basePath() . '/components/bootstrap-material-design/dist/css/roboto.min.css')
                        ->prependStylesheet($this->basePath() . '/components/bootstrap/dist/css/bootstrap.min.css')
        				?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/assets/js/application.js')
                        ->prependFile($this->basePath() . '/components/fullcalendar/dist/locale/fr.js')
                        ->prependFile($this->basePath() . '/components/fullcalendar/dist/fullcalendar.min.js')
                        ->prependFile($this->basePath() . '/components/jquery-stupid-table/stupidtable.min.js')
                        ->prependFile($this->basePath() . '/components/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js')
                        ->prependFile($this->basePath() . '/components/momentjs/min/moment.min.js')
                        ->prependFile($this->basePath() . '/components/bootstrap-material-design/dist/js/material.min.js')
                        ->prependFile($this->basePath() . '/components/bootstrap-material-design/dist/js/ripples.min.js')
                        ->prependFile($this->basePath() . '/components/bootstrap/dist/js/bootstrap.min.js')
                        ->prependFile($this->basePath() . '/components/noty/js/noty/packaged/jquery.noty.packaged.min.js')
                        ->prependFile($this->basePath() . '/components/jquery-ui/jquery-ui.min.js')
                        ->prependFile($this->basePath() . '/components/arrive/minified/arrive.min.js')
                        ->prependFile($this->basePath() . '/components/jquery-validation/src/localization/messages_fr.js')
                        ->prependFile($this->basePath() . '/components/jquery-validation/dist/jquery.validate.min.js')
                        ->prependFile($this->basePath() . '/components/jquery/dist/jquery.min.js')

        							   ?>

    </head>
    <body data-spy="scroll" data-target="#sidebar">
    
    <?php echo $this->navbartop("blue", ' : IPO', 'ipo', null); ?>
	
	<div class="content">
	
        <?php echo $this->content; ?>
    
    </div> <!-- /container -->
        
    <?php 
	if(!$this->zfcuserIdentity()){
			echo $this->modalWindow("loginwindow", "<h3>Connexion</h3>", "", $this->zfcUserLoginWidget(array('redirect'=>$this->url('ipo'))));
	} ?>
        
    <?php echo $this->inlineScript() ?>
    </body>
</html>
