<?php $this->headScript()->appendFile($this->basePath() . '/assets/js/radars.js')?>
<?php 
	
	function trRadar($radar, $deleteUrl, $decommissionurl = null){
		echo '<tr>';
		echo '<td>'.$radar->getId().'</td>';
		echo '<td>'.$radar->getName().'</td>';
		echo '<td>'.$radar->getShortname().'</td>';
		echo '<td>'.$radar->getOrganisation()->getName().'</td>';
		echo '<td>';
		echo "<a
				title=\"Modifier\"
				href=\"#radar-container\"
				class=\"mod-radar\"
				data-id=\"".$radar->getId()."\"
				data-name=\"".$radar->getName()."\"
				data-toggle=\"modal\"><span class=\"glyphicon glyphicon-pencil\"></span></a>  ";
		if($decommissionurl) {
            echo "<a
				title=\"Archiver\"
				href=\"#confirm-decommission-radar\"
				data-href=\"" . $decommissionurl . "\"
				class=\"decommission-radar\"
				data-id=\"" . $radar->getId() . "\"
				data-name=\"" . $radar->getName() . "\"
				data-toggle=\"modal\"><span class=\"glyphicon glyphicon-hdd\"></span></a>  ";
        }
		echo "<a
				title=\"Supprimer\"
				href=\"#confirm-delete-radar\"
				data-href=\"".$deleteUrl."\"
				class=\"delete-radar\"
				data-id=\"".$radar->getId()."\"
				data-name=\"".$radar->getName()."\"
				data-toggle=\"modal\"><span class=\"glyphicon glyphicon-trash\"></span></a>";
		echo '</td>';
		echo '</tr>';
	}
?>

<div class="container-fluid">
	<div class="row">
		<div class="col-md-3" id="sidebar">
			<ul class="nav sidenav">
				<li>
					<a href="#radars">1. Radars</a>
				</li>
				<li>
					<a href="#oldradars">2. Anciens radars</a>
				</li>
			</ul>
		</div>
		<div class="col-md-9">
			<p></p>
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title" id="radars">1. Radars en service</h4>
				</div>
				<div class="panel-body">
                    <table class="table table-striped sortable">
                        <thead>
                        	<tr>
                        		<th data-sort="int">id</th>
                        		<th data-sort="string" data-autosort="true">Nom</th>
                        		<th data-sort="string">Nom court</th>
                        		<th>Organisation</th>
                        		<th><a class="btn btn-xs btn-primary" href="#radar-container" data-toggle="modal" id="add-radar">Ajouter</a></th>
                        	</tr>
                        </thead>
                        <tbody>
                        	<?php 	
                        	foreach ($this->radars as $radar){
                        		if(!$radar->isDecommissionned()){
                        			trRadar(
                        			        $radar,
                                            $this->url('administration', array('controller'=>'radars', 'action'=>'delete'), array('query'=>array('id'=>$radar->getId()))),
                                            $this->url('administration', array('controller'=>'radars', 'action'=>'decommission'), array('query'=>array('id'=>$radar->getId())))
                                    );
                        		}
                        	}
                        	?>
                        </tbody>
                    </table>
				</div>
			</div>
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title" id="oldradars">2. Anciens radars</h4>
				</div>
				<div class="panel-body">
					<table class="table table-striped sortable">
                        <thead>
                        	<tr>
                        		<th data-sort="int">id</th>
                        		<th data-sort="string" data-autosort="true">Nom</th>
                        		<th data-sort="string">Nom court</th>
                        		<th>Organisation</th>
                        		<th></th>
                        	</tr>
                        </thead>
                        
                        <tbody>
                        	<?php 	
                        	foreach ($this->radars as $radar){
                        		if($radar->isDecommissionned()){
                                    trRadar(
                                        $radar,
                                        $this->url('administration', array('controller'=>'radars', 'action'=>'delete'), array('query'=>array('id'=>$radar->getId())))
                                    );
                        		}
                        	}
                        	?>
                        </tbody>
                    </table>
				</div>
			</div>
		</div>
	</div>
</div>

<?php echo $this->modalWindow("radar-container", "<h3 id=\"radar-title\">Nouveau radar</h3>", "", "<div id=\"radar-form\"></div>")?>

<?php echo $this->modalwindow("confirm-delete-radar",
						"<h4>Confirmer la suppression ?</h4>",
						"", 
						null,
                        "<div class=\"alert alert-warning\">La suppression définitive d'un radar impacte les évènements existants liés à ce radar."
                        ." Si des évènements liés à ce radar existent, il est préférable de l'archiver (<span class='glyphicon glyphicon-hand-right'></span> Modifier puis cocher la case Hors Service).</div>"
						."<p>Voulez-vous vraiment supprimer le radar <em><span class=\"radar-name\"></span></em> ?</p>",
						"<a class=\"btn btn-danger\" id=\"delete-radar-href\">Confirmer</a>
						<button class=\"btn\" href=\"#\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</button>") ?>

<?php echo $this->modalwindow("confirm-decommission-radar",
    "<h4>Confirmer l'archivage ?</h4>",
    "",
    null,
    "<p>Voulez-vous vraiment archiver le radar <em><span class=\"radar-name\"></span></em> ?</p>",
    "<a class=\"btn btn-danger\" id=\"decommission-radar-href\">Confirmer</a>
						<button class=\"btn\" href=\"#\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</button>") ?>

<?php $this->inlineScript()->captureStart();?>

$('.sidenav').affix();

$('body').scrollspy({target:'#sidebar', offset:120});

radars('<?php echo $this->url('administration')?>');

<?php echo $this->notifications($this->messages); ?>

<?php $this->inlineScript()->captureEnd();?>