<?php $this->headScript()->appendFile($this->basePath() . '/js/stupidtable.min.js')?>
<?php $this->headScript()->appendFile($this->basePath() . '/assets/js/radars.js')?>
<?php 
	
	function trRadar($radar, $deleteUrl){
		echo '<tr>';
		echo '<td>'.$radar->getId().'</td>';
		echo '<td>'.$radar->getName().'</td>';
		echo '<td>'.$radar->getShortname().'</td>';
		echo '<td>'.$radar->getOrganisation()->getName().'</td>';
		echo '<td>'.($radar->isDecommissionned() ? '<i class="icon-remove"></i>' : '<i class="icon-ok"></i>');
		echo '<td>';
		echo "<a
				title=\"Modifier\"
				href=\"#radar-container\"
				class=\"mod-radar\"
				data-id=\"".$radar->getId()."\"
				data-name=\"".$radar->getName()."\"
				data-toggle=\"modal\"><i class=\"icon-pencil\"></i></a>  ";
		echo "<a
				title=\"Supprimer\"
				href=\"#confirm-delete-radar\"
				data-href=\"".$deleteUrl."\"
				class=\"delete-radar\"
				data-id=\"".$radar->getId()."\"
				data-name=\"".$radar->getName()."\"
				data-toggle=\"modal\"><i class=\"icon-trash\"></i> </a>";
		echo '</td>';
		echo '</tr>';
	}
?>

<h2>Radars en service</h2>

<table class="table table-striped sortable">
<thead>
	<tr>
		<th>id</th>
		<th data-sort="string">Nom</th>
		<th data-sort="string">Nom court</th>
		<th>Organisation</th>
		<th>En service</th>
		<th><a class="btn btn-mini" href="#radar-container" data-toggle="modal" id="add-radar">Ajouter</a></th>
	</tr>
</thead>

<tbody>
	<?php 	
	foreach ($this->radars as $radar){
		if(!$radar->isDecommissionned()){
			trRadar($radar, $this->url('administration', array('controller'=>'radars', 'action'=>'delete'), array('query'=>array('id'=>$radar->getId()))));
		}
	}
	?>
</tbody>

</table>

<h2>Anciens radars</h2>

<table class="table table-striped sortable">
<thead>
	<tr>
		<th>id</th>
		<th data-sort="string">Nom</th>
		<th data-sort="string">Nom court</th>
		<th>Organisation</th>
		<th>En service</th>
		<th></th>
	</tr>
</thead>

<tbody>
	<?php 	
	foreach ($this->radars as $radar){
		if($radar->isDecommissionned()){
			trRadar($radar, $this->url('administration', array('controller'=>'radars', 'action'=>'delete'), array('query'=>array('id'=>$radar->getId()))));
		}
	}
	?>
</tbody>

</table>

<?php echo $this->modalWindow("radar-container", "<h3 id=\"radar-title\">Nouveau radar</h3>", "", "<div id=\"radar-form\"></div>")?>

<?php echo $this->modalwindow("confirm-delete-radar",
						"<h3>Confirmer la suppression ?</h3>",
						"", 
						null, 
						"<p>Voulez-vous vraiment supprimer le radar <em><span id=\"radar-name\"></span></em> ?</p>",
						"<a class=\"btn btn-danger\" id=\"delete-radar-href\">Confirmer</a>
						<a class=\"btn\" href=\"#\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</a>") ?>	


<?php $this->inlineScript()->captureStart();?>

radars('<?php echo $this->url('administration')?>');

$(".sortable").stupidtable();

$(".sortable").bind('aftertablesort', function(event, data){
	var th = $(this).find("th");
    th.find(".arrow").remove();
    var arrow = data.direction === "asc" ? "<i class=\"icon-arrow-down\"></i>" : "<i class=\"icon-arrow-up\"></i>";
    th.eq(data.column).append('<span class="arrow"> ' + arrow +'</span>');
});

<?php echo $this->notifications($this->messages); ?>

<?php $this->inlineScript()->captureEnd();?>