<?php

$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('administration', array('controller'=>'opsups', 'action'=>'saveopsup')));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');

echo $this->form()->openTag($form) 

?>

<div class="modal-body">

<?php 

echo $this->formInput($form->get('id'));

echo $this->controlGroup($form->get('name'));

echo $this->controlGroup($form->get('organisation'));

echo $this->controlGroup($form->get('zone'));

echo $this->controlGroup($form->get('type'));

?>

</div>

<div class="modal-footer">
<?php
echo $this->formSubmit($this->form->get('submit'));
?>
</div>

    
<?php echo $this->form()->closeTag() ?>
