<?php


use Zend\Form\Element\Select;

$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('administration', array('controller'=>'opsups', 'action'=>'saveopsup')));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');

?>

<?php echo $this->form()->openTag($form) ?>

<div class="modal-body">

<?php 

echo $this->formInput($form->get('id'));

echo $this->controlGroup($this->formLabel($form->get('name')->setLabelAttributes(array('class' => 'control-label'))),
		$this->formInput($form->get('name')) . $this->formElementErrors($form->get('name')));

echo $this->controlGroup($this->formLabel($form->get('organisation')->setLabelAttributes(array('class' => 'control-label'))),
		$this->formSelect($form->get('organisation')) . $this->formElementErrors($form->get('organisation')));

echo $this->controlGroup($this->formLabel($form->get('zone')->setLabelAttributes(array('class' => 'control-label'))),
		$this->formSelect($form->get('zone')) . $this->formElementErrors($form->get('zone')));

?>

</div>

<div class="modal-footer">
<?php
echo $this->formSubmit($this->form->get('submit'));
?>
</div>

    
<?php echo $this->form()->closeTag() ?>
