<?php $this->headScript()->appendFile($this->basePath() . '/assets/js/opsups.js')?>

<?php

$formatterHour = \IntlDateFormatter::create(
    \Locale::getDefault(),
    \IntlDateFormatter::FULL,
    \IntlDateFormatter::FULL,
    'UTC',
    \IntlDateFormatter::GREGORIAN,
    'HH:mm'
);

$formatterHourLoc = \IntlDateFormatter::create(
    \Locale::getDefault(),
    \IntlDateFormatter::FULL,
    \IntlDateFormatter::FULL,
    new \DateTimeZone('Europe/Paris'),
    \IntlDateFormatter::GREGORIAN,
    'HH:mm'
);


?>

<div class="container-fluid">
<div class="row">
    <div class="col-md-3" id="sidebar">
        <ul class="nav sidenav">
            <li>
                <a href="#Types">
                    1. Types superviseurs opérationnels
                </a>
            </li>
            
            <li>
                <a href="#shifthours">
                    2. Tours de service
                </a>
            </li>
            <li>
                <a href="#Opsups">
                    3. Liste des superviseurs opérationnels
                </a>
            </li>
            <li>
                <a href="#Opsups-archived">
                    4. Liste des superviseurs opérationnels archivés
                </a>
            </li>
        </ul>
    </div>
    <div class="col-md-9">
<p></p>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title" id="Types">Types superviseurs opérationnels</h4>
            </div>
            <div class="panel-body">
                <table class="table table-striped sortable">
                    <thead>
                    <tr>
                        <th data-sort="int">id</th>
                        <th data-sort="string" data-autosort="true">Nom</th>
                        <th data-sort="string">Nom court</th>
                        <th>Visible pour</th>
                        <th><a class="btn btn-xs btn-primary" href="#opsuptype-container" data-toggle="modal" id="add-opsuptype">Ajouter</a></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    foreach($this->types as $type) {
                        echo '<tr>';
                        echo '<td>'.$type->getId().'</td>';
                        echo '<td>'.$type->getName().'</td>';
                        echo '<td>'.$type->getShortname().'</td>';
                        echo '<td>';
                        foreach ($type->getRoles() as $role) {
                            echo $role->getName() . '<br />';
                        }
                        echo '</td>';
                        echo '<td>';
                        echo "<a
                            title=\"Modifier\"
                            href=\"#opsuptype-container\"
                            class=\"mod-opsuptype\"
                            data-id=\"".$type->getId()."\"
                            data-name=\"".$type->getName()."\"
                            data-toggle=\"modal\"><span class=\"glyphicon glyphicon-pencil\"></span></a>  ";
                        echo "<a
                            title=\"Supprimer\"
                            href=\"#confirm-delete-opsuptype\"
                            data-href=\"".$this->url('administration', array('controller'=>'opsups', 'action'=>'deleteopsuptype'), array('query'=>array('id'=>$type->getId())))."\"
                            class=\"delete-opsuptype\"
                            data-id=\"".$type->getId()."\"
                            data-name=\"".$type->getName()."\"
                            data-toggle=\"modal\"><span class=\"glyphicon glyphicon-trash\"></span> </a>";
                        echo '</td>';
                        echo '</tr>';
                    }
                    ?>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title" id="shifthours">Tours de service</h4>
            </div>
            <div class="panel-body">
                <table class="table table-striped sortable">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th data-sort="string" data-autosort="true">Type</th>
                        <th data-sort="string">Zone qualif.</th>
                        <th>Heure locale</th>
                        <th><a class="btn btn-xs btn-primary" href="#shifthour-container" data-toggle="modal" id="add-shifthour">Ajouter</a></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    foreach ($shifthours as $shifthour) {
                        echo '<tr>';
                        echo '<td>' . $shifthour->getId() . '</td>';
                        echo '<td>' . $shifthour->getOpsuptype()->getName() . '</td>';
                        echo '<td>' . ($shifthour->getQualificationzone() == null ? '' : $shifthour->getQualificationzone()->getName()) . '</td>';
                        echo '<td>' . $formatterHourLoc->format($shifthour->getHour()) . '</td>';
                        echo '<td>';
                        echo "<a 
                                title=\"Modifier\" 
                                href=\"#shifthour-container\" 
                                class=\"mod-shifthour\" 
                                data-id=\"".$shifthour->getId()."\" 
                                data-toggle=\"modal\"><span class=\"glyphicon glyphicon-pencil\"></span></a>  ";
                        echo "<a 
                                title=\"Supprimer\" 
                                href=\"#confirm-delete-shifthour\" 
                                data-href=\"".$this->url('administration', array('controller'=>'opsups', 'action'=>'deleteshifthour'), array('query'=>array('id'=>$shifthour->getId())))."\" 
                                class=\"delete-shifthour\" 
                                data-id=\"".$shifthour->getId()."\" 
                                data-toggle=\"modal\"><span class=\"glyphicon glyphicon-trash\"></span> </a>";
                        echo '</td>';
                        echo '</tr>';
                    }
                    ?>
                    </tbody>
                </table>
            </div>
        </div>
        
<div class="panel panel-default">
<div class="panel-heading">
	<h4 class="panel-title" id="Opsups">Liste des superviseurs opérationnels</h4>
</div>
<div class="panel-body">
<table class="table table-striped sortable">
<thead>
	<tr>
		<th data-sort="int">id</th>
		<th data-sort="string" data-autosort="true">Nom</th>
		<th data-sort="string">Organisation</th>
		<th>Zone de qualification</th>
		<th>Type</th>
		<th><a class="btn btn-xs btn-primary" href="#opsup-container" data-toggle="modal" id="add-opsup">Ajouter</a></th>
	</tr>
</thead>

<tbody>
	<?php 
	foreach ($this->opsups as $opsup){
		echo '<tr>';
		echo '<td>'.$opsup->getId().'</td>';
		echo '<td>'.$opsup->getName().'</td>';
		echo '<td>'.$opsup->getOrganisation()->getName().'</td>';
		echo '<td>'.$opsup->getZone()->getName().'</td>';
		echo '<td>'.$opsup->getType()->getName().'</td>';
		echo '<td>';
		echo "<a 
				title=\"Modifier\" 
				href=\"#opsup-container\" 
				class=\"mod-opsup\" 
				data-id=\"".$opsup->getId()."\" 
				data-name=\"".$opsup->getName()."\" 
				data-toggle=\"modal\"><span class=\"glyphicon glyphicon-pencil\"></span></a>  ";
		echo "<a 
				title=\"Archiver\" 
				href=\"#confirm-archive-opsup\" 
				data-href=\"".$this->url('administration', array('controller'=>'opsups', 'action'=>'archiveopsup'), array('query'=>array('id'=>$opsup->getId())))."\" 
				class=\"archive-opsup\" 
				data-id=\"".$opsup->getId()."\" 
				data-name=\"".$opsup->getName()."\" 
				data-toggle=\"modal\"><span class=\"glyphicon glyphicon-folder-close\"></span> </a>";
		echo '</td>';
		echo '</tr>';
	}
	?>
</tbody>

</table>
</div>
</div>


        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title" id="Opsups-archived">Liste des superviseurs opérationnels archivés</h4>
            </div>
            <div class="panel-body">
                <table class="table table-striped sortable">
                    <thead>
                    <tr>
                        <th data-sort="int">id</th>
                        <th data-sort="string" data-autosort="true">Nom</th>
                        <th data-sort="string">Organisation</th>
                        <th>Zone de qualification</th>
                        <th>Type</th>
                        <th></th>
                    </tr>
                    </thead>

                    <tbody>
                    <?php
                    foreach ($this->opsupsArchived as $opsup){
                        echo '<tr>';
                        echo '<td>'.$opsup->getId().'</td>';
                        echo '<td>'.$opsup->getName().'</td>';
                        echo '<td>'.$opsup->getOrganisation()->getName().'</td>';
                        echo '<td>'.$opsup->getZone()->getName().'</td>';
                        echo '<td>'.$opsup->getType()->getName().'</td>';
                        echo '<td>';
                        echo "<a 
				title=\"Modifier\" 
				href=\"#opsup-container\" 
				class=\"mod-opsup\" 
				data-id=\"".$opsup->getId()."\" 
				data-name=\"".$opsup->getName()."\" 
				data-toggle=\"modal\"><span class=\"glyphicon glyphicon-pencil\"></span></a>  ";
                        echo "<a 
				title=\"Supprimer\" 
				href=\"#confirm-delete-opsup\" 
				data-href=\"".$this->url('administration', array('controller'=>'opsups', 'action'=>'deleteopsup'), array('query'=>array('id'=>$opsup->getId())))."\" 
				class=\"delete-opsup\" 
				data-id=\"".$opsup->getId()."\" 
				data-name=\"".$opsup->getName()."\" 
				data-toggle=\"modal\"><span class=\"glyphicon glyphicon-trash\"></span> </a>";
                        echo '</td>';
                        echo '</tr>';
                    }
                    ?>
                    </tbody>

                </table>
            </div>
        </div>


</div>
</div>
</div>

<?php echo $this->modalWindow("shifthour-container", "<h4 id=\"shifthour-title\">Nouvelle heure de relève</h4>", "", "<div id=\"shifthour-form\"></div>")?>

<?php echo $this->modalwindow("confirm-delete-shifthour",
    "<h4>Confirmer la suppression ?</h4>",
    "",
    null,
    "<p>Voulez-vous vraiment supprimer cette heure de relève de la liste ?</p>",
    "<a class=\"btn btn-danger\" id=\"delete-shifthour-href\">Confirmer</a>
						<button class=\"btn\" href=\"#\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</button>") ?>


<?php echo $this->modalWindow("opsup-container", "<h4 id=\"opsup-title\">Nouveau Chef OP</h4>", "", "<div id=\"opsup-form\"></div>")?>

<?php echo $this->modalwindow("confirm-delete-opsup",
						"<h4>Confirmer la suppression ?</h4>",
						"", 
						null, 
						"<p>Voulez-vous vraiment supprimer le chef OP <em><span id=\"opsup-name\"></span></em> de la liste ?</p>",
						"<a class=\"btn btn-danger\" id=\"delete-opsup-href\">Confirmer</a>
						<button class=\"btn\" href=\"#\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</button>") ?>

<?php echo $this->modalwindow("confirm-archive-opsup",
    "<h4>Confirmer l'archivage ?</h4>",
    "",
    null,
    "<p>Voulez-vous vraiment archiver le chef OP <em><span id=\"opsup-name\"></span></em> de la liste ?</p>",
    "<a class=\"btn btn-danger\" id=\"archive-opsup-href\">Confirmer</a>
	<button class=\"btn\" href=\"#\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</button>") ?>

<?php echo $this->modalWindow("opsuptype-container", "<h4 id=\"opsuptype-title\">Nouveau type OP Sup</h4>", "", "<div id=\"opsuptype-form\"></div>")?>

<?php echo $this->modalwindow("confirm-delete-opsuptype",
    "<h4>Confirmer la suppression ?</h4>",
    "",
    null,
    "<p>Voulez-vous vraiment supprimer le type de superviseur opérationnel <em><span id=\"opsuptype-name\"></span></em> de la liste ?</p>
    <p><em>Tous les superviseurs opérationnels ainsi que les heures de relève associés seront supprimés !</em></p>",
    "<a class=\"btn btn-danger\" id=\"delete-opsuptype-href\">Confirmer</a>
						<button class=\"btn\" href=\"#\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</button>") ?>



<?php $this->inlineScript()->captureStart();?>

$(".sidenav").affix();

$('body').scrollspy({target: '#sidebar', offset:120});

opsups('<?php echo $this->url('administration')?>');

<?php echo $this->notifications($this->messages); ?>

<?php $this->inlineScript()->captureEnd();?>