<?php $this->headScript()->appendFile($this->basePath() . '/assets/js/opsups.js')?>
<div class="container-fluid">
<div class="row">
<div class="col-md-12">
<p></p>
<div class="panel panel-default">
<div class="panel-heading">
	<h4 class="panel-title">Liste des superviseurs opérationnels</h4>
</div>
<div class="panel-body">
<table class="table table-striped sortable">
<thead>
	<tr>
		<th data-sort="int">id</th>
		<th data-sort="string" data-autosort="true">Nom</th>
		<th data-sort="string">Organisation</th>
		<th>Zone de qualification</th>
		<th><a class="btn btn-xs btn-primary" href="#opsup-container" data-toggle="modal" id="add-opsup">Ajouter</a></th>
	</tr>
</thead>

<tbody>
	<?php 
	foreach ($this->opsups as $opsup){
		echo '<tr>';
		echo '<td>'.$opsup->getId().'</td>';
		echo '<td>'.$opsup->getName().'</td>';
		echo '<td>'.$opsup->getOrganisation()->getName().'</td>';
		echo '<td>'.$opsup->getZone()->getName().'</td>';
		echo '<td>';
		echo "<a 
				title=\"Modifier\" 
				href=\"#opsup-container\" 
				class=\"mod-opsup\" 
				data-id=\"".$opsup->getId()."\" 
				data-name=\"".$opsup->getName()."\" 
				data-toggle=\"modal\"><span class=\"glyphicon glyphicon-pencil\"></span></a>  ";
		echo "<a 
				title=\"Supprimer\" 
				href=\"#confirm-delete-opsup\" 
				data-href=\"".$this->url('administration', array('controller'=>'opsups', 'action'=>'deleteopsup'), array('query'=>array('id'=>$opsup->getId())))."\" 
				class=\"delete-opsup\" 
				data-id=\"".$opsup->getId()."\" 
				data-name=\"".$opsup->getName()."\" 
				data-toggle=\"modal\"><span class=\"glyphicon glyphicon-trash\"></span> </a>";
		echo '</td>';
		echo '</tr>';
	}
	?>
</tbody>

</table>
</div>
</div>
</div>
</div>
</div>
<?php echo $this->modalWindow("opsup-container", "<h4 id=\"opsup-title\">Nouveau Chef OP</h4>", "", "<div id=\"opsup-form\"></div>")?>

<?php echo $this->modalwindow("confirm-delete-opsup",
						"<h4>Confirmer la suppression ?</h4>",
						"", 
						null, 
						"<p>Voulez-vous vraiment supprimer le chef OP <em><span id=\"opsup-name\"></span></em> de la liste ?</p>",
						"<a class=\"btn btn-danger\" id=\"delete-opsup-href\">Confirmer</a>
						<button class=\"btn\" href=\"#\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</button>") ?>	


<?php $this->inlineScript()->captureStart();?>

opsups('<?php echo $this->url('administration')?>');

<?php echo $this->notifications($this->messages); ?>

<?php $this->inlineScript()->captureEnd();?>