<div id="event">
<div id="loading">Chargement...</div>
<!-- formulaire createform.phtml récupéré via ajax -->
</div>
<?php $this->inlineScript()->captureStart();?>
$("#loading").ajaxStart(function(){
	$(this).show();})
	.ajaxStop(function(){
	$(this).hide();});
	
	
$("#create-link").on("click", function(){

	$("#event").load(
		'<?php echo $this->url('application', array('controller'=>'events', 'action'=>'createform'))?>',
		function(){
			//disable every accordion but the first
			$("a.accordion-toggle:gt(0)").addClass("disabled");
		}
	);
	
	loadModernizr();
});

//click on a predefined events
$(document).on("click", "a#predefined", function(){
	$("#Modèlesid").html('Modèle : '+$(this).parent().prev().html());
	var me = $(this);
	$.getJSON(
		'<?php echo $this->url('application', array('controller'=>'events', 'action'=>'getpredefinedvalues'))?>'+'?id='+me.data('id'),
		function(data){
			$("#name").val(data.defaultvalues.name);
			$("#punctual").prop('checked', data.defaultvalues.punctual);
			$("#punctual").trigger("change");
			$.each(data.customvalues, function(key, value){
				var elt = $("#"+key);
				if(elt.is("select")){
					$("#"+key+" option[value="+value+"]").prop('selected', true);
				} else if(elt.is('textarea')){
					elt.html(value);
				} else if(elt.is('input')){
					elt.prop('value', value);
				}
				//TODO les autres types de champs : 
			});
			//open hour accordion
			$("#Horairesid").trigger('click');
			//prepare actions
			$("#actionsTitle").removeClass("disabled");
	});
	//get actions
	$.getJSON(
		'<?php echo $this->url('application', array('controller'=>'events', 'action'=>'getactions'))?>'+'?id='+me.data('id'),
		function(data){
			var container = $("#inner-Ficheréflexe");
			container.html("");
			//save id of model
			var content = "<input name=\"modelid\" type=\"hidden\" value=\""+me.data('id')+"\" >";
			//then the table of actions
			content += '<table class="table table-hover"><tbody>';
			$.each(data, function(key, value){
				content += "<tr data-id=\""+key+"\">";
				content += "<td><span class=\"label label-"+value.impactstyle+"\">"+value.impactname+"</span></td>";
				content += "<td>"+value.name+"</td>";
				content += '</tr>';
			});						
			content += '</tbody></table>';
			container.html(content);
		}
	);
});

//choosing a category
$(document).on("change", "#root_categories", function(){
	$.post(
	'<?php echo $this->url('application',
							array('controller'=>'events', 'action'=>'createform'),
							array('query'=>array('type'=>'subcategories')) ) ?>'+'&id='+$(this).val(),
	function(data){
		$("#subcategories").html(data);
		if($("#root_categories option:selected").val() > 0) {
			$("#category_title").html('Catégories : '+$("#root_categories option:selected").text());
			$("#Horairesid").removeClass("disabled");
			$("#Descriptionid").removeClass("disabled");
			$('#subcategories option[value=-1]').prop('selected', true);
			$('#subcategories').trigger("change");
			$('#subcategories').prop('disabled',false);
		} else {
			$("#category_title").html('Catégories');
			$("#Horairesid").addClass("disabled");
			$("#Descriptionid").addClass("disabled");
			$('#subcategories option[value=-1]').prop('selected', true);
			$('#subcategories').trigger("change");
			$('#subcategories').prop('disabled',true);
		}
	});
	
	
});

//choosing a subcategory
$(document).on("change", "#subcategories", function(){
	$.post(
		'<?php echo $this->url('application',
							array('controller'=>'events', 'action'=>'createform'),
							array('query'=>array('type'=>'predefined_events')) ) ?>'+'&id='+$(this).val(),
		function(data){
			$("#predefined_events").html(data);
			if($("#subcategories option:selected").val() > 0) {
				$("#category_title").html('Catégories : '+$("#root_categories option:selected").text()+' > '+$("#subcategories option:selected").text());
				$("#Modèlesid").removeClass("disabled");
				$.post(
					'<?php echo $this->url('application',
							array('controller'=>'events', 'action'=>'createform'),
							array('query'=>array('type'=>'custom_fields')) ) ?>'+'&id='+$("#subcategories option:selected").val(),
					function(data){
						$("#custom_fields").html(data);
					}			
				);
				$('#Modèlesid').trigger('click');

			} else {
				//pas de sous-catégorie choisie, on supprime les champs spécifiques
				if($("#root_categories").val() > 0) {
					$("#category_title").html('Catégories : '+$("#root_categories option:selected").text());
				}
				
				$("#Modèlesid").html('Modèles').addClass("disabled");
				$("#actionsTitle").addClass("disabled");
				$("#custom_fields").html("");
				$("#inner-Ficheréflexe").html("");
			}
		}
	);
	
});

$(document).on("change", "#punctual", function(){
	$("#dateFin").prop('disabled',$(this).is(':checked')); 
});

<?php $this->inlineScript()->captureEnd();?>