<div id="event">
<div id="loading">Chargement...</div>
<!-- formulaire createform.phtml récupéré via ajax -->
</div>
<?php $this->inlineScript()->captureStart();?>
$("#loading").ajaxStart(function(){
	$(this).show();})
	.ajaxStop(function(){
	$(this).hide();});
	
	
$("#create-link").on("click", function(){

	$("#event").load(
		'<?php echo $this->url('application', array('controller'=>'events', 'action'=>'createform'))?>'
	);
	
	loadModernizr();
});

$(document).on("change", "#root_categories", function(){
	$.post(
	'<?php echo $this->url('application',
							array('controller'=>'events', 'action'=>'createform'),
							array('query'=>array('type'=>'subcategories')) ) ?>'+'&id='+$(this).val(),
	function(data){
		$("#subcategories").html(data);
	});
});

<?php $this->inlineScript()->captureEnd();?>