<?php
	if($this->type){
		switch ($this->type) {
			case 'subcategories':
				echo '<option value=\"-1\">Choisir la sous-catégorie</option>'; 
				foreach($this->values as $key => $value){?>
					<option value="<?php echo $key; ?>"><?php echo $value; ?></option>
	<?php 		};
				break;
			case 'predefined_events':
				echo '<table class="table table-hover" >';
				echo '<tbody>';
				foreach ($this->values as $key => $value){
					echo '<tr>';
					echo '<td>'.$key.'</td>';
					echo '<td>'.$value.'</td>';
					echo '<td><a href="#" class="btn btn-small">Utiliser</a></td>';
					echo '</tr>';
				}
				echo '</tbody>';
				echo '</table>';
				break;
			default:
				;
			break;
		}		
	} else {
//structure du formulaire
//rempli via jquery
	?>
		
	<?php
	$this->form->setAttributes(array(
				'action' => $this->url('application', array('controller'=>'events', 'action'=>'create')),
				'class' => 'form-horizontal'));
	$this->form->prepare();
	echo $this->form()->openTag($this->form);
	echo $this->formHidden($this->form->get('id'));
	?>
	
	<div class="accordion" id="form">
		<?php 
		$html = "<div class=\"control-group\">";
		$html .=  $this->formLabel($this->form->get('categories')->get('root_categories')->setLabelAttributes(array('class'=>'control-label')));
		$html .= "<div class=\"controls\">";
		$html .=  $this->formSelect($this->form->get('categories')->get('root_categories'));
		$html .= "</div>";
		$html .= "</div>";
		$html .= "<div class=\"control-group\">";
		$html .= $this->formLabel($this->form->get('categories')->get('subcategories')->setLabelAttributes(array('class'=>'control-label')));
		$html .= "<div class=\"controls\" id=\"form_subcategories\">";
		$html .= $this->formSelect($this->form->get('categories')->get('subcategories'));
		$html .= "</div>";
		$html .= "</div>";
		?>
		<?php echo $this->accordionGroup("Catégories", $html, array('in'=>true, 'inner-id'=>'category', 'data-parent'=>'form', 'title_id'=>'category_title'));	?>

		<?php echo $this->accordionGroup("Modèles", "", array('data-parent'=>'form', 'inner-id'=> 'predefined_events')); ?>
		
		<?php 
		$html = "<div class=\"control-group\">";
		$html .= $this->formLabel($this->form->get('punctual')->setLabelAttributes(array('class'=>'control-label')));
		$html .= "<div class=\"controls\">";
		$html .= $this->formCheckbox($this->form->get('punctual'));
		$html .= "</div>";
		$html .= "</div>";
	    $html .= "<div class=\"control-group\">";
		$html .= $this->formLabel($this->form->get('start_date')->setLabelAttributes(array('class'=>'control-label')));
		$html .= "<div class=\"controls\">";
		$html .= "<div class=\"input-prepend\">";
		$html .= "<span class=\"add-on\"><i class=\"icon-time\"></i></span>".$this->formDateTime($this->form->get('start_date'));
		$html .= "</div></div>";
		$html .= "</div>";
		$html .= "<div class=\"control-group\">";
		$html .= $this->formLabel($this->form->get('end_date')->setLabelAttributes(array('class'=>'control-label')));
		$html .= "<div class=\"controls\">";
		$html .= "<div class=\"input-prepend\">";
		$html .= "<span class=\"add-on\"><i class=\"icon-time\"></i></span>".$this->formDateTime($this->form->get('end_date'));
		$html .= "</div></div>";
		$html .= "</div>";
		
	
		echo $this->accordionGroup("Horaires",$html, array('data-parent'=>'form')); ?>
		
		<div class="accordion-group">
			<div class="accordion-heading">
				<a class="accordion-toggle" data-toggle="collapse" data-parent="#form" href="#accordion-others">
					Le reste
				</a>
			</div>
			<div class="accordion-body collapse" id="accordion-others">
				<div class="accordion-inner" id="others">
				
				

	<div class="control-group">
		<?php echo $this->formLabel($this->form->get('name')->setLabelAttributes(array('class'=>'control-label'))); ?>
		<div class="controls">
			<?php echo $this->formInput($this->form->get('name')); ?>
		</div>
	</div>
	
	<div class="control-group">
		<?php echo $this->formLabel($this->form->get('status')->setLabelAttributes(array('class'=>'control-label'))); ?>
		<div class="controls">
			<?php echo $this->formSelect($this->form->get('status')); ?>
		</div>
	</div>
	
	
	</div>
			</div>
		</div>
	
	</div>
	<div class="control-group">
		<div class="controls">
			<?php	echo $this->formSubmit($this->form->get('submit')); ?>
		</div>
	</div>	
	<?php echo $this->form()->closeTag(); ?>
<?php }?>
