<?php
	if($this->subform){
		$this->form->prepare();
		switch ($this->subform) {
			case 'subcategories':
				echo '<option value="-1">Choisir la sous-catégorie</option>'; 
				foreach($this->values as $key => $value){
					echo "<option value=\"".$key."\">".$value."</option>";
				};
				break;
			case 'predefined_events':
				if(empty($this->values)){
					echo 'Aucun modèle défini.';
				} else {
					echo '<table class="table table-hover" >';
					echo '<tbody>';
					foreach ($this->values as $key => $value){
						echo '<tr>';
						echo '<td>'.$key.'</td>';
						echo '<td>'.$value.'</td>';
						echo '<td><a id="predefined" data-id="'.$key.'" href="#" class="btn btn-small">Utiliser</a></td>';
						echo '</tr>';
					}
					echo '</tbody>';
					echo '</table>';
				}
				break;
			case 'custom_fields':
				foreach ($this->form->get('custom_fields')->getElements() as $element){
					if($element instanceof \Zend\Form\Element\Select){
						echo $this->controlGroup(
								$this->formLabel($element->setLabelAttributes(array('class'=>'control-label'))),
								$this->formSelect($element));
					} elseif ($element instanceof \Zend\Form\Element\Checkbox){
						echo $this->controlGroup(
								$this->formLabel($element->setLabelAttributes(array('class'=>'control-label'))),
								$this->formCheckbox($element));
					} elseif ($element instanceof \Zend\Form\Element\Text){
						echo $this->controlGroup(
								$this->formLabel($element->setLabelAttributes(array('class'=>'control-label'))),
								$this->formText($element));
					} elseif ($element instanceof \Zend\Form\Element\Textarea){
						echo $this->controlGroup(
							$this->formLabel($element->setLabelAttributes(array('class'=>'control-label'))),
							$this->formTextarea($element));
					} else {
						echo $this->formRow($element);
					}
				}
				break;
				;
			break;
		}		
	} else {
//structure du formulaire
//rempli via jquery
	?>
		
	<?php
	if($this->event){
		//form de modif
		echo "<h2>".$this->event->getName()."</h2>";
		$this->form->setAttributes(array(
		'action' => $this->url('application', array('controller'=>'events', 'action'=>'edit')),
		'class' => 'form-horizontal'));
	} else {
		//form de creation
		$this->form->setAttributes(array(
		'action' => $this->url('application', array('controller'=>'events', 'action'=>'create')),
		'class' => 'form-horizontal'));
	}
	
	$this->form->prepare();
	echo $this->form()->openTag($this->form);
	echo $this->formHidden($this->form->get('id'));
	?>
	
	<div class="accordion" id="form">
		<?php 
		//category and subcategory		
		$formSelectCat = $this->form->get('categories')->get('root_categories');
		$formSelectSubCat = $this->form->get('categories')->get('subcategories');
 		if($this->event){
			//Catégorie non modifiale si modification
			$formSelectCat->setAttribute('disabled',true);
 		}
		
		$html = $this->controlGroup(
					$this->formLabel($this->form->get('categories')->get('root_categories')->setLabelAttributes(array('class'=>'control-label'))),
					$this->formSelect($formSelectCat));
		$html .= $this->controlGroup(
					$this->formLabel($this->form->get('categories')->get('subcategories')->setLabelAttributes(array('class'=>'control-label'))),
					$this->formSelect($formSelectSubCat->setAttribute('disabled',true)),
					array('control_id'=>'form_categories'));		
		
		echo $this->accordionGroup("Catégories", $html, array('in'=>($this->event ? false : true), 'inner-id'=>'category', 'data-parent'=>'form', 'title_id'=>'category_title'));
 
		//Modèles uniquement si création
		if(!$this->event){
			echo $this->accordionGroup("Modèles", "Aucun modèle défini.", array('data-parent'=>'form', 'inner-id'=> 'predefined_events'));
		}
			
		$html = $this->controlGroup(
					$this->formLabel($this->form->get('punctual')->setLabelAttributes(array('class'=>'control-label'))),
					$this->formCheckbox($this->form->get('punctual')));
		$html .= $this->controlGroup(
					$this->formLabel($this->form->get('start_date')->setLabelAttributes(array('class'=>'control-label'))),
					"<div class=\"input-prepend\">".
					"<span class=\"add-on\"><i class=\"icon-time\"></i></span>".$this->formDateTime($this->form->get('start_date')).
					"</div>");
		$html .= $this->controlGroup(
					$this->formLabel($this->form->get('end_date')->setLabelAttributes(array('class'=>'control-label'))),
					"<div class=\"input-prepend\">".
					"<span class=\"add-on\"><i class=\"icon-time\"></i></span>".$this->formDateTime($this->form->get('end_date')).
					"</div>");
		
		echo $this->accordionGroup("Horaires",$html, array('data-parent'=>'form'));
		
		$html = $this->controlGroup(
					$this->formLabel($this->form->get('name')->setLabelAttributes(array('class'=>'control-label'))),
					$this->formInput($this->form->get('name')));
		$html .= $this->controlGroup(
				$this->formLabel($this->form->get('impact')->setLabelAttributes(array('class'=>'control-label'))),
				$this->formSelect($this->form->get('impact')));
		
		if($this->event){
			//TODO FACTORISER !
			foreach ($this->form->get('custom_fields')->getElements() as $element){
				if($element instanceof \Zend\Form\Element\Select){
					$html .= $this->controlGroup(
						$this->formLabel($element->setLabelAttributes(array('class'=>'control-label'))),
						$this->formSelect($element));
				} elseif ($element instanceof \Zend\Form\Element\Checkbox){
					$html .= $this->controlGroup(
						$this->formLabel($element->setLabelAttributes(array('class'=>'control-label'))),
						$this->formCheckbox($element));
				} elseif ($element instanceof \Zend\Form\Element\Text){
					$html .= $this->controlGroup(
						$this->formLabel($element->setLabelAttributes(array('class'=>'control-label'))),
						$this->formText($element));
				} elseif ($element instanceof \Zend\Form\Element\Textarea){
					$html .= $this->controlGroup(
						$this->formLabel($element->setLabelAttributes(array('class'=>'control-label'))),
						$this->formTextarea($element));
				} else {
					$html .= $this->formRow($element);
				}
			}
		} else {
			$html .= "<div id=\"custom_fields\"></div>";
		}	
		echo $this->accordionGroup("Description", $html, array('in' => ($this->event ? true : false), 'data-parent'=>'form'));
		
		echo $this->accordionGroup("Fiche réflexe", "", array('data-parent'=>'form', 'title_id'=>'actionsTitle'));
		
		?>

	<div class="control-group">
		<?php echo $this->formLabel($this->form->get('status')->setLabelAttributes(array('class'=>'control-label'))); ?>
		<div class="controls">
			<?php echo $this->formSelect($this->form->get('status')); ?>
		</div>
	</div>
	
	<div class="control-group">
		<div class="controls">
			<?php	
			if($this->event){
				echo $this->formSubmit($this->form->get('submit')->setAttribute('value', "Modifier"));
			} else {
				echo $this->formSubmit($this->form->get('submit'));
			}?>
		</div>
	</div>	
	<?php echo $this->form()->closeTag(); ?>
<?php }?>


