<?php
	if($this->error){
		echo "<div class=\"alert alert-error\">";
		echo $this->error."</div>";
		return false;
	}

	if($this->event && !$this->copy){
		//form de modif
		$this->form->setAttributes(array(
		'action' => $this->url('application', array('controller'=>'events', 'action'=>'modify', 'id'=>$this->event->getId())),
		'class' => 'form-horizontal'));
	} else {
		//form de creation
		$this->form->setAttributes(array(
		'action' => $this->url('application', array('controller'=>'events', 'action'=>'create')),
		'class' => 'form-horizontal'));
	}
	
	$this->form->prepare();
	echo $this->form()->openTag($this->form);
	echo $this->formHidden($this->form->get('id'));
	echo $this->formHidden($this->form->get('category'));
	?>
	
	<div class="accordion" id="form">
		<?php 
		//category and subcategory		
		$formSelectCat = $this->form->get('categories')->get('root_categories');
		$formSelectSubCat = $this->form->get('categories')->get('subcategories');
 		if($this->event){
			//Catégorie non modifiale si modification
			$formSelectCat->setAttribute('disabled',true);
 		}
		
		$html = $this->controlGroup(
					$this->formLabel($this->form->get('categories')->get('root_categories')->setLabelAttributes(array('class'=>'control-label'))),
					$this->formSelect($formSelectCat));
		$html .= $this->controlGroup(
					$this->formLabel($this->form->get('categories')->get('subcategories')->setLabelAttributes(array('class'=>'control-label'))),
					$this->formSelect($formSelectSubCat->setAttribute('disabled',true)),
					array('control_id'=>'form_categories'));		
		
		echo $this->accordionGroup("Catégories", $html, array('in'=>($this->event ? false : true), 'inner-id'=>'category', 'data-parent'=>'form', 'title_id'=>'category_title'));
 
		//Modèles uniquement si création
		if(!$this->event){
			echo $this->accordionGroup("Modèles", "Aucun modèle défini.", array('data-parent'=>'form', 'inner-id'=> 'predefined_events'));
		}
			
		$html = $this->controlGroup(
					$this->formLabel($this->form->get('punctual')->setLabelAttributes(array('class'=>'control-label'))),
					$this->formCheckbox($this->form->get('punctual')), array('class'=>'compact'));
		$html .= $this->controlGroup("", $this->formHidden($this->form->get('startdate')));
		
		$html .= $this->controlGroup(
				$this->formLabel($this->form->get('startdate')->setLabelAttributes(array('class'=>'control-label time-middle'))),
				$this->formDateTimeEnhanced("start"), array('class'=>'compact'));
		
		$formEndDate = $this->form->get('enddate');
		if($this->event){
			if($this->event->isPunctual()){
				$formEndDate->setAttribute('disabled', true);
			}
		}
		$html .= $this->controlGroup("",$this->formHidden($formEndDate));
		
		$html .= $this->controlGroup(
				$this->formLabel($this->form->get('enddate')->setLabelAttributes(array('class'=>'control-label time-middle'))),
				$this->formDateTimeEnhanced("end"), array('class'=>'compact'));
		
		echo $this->accordionGroup("Horaires",$html, array('data-parent'=>'form'));
		
		$html = $this->controlGroup(
				$this->formLabel($this->form->get('impact')->setLabelAttributes(array('class'=>'control-label'))),
				$this->formSelect($this->form->get('impact')));
		
		if($this->event){
			foreach ($this->form->get('custom_fields')->getElements() as $element){
				$html .= $this->customFieldGroup($element);
			}
		} else {
			$html .= "<div id=\"custom_fields\"></div>";
		}	
		echo $this->accordionGroup("Description", $html, array('in' => ($this->event ? true : false), 'data-parent'=>'form'));
		$titleclass="";		
		if($this->event){
			$files = $this->event->getFiles();
			if(count($files) > 0){
			//accéder aux fichiers
				$html = '<table class="table table-hover" >';
				$html .= '<tbody>';
				foreach ($files as $file){
					$html .= "<tr>";
					$html .= "<td>".($file->getReference() ? "#".$file->getReference() : "N/A")."</td>";
					$html .= "<td>".($file->getName() ? $file->getname() : $file->getFilename())."</td>";
					$html .= "<td><a href=\"".$this->basePath().$file->getPath()."\" rel=\"external\"><i class=\"icon-download\"></i></a></td>";
					$html .= "</tr>";
				}
				$html .= '</tbody>';
				$html .= '</table>';
			} else {
				$titleclass = "disabled";
				$html = "";
			}
			//TODO permettre la modif des fichiers si droits OK
		} else {
			$html = "<div id=\"file_list\">";
					
			$html .= "<div id=\"filefield_1\">";
			//ajouter des fichiers
			$file = $this->form->get('fichiers')->get('fichier1')->get('file1');
			$ref = $this->form->get('fichiers')->get('fichier1')->get('reference1');
			$name = $this->form->get('fichiers')->get('fichier1')->get('name1');
			$html .= $this->controlGroup(
					"<div class=\"control-label\"><a data-count=".$this->count." href=\"#\" class=\"removefile pull-left\">&nbsp;</a>".
					$this->formLabel($name).
					"</div>",
					$this->formInput($ref).
					$this->formInput($name)
			);
			$html .= $this->controlGroup(
						$this->formLabel($file->setLabelAttributes(array('class'=>'control-label'))),
						$this->formFile($file)
			);
			$html .= "</div>";
			
			$html .= "</div>";
			$html .= "<a id=\"addfile\" href=\"#\" class=\"btn btn-small pull-right\"><i class=\"icon-plus\"></i></a>";
		}
		
		echo $this->accordionGroup("Fichiers", $html, array('data-parent'=>'form', 'title_id'=>'filesTitle', 'title_class'=>$titleclass));
		
		
		$html = "";
		$actionsClass = "";
		if($this->event) {
			if($this->copy){
				echo "<input type=\"hidden\" name=\"fromeventid\" value=\"".$this->copy."\">";
			}
			$childs = $this->event->getChilds();
			if(count($childs) > 0){
				$html .= '<table class="table table-hover" >';
				$html .= '<tbody>';
				foreach ($childs as $child){
					$html .= "<tr data-id=\"".$child->getId()."\">";
					$html .= "<td><span class=\"label label-".$child->getImpact()->getStyle()."\">".$child->getImpact()->getName()."</span></td>";
					$html .= "<td>".$this->eventName($child)."</td>";
					if(!$this->copy){ //copie d'un évènement -> pas de modif de la ficher réflexe
						$html .= "<td><a class=\"fiche btn btn-small ".($child->getStatus()->isOpen()? "" : "active")."\" data-id=\"".$child->getId()."\">".($child->getStatus()->isOpen()? "A faire" : "Fait")."</a></td>";
					}
					$html .= '</tr>';
				}
				$html .= '</table>';
				$html .= '</tbody>';
			} else {
				$actionsClass="disabled";
			}
		}
		echo $this->accordionGroup("Fiche réflexe", $html, array('data-parent'=>'form', 'title_id'=>'actionsTitle', 'title_class'=>$actionsClass));
		
		?>

	<div class="control-group">
		<?php echo $this->formLabel($this->form->get('status')->setLabelAttributes(array('class'=>'control-label'))); ?>
		<div class="controls">
			<?php // if($this->event){
		//		echo $this->formSelect($this->form->get('status')->setAttribute('value', $this->event->getStatus()->getId()));
		//	} else {
				echo $this->formSelect($this->form->get('status')); 
		//	}?>
		</div>
	</div>
	
	<div class="control-group">
		<div class="controls">
			<?php	
			if($this->event){
				echo $this->formSubmit($this->form->get('submit')->setAttribute('value', ($this->copy ? "Ajouter" : "Modifier")));
			} else {
				echo $this->formSubmit($this->form->get('submit')->setAttribute('disabled', 'disabled'));
			}?>
			<a class="btn" id="cancel-form">Annuler</a>
		</div>
	</div>	
	<?php echo $this->form()->closeTag(); ?>


