<?php

	if($this->event && !$this->copy){
		//form de modif
		$this->form->setAttributes(array(
		'action' => $this->url('application', array('controller'=>'events', 'action'=>'modify', 'id'=>$this->event->getId())),
		'class' => 'form-horizontal'));
	} else {
		//form de creation
		$this->form->setAttributes(array(
		'action' => $this->url('application', array('controller'=>'events', 'action'=>'create')),
		'class' => 'form-horizontal'));
	}
	
	$this->form->prepare();
	echo $this->form()->openTag($this->form);
	echo $this->formHidden($this->form->get('id'));
	echo $this->formHidden($this->form->get('category'));
	?>
	
	<div class="accordion" id="form">
		<?php 
		//category and subcategory		
		$formSelectCat = $this->form->get('categories')->get('root_categories');
		$formSelectSubCat = $this->form->get('categories')->get('subcategories');
 		if($this->event || $this->model){
			//Catégorie non modifiale si modification
			$formSelectCat->setAttribute('disabled',true);
			$formSelectSubCat->setAttribute('disabled', true);
 		}
		
		$html = $this->controlGroup(
					$this->formLabel($this->form->get('categories')->get('root_categories')->setLabelAttributes(array('class'=>'control-label'))),
					$this->formSelect($formSelectCat));
		$html .= $this->controlGroup(
					$this->formLabel($this->form->get('categories')->get('subcategories')->setLabelAttributes(array('class'=>'control-label'))),
					$this->formSelect($formSelectSubCat),
					array('control_id'=>'form_categories'));		
		
		$catTitle = "Catégories";
		
		if($this->event) {
			$catTitle .= " : ".($this->event->getCategory()->getParent() ? 
									$this->event->getCategory()->getParent()->getName() . " > ".$this->event->getCategory()->getName() :
									$this->event->getCategory()->getName());
		}
		
		if($this->model) {
			$catTitle .= " : ".($this->model->getCategory()->getParent() ?
					$this->model->getCategory()->getParent()->getName() . " > ".$this->model->getCategory()->getName() :
					$this->model->getCategory()->getName());
		}
		
		echo $this->accordionGroup($catTitle, $html, array('in'=>($this->event ? false : true), 'inner-id'=>'category', 'data-parent'=>'form', 'title_id'=>'category_title', 'body-id' => "Catégories"));
 
		//Modèles uniquement si création
		if(!$this->event && !$this->model){
			echo $this->accordionGroup("Modèles", "Aucun modèle défini.", array('data-parent'=>'form', 'inner-id'=> 'predefined_events'));
		}
			
		$html = $this->controlGroup(
					$this->formLabel($this->form->get('punctual')->setLabelAttributes(array('class'=>'control-label'))),
					$this->formCheckbox($this->form->get('punctual')), array('class'=>'compact'));
		
		$html .= $this->controlGroup(
				$this->formLabel($this->form->get('startdate')->setLabelAttributes(array('class'=>'control-label time-middle'))),
				$this->formDateTimeEnhanced("start") . $this->formHidden($this->form->get('startdate')), array('class'=>'compact'));
		
		$formEndDate = $this->form->get('enddate');
		if($this->event){
			if($this->event->isPunctual()){
				$formEndDate->setAttribute('disabled', true);
			}
		}
		if($this->model){
			if($this->model->isPunctual()){
				$formEndDate->setAttribute('disabled', true);
			}
		}
		
		$html .= $this->controlGroup(
				$this->formLabel($this->form->get('enddate')->setLabelAttributes(array('class'=>'control-label time-middle'))),
				$this->formDateTimeEnhanced("end") . $this->formHidden($formEndDate), array('class'=>'compact'));
		
		echo $this->accordionGroup("Horaires",$html, array('data-parent'=>'form'));
		
		echo $this->formSelect($this->form->get('organisation')->setAttribute('class', 'unvisible'));
		
		$html = $this->controlGroup(
				$this->formLabel($this->form->get('impact')->setLabelAttributes(array('class'=>'control-label'))),
				$this->formSelect($this->form->get('impact')));
		if($this->form->has('zonefilters')){
			$html .= $this->controlGroup(
					$this->formLabel($this->form->get('zonefilters')->setLabelAttributes(array('class'=>'control-label'))),
					$this->formSelect($this->form->get('zonefilters')));
		}
		$html .= "<div id=\"custom_fields\">";
		if($this->event || $this->model){
			foreach ($this->form->get('custom_fields')->getElements() as $element){
				$html .= $this->customFieldGroup($element);
			}
		} 
		$html .= "</div>";
		
		echo $this->accordionGroup("Description", $html, array('in' => ($this->event ? true : false), 'data-parent'=>'form'));
		
		$titleclass="";	
		$html = "";	
		
		$mod = !$this->event || ($this->event && ($this->isGranted('events.modify') || ($this->zfcUserIdentity() && $this->event->getAuthor()->getId() == $this->zfcUserIdentity()->getId())));

		$html .= '<table class="table table-hover" id="alarm-table">';
		if($this->event){
			foreach($this->event->getChildren() as $child) {
				if($child->getCategory() instanceof AlarmCategory){
					$html .= '<tr data-id="'.$child->getId().'">';
					$html .= '<tr></tr>';
					$html .= '<td>'.$this->eventname($child).'</td>';
					$html .= "</tr>";
				}
			}
		}
		$html .= '</table>';
		if($mod){
			$html .= "<a id=\"addalarm\" href=\"#add-alarm\" data-toggle=\"modal\" class=\"btn btn-small pull-right\"><i class=\"icon-plus\"></i></a>";
		}
		
		echo $this->accordionGroup("Alarmes", $html, array('data-parent'=>'form'));
		
		$titleclass="";	
		$html = "";	
		$countfiles = 0;
		$mod = false;
                $html = '<table class="table table-hover" id="file-table">';
		$html .= '<tbody>';
		if($this->event){
			$files = $this->event->getFiles();
			
			if($this->zfcUserIdentity()){
				$mod = ($this->event->getAuthor()->getId() == $this->zfcUserIdentity()->getId()) || ($this->isGranted('events.modify'));
			}
                        
			if(count($files) > 0){
				$countfiles = count($files);
				//accéder aux fichiers
				
				foreach ($files as $file){
					$html .= "<tr id=\"file_".$file->getId()."\">";
					$html .= "<td>".($file->getReference() ? "#".$file->getReference() : "N/A")."</td>";
					$html .= "<td><a href=\"".$this->basePath().$file->getPath()."\" rel=\"external\">".
								($file->getName() ? $file->getname() : $file->getFilename())."</a></td>";
					$html .= "<td>";
					$html .= "<a href=\"".$this->basePath().$file->getPath()."\" rel=\"external\"><i class=\"icon-download\"></i></a>";
					$html .= "</td>";
					if($mod){
						$html .= "<td>";
						//TODO
						//$html .= "<a href=\"#\"><i class=\"icon-pencil mod-file\"></i></a> ";
						$html .= "<a href=\"#confirm-delete-file\"
									class=\"delete-file\"
									data-href=\"".$this->url('application', 
															array('controller'=>'events', 'action' => 'deletefile'),
															array('query'=>array('id'=>$file->getId(), 'eventid' => $event->getId())))."\"
									data-id=\"".$file->getId()."\"
									data-name=\"".($file->getName() ? $file->getname() : $file->getFilename())."\"
									data-toggle=\"modal\"
									><i class=\"icon-trash\"></i></a>";
						$html .= "</td>";
					}
					$html .= "</tr>";
				}
				
			} 
                        
			if(!$mod && count($files) == 0){
				$titleclass = "disabled";
				$html = "";
			}
		}
                $html .= '</tbody>';
		$html .= '</table>';
		//ajout de fichier si nouvel evt ou mod avec droits ok
		if(!$this->event || ($this->event && $mod)){
			$html .= "<a id=\"addfile\" href=\"#add-file\" data-toggle=\"modal\" class=\"btn btn-small pull-right\"><i class=\"icon-plus\"></i></a>";
		}
		
		echo $this->accordionGroup("Fichiers", $html, array('data-parent'=>'form', 'title_id'=>'filesTitle', 'title_class'=>$titleclass));
		
		
		$html = "";
		$actionsClass = "";
		if($this->event || $this->model) {
			if($this->copy){
				echo "<input type=\"hidden\" name=\"fromeventid\" value=\"".$this->copy."\">";
			}
			$children = null;
			if($this->event){
				$children = $this->event->getChildren();
			} else if ($this->model){
				$children = $this->model->getChildren();
			}
			if(count($children) > 0){
				$html .= '<table class="table table-hover" >';
				$html .= '<tbody>';
                                foreach ($children as $child){
                                    if($child->getCategory() instanceof Application\Entity\ActionCategory){
					$html .= "<tr data-id=\"".$child->getId()."\">";
					$html .= "<td><span class=\"label label-".$child->getImpact()->getStyle()."\">".$child->getImpact()->getName()."</span></td>";
					$html .= "<td>".$this->eventName($child)."</td>";
					if(!$this->copy && !$this->model){ //copie d'un évènement -> pas de modif de la ficher réflexe
						$html .= "<td><a class=\"fiche btn btn-small ".($child->getStatus()->isOpen()? "" : "active")."\" data-id=\"".$child->getId()."\">".($child->getStatus()->isOpen()? "A faire" : "Fait")."</a></td>";
					}
					$html .= '</tr>';
                                    }
                                }
                                $html .= '</tbody>';
				$html .= '</table>';
			} else {
				$actionsClass="disabled";
			}
		}
		echo $this->accordionGroup("Fiche réflexe", $html, array('data-parent'=>'form', 'title_id'=>'actionsTitle', 'title_class'=>$actionsClass));
		
		?>

	<div class="control-group">
		<?php echo $this->formLabel($this->form->get('status')->setLabelAttributes(array('class'=>'control-label'))); ?>
		<div class="controls">
			<?php 
			if($this->isGranted('events.status')) {
				echo $this->formSelect($this->form->get('status'));
			} else {
				echo $this->formSelect($this->form->get('status')->setAttribute('disabled', 'disabled'));
			} 
			?>
		</div>
	</div>
	
	<div class="control-group">
		<div class="controls">
                    <div style="display:inline-block; position:relative;">
			<?php	
			if($this->event || $this->model){
				echo $this->formSubmit($this->form->get('submit')->setAttribute('value', (($this->copy || $this->model) ? "Ajouter" : "Enregistrer")));
			} else {
				echo $this->formSubmit($this->form->get('submit')->setAttribute('disabled', 'disabled'));
			}?>
                        <div id="hack-tooltip" style="display:none; position:absolute; left:0; right: 0; top: 0; bottom: 0;"></div>
                    </div>
			<a class="btn" id="cancel-form">Annuler</a>
		</div>
	</div>	
	<?php echo $this->form()->closeTag(); ?>
