<div id="close-button" data-id="<?php echo $event->getId(); ?>">
<a href="#" id="close-panel"><span class="pull-right"><span class="glyphicon glyphicon-remove"></span></span></a>
</div>
<?php if ($this->event) : ?>

<div class="panel-group">
    
<div class="panel panel-success">
    <div class="panel-heading">
        <h4 class="panel-title">Résumé<div class="panel-badge"><span class="glyphicon glyphicon-chevron-up"></span></div></h4>
    </div>
    <div class="panel-collapse collapse in">
    	<div class="panel-body">
    	<?php echo $this->partial('events/summary.phtml');?>
    	</div>
    </div>
</div>
    
    <?php
    $count = 0;
    foreach ($this->event->getChildren() as $child) {
        if ($child->getCategory() instanceof Application\Entity\ActionCategory) {
            $count++;
        }
    }
    ?>
    <?php if ($count > 0) : ?>

        <div class="panel panel-info">
            <div class="panel-heading">
                <h4 class="panel-title" style="text-overflow:ellipsis">Fiche réflexe <?php echo $this->eventName($this->event); ?>
                <div class="panel-badge"><span class="badge"><?php echo $count; ?></span> <span class="glyphicon glyphicon-chevron-up"></span></h4>
            </div>
            <div class="panel-collapse collapse in">
            	<div class="panel-body" id="list-actions" data-parentid="<?php echo $this->event->getId(); ?>">
                <?php echo $this->partial('events/actions.phtml', array('actions' => $this->actions, 'compact' => true)); ?>
                </div>
            </div>
        </div>

    <?php endif; ?>

<?php if(count($this->event->getFiles())>0) : ?>
<div class="panel panel-info">
    <div class="panel-heading" id="files-panel">
        <h4 class="panel-title">Fichiers
        <div class="panel-badge"><span class="badge"><?php echo count($this->event->getFiles()) ?></span> <span class="glyphicon glyphicon-chevron-down"></span></h4>
    </div>
    <div class="panel-collapse collapse">
    <div class="panel-body">
        <table class="table table-hover">
            <tbody>
                <?php
                foreach ($this->event->getFiles() as $file) {
                    echo "<tr id=\"file_".$file->getId()."\">";
                    echo "<td>".($file->getReference() ? "#".$file->getReference() : "N/A")."</td>";
                    echo "<td style=\"word-wrap: break-word; max-width: 200px;\"><a href=\"".$this->basePath().$file->getPath()."\" rel=\"external\">".
				($file->getName() ? $file->getname() : $file->getFilename())."</a></td>";
                    echo "<td><a href=\"".$this->basePath().$file->getPath()."\" rel=\"external\"><span class=\"glyphicon glyphicon-download\"></span></a></td>";
                    echo "</tr>";
                }
                ?>
            </tbody>
        </table>
        </div>
    </div>
</div>
<?php endif; ?>

<div class="panel panel-info">
    <div class="panel-heading">
        <h4 class="panel-title">Historique
        <div class="panel-badge"><span class="badge"><?php echo count($this->history) ?></span> <span class="glyphicon glyphicon-chevron-down"></span></div></h4>
    </div>
    <div class="panel-collapse collapse">
    <div class="panel-body" id="history">
        <?php echo $this->partial('events/gethistory.phtml', array('history' => $this->history)); ?>
    </div>
    </div>
</div>

<div class="panel panel-info">
    <div class="panel-heading">
        <h4 class="panel-title">Notes
        <div class="panel-badge"><span class="badge"><?php echo count($this->event->getUpdates()) ?></span> <span class="glyphicon glyphicon-chevron-<?php echo (($this->event->getUpdates() && count($this->event->getUpdates()) > 0) ? 'up' : 'down')?>"></span></h4>
    </div>
    <div class="panel-collapse collapse <?php echo (($this->event->getUpdates() && count($this->event->getUpdates()) > 0) ? 'in' : '')?>">
        <div class="panel-body">
        <div id="updates">
        <?php echo $this->partial('events/updates.phtml', array('updates' => $this->event->getUpdates())); ?>
        </div>
        <?php if($this->isGranted('events.write')) :?>
        <div class="block-controls">
            <form data-id="<?php echo $this->event->getId();?>" id="add-note-fiche" action="<?php echo $this->url('application', array('controller' => 'events', 'action' => 'addnote'))?>">
            <textarea name="new-update" placeholder="Ajouter une note."></textarea>
            <input type="submit" class="btn btn-sm btn-primary pull-right" value="Ajouter note"></input>
            </form>
        </div>
        <?php endif; ?>
        
        </div>
    </div>
</div>

</div>
<?php endif; ?>