<?php
if ($this->fiche) {
    $count = 0;
    foreach ($this->fiche->getChildren() as $child) {
        if ($child->getCategory() instanceof Application\Entity\ActionCategory) {
            $count++;
        }
    }
    ?>
    <?php if ($count > 0) : ?>

        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">Fiche réflexe <?php echo $this->eventName($this->fiche); ?></div>
            </div>
            <div class="block-content collapse in">
                <?php
                echo "<table class=\"table\">";
                echo "<tbody>";
                foreach ($this->fiche->getChildren() as $child) {
                    if ($child->getCategory() instanceof Application\Entity\ActionCategory) {
                        echo "<tr data-id=\"" . $child->getId() . "\">";
                        echo "<td>" . $this->eventName($child) . "</td>";
                        echo '<td><a class="fiche btn btn-small ' . ($child->getStatus()->isOpen() ? "" : "active") . '" data-id="' . $child->getId() . '">' . ($child->getStatus()->isOpen() ? "A faire" : "Fait") . '</a></td>';
                        echo "</tr>";
                    }
                }
                echo "</tbody></table>";
                ?>
            </div>
        </div>

    <?php endif; ?>
    <?php
}
?>



<div class="block">
    <div class="navbar navbar-inner block-header">
        <div class="muted pull-left">Historique</div>
    </div>
    <div class="block-content collapse in">
        <?php echo $this->partial('events/gethistory.phtml'); ?>
    </div>
</div>






