<a href="#" id="close-panel"><span class="pull-right" style="margin-right:-4px; margin-top:-4px; "><i class="icon-chevron-left icon-grey"></i></span></a>

<?php if ($this->event) : ?>
    
<div class="block">
    <div class="navbar navbar-inner block-header">
        <div class="muted pull-left">Résumé</div>
        <div class="pull-right"><i class="icon-chevron-up icon-grey"></i></div>
    </div>
    <div class="block-content collapse in">
        <?php echo $this->partial('events/summary.phtml');?>
    </div>
</div>
    
    <?php
    $count = 0;
    foreach ($this->event->getChildren() as $child) {
        if ($child->getCategory() instanceof Application\Entity\ActionCategory) {
            $count++;
        }
    }
    ?>
    <?php if ($count > 0) : ?>

        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">Fiche réflexe <?php echo $this->eventName($this->event); ?></div>
                <div class="pull-right"><span class="badge"><?php echo $count; ?></span> <i class="icon-chevron-up icon-grey"></i></div>
            </div>
            <div class="block-content collapse in">
                <?php
                echo "<table class=\"table\">";
                echo "<tbody>";
                foreach ($this->event->getChildren() as $child) {
                    if ($child->getCategory() instanceof Application\Entity\ActionCategory) {
                        echo "<tr data-id=\"" . $child->getId() . "\">";
                        echo "<td>" . $this->eventName($child) . "</td>";
                        echo '<td><a class="fiche btn btn-small ' . ($child->getStatus()->isOpen() ? "" : "active") . '" data-eventid="'.$this->event->getId().'" data-id="' . $child->getId() . '">' . ($child->getStatus()->isOpen() ? "A faire" : "Fait") . '</a></td>';
                        echo "</tr>";
                    }
                }
                echo "</tbody></table>";
                ?>
            </div>
        </div>

    <?php endif; ?>


<div class="block">
    <div class="navbar navbar-inner block-header">
        <div class="muted pull-left">Notes</div>
        <div class="pull-right"><span class="badge"><?php echo count($this->event->getUpdates()) ?></span> <i class="icon-chevron-<?php echo (($this->event->getUpdates() && count($this->event->getUpdates()) > 0) ? 'up' : 'down')?> icon-grey"></i></div>
    </div>
    <div class="block-content collapse in" id="updates" <?php echo (($this->event->getUpdates() && count($this->event->getUpdates()) > 0) ? '' : 'style="display:none"')?>>
        <?php echo $this->partial('events/updates.phtml', array('updates' => $this->event->getUpdates())); ?>
    </div>
</div>

<?php if(count($this->event->getFiles())>0) : ?>
<div class="block">
    <div class="navbar navbar-inner block-header">
        <div class="muted pull-left">Fichiers</div>
        <div class="pull-right"><span class="badge"><?php echo count($this->event->getFiles()) ?></span> <i class="icon-chevron-down icon-grey"></i></div>
    </div>
    <div class="block-content collapse in" id="updates" style="display:none">
        <table class="table table-hover">
            <tbody>
                <?php
                foreach ($this->event->getFiles() as $file) {
                    echo "<tr id=\"file_".$file->getId()."\">";
                    echo "<td>".($file->getReference() ? "#".$file->getReference() : "N/A")."</td>";
                    echo "<td><a href=\"".$this->basePath().$file->getPath()."\" rel=\"external\">".
				($file->getName() ? $file->getname() : $file->getFilename())."</a></td>";
                    echo "<td><a href=\"".$this->basePath().$file->getPath()."\" rel=\"external\"><i class=\"icon-download\"></i></a></td>";
                    echo "</tr>";
                }
                ?>
            </tbody>
        </table>
    </div>
</div>
<?php endif; ?>

<div class="block">
    <div class="navbar navbar-inner block-header">
        <div class="muted pull-left">Historique</div>
        <div class="pull-right"><i class="icon-chevron-down icon-grey"></i></div>
    </div>
    <div class="block-content collapse in" id="history" style="display:none;">
        <?php echo $this->partial('events/gethistory.phtml'); ?>
    </div>
</div>

<div class="block-controls">
    <form data-id="<?php echo $this->event->getId();?>" id="add-note" action="<?php echo $this->url('application', array('controller' => 'events', 'action' => 'addnote'))?>">
    <textarea name="new-update" placeholder="Ajouter une note."></textarea>
    <input type="submit" class="btn btn-small btn-primary pull-right" value="Ajouter note"></input>
    </form>
</div>

<?php else : ?>

<?php endif; ?>





