<?php $this->headScript()->appendFile($this->basePath() . '/assets/js/timeline.js');
$this->headScript()->appendFile($this->basePath() . '/js/jquery.form.js');
$this->headScript()->appendFile($this->basePath() . '/assets/js/fileupload.js');
$this->headScript()->appendFile($this->basePath() . '/assets/js/search.js');
?>

<?php if($this->isGranted('events.create') || $this->isGranted('events.write')):?>
        <div id="create-evt" class="popover fade bottom in">
                <div class="arrow"></div>
                <div class="loading"></div>
                <h3 class="popover-title" id="form-title">Nouvel évènement</h3>
                <div id="event">
                        <div>Chargement...</div>
                        <!-- formulaire createform.phtml récupéré via ajax -->
                </div>
        </div>
        <div id="suggestions-container"></div>
<?php endif; ?>

<div id="search-results" class="popover fade bottom in">
        <div class="arrow"></div>
        <div class="loading"></div>
        <div id="results">
                <div>Chargement...</div>
        </div>
</div>

<div id="fiche" class="panel panel-fixed">
</div>

<div id="timeline">
    
    <div id="calendar">
    <p><i class="icon-backward"></i> <input id="date" type="text" class="date input-small"></input> <i class="icon-forward"></i></p>
    </div>
    
</div>


<?php 
//modal windows to modify or delete file
echo $this->modalwindow("confirm-delete-file",
					"<h3>Confirmer la suppression du fichier ?</h3>",
					"",
					null,
					"<p>Voulez-vous vraiment supprimer le fichier <em><span id=\"file_name\"></span></em> ?</p>",
					"<a class=\"btn btn-danger\" id=\"delete-file-href\">Confirmer</a>
					<a class=\"btn\" href=\"#\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</a>");
?>

<?php

echo $this->modalwindow(
    "add-file",
    "<h3>Ajout d'un fichier</h3>",
    "",
    "<div id=\"file-upload-form\"></div>"
    );

echo $this->modalwindow("add-alarm",
	"<h3>Ajout d'une alarme</h3>",
	"",
	"<div id=\"alarm-form\"></div>");
    
?>

<?php $this->inlineScript()->captureStart();?>

$('#timeline').css('height', $(window).height()-82+'px');
//init timeline
timeline.conf($('#timeline'), '<?php echo $this->url('application', array('controller' => 'events', ''))?>');
	
//init form
form('<?php echo $this->url('application');?>');

fileupload('<?php echo $this->url('application')?>');

//search
search('<?php echo $this->url('application', array('controller'=>'events'));?>');

<?php $this->inlineScript()->captureEnd();?>