<?php 

$this->form->prepare();
switch ($this->part) {
	case 'subcategories':
		echo '<option value="-1">Choisir la sous-catégorie</option>';
		foreach($this->values as $key => $value){
			echo "<option value=\"".$key."\">".$value."</option>";
		};
		break;
	case 'predefined_events':
		if(empty($this->values)){
			echo 'Aucun modèle défini.';
		} else {
			echo '<table class="table table-hover" >';
			echo '<tbody>';
			foreach ($this->values as $key => $value){
				echo '<tr>';
				echo '<td>'.$key.'</td>';
				echo '<td>'.$value.'</td>';
				echo '<td><a class="predefined btn btn-small btn-primary" data-id="'.$key.'" href="#">Utiliser</a></td>';
				echo '</tr>';
			}
			echo '</tbody>';
			echo '</table>';
		}
		break;
	case 'custom_fields':
		foreach ($this->form->get('custom_fields')->getElements() as $element){
			echo $this->customFieldGroup($element);
		}
		break;
	case 'file_field':
		echo "<div id=\"filefield_".$this->count."\">";
		$file = $this->form->get('fichiers')->get('fichier'.$this->count)->get('file'.$this->count);
			
		$name = $this->form->get('fichiers')->get('fichier'.$this->count)->get('name'.$this->count);
		echo $this->controlGroup(
				$this->formLabel($name->setLabelAttributes(array('class'=>'control-label'))),
				$this->formInput($name).
				"<a data-count=".$this->count." href=\"#\" class=\"removefile pull-right\"><i class=\"icon-trash\"></i></a>"
		);
		echo $this->controlGroup(
				$this->formLabel($file->setLabelAttributes(array('class'=>'control-label'))),
				$this->formFile($file)
		);
		echo "</div>";
		break;
	default:
		break;
}