<?php
$this->form->prepare();
switch ($this->part) {
    case 'subcategories':
        echo '<option value="-1">Autre</option>';
        foreach ($this->values as $key => $value) {
            echo "<option value=\"" . $key . "\">" . $value . "</option>";
        }
        ;
        break;
    case 'predefined_events':
        if (empty($this->values)) {
            echo '<div class="col-sm-10">';
            echo '<p>Aucun modèle défini.</p>';
            echo '</div>';
        } else {
            echo '<div class="col-md-5">';
            
            $count = count($values);
            $i = 1;
            $separated = false;
            foreach ($this->values as $key => $value) {
                echo '<div class="container-fluid">';
                    echo '<div class="col-sm-2">';
                        echo '<div class="round round-lg grey"><i class="mdi-content-content-paste"></i></div>';
                    echo '</div>';
                    echo '<div class="col-sm-7">';
                    echo '<p>'.$value.'</p>';
                    echo '</div>';
                    echo '<div class="col-sm-3">';
                    echo '<span class="pull-right"><button class="btn btn-sm btn-primary">Utiliser</button></span>';
                    echo ' </div>';
                echo '</div>';
                if ($i >= $count / 2 && ! $separated) {
                    echo '</div>';
                    echo '<div class="col-md-5">';
                    $separated = true;
                }
                $i ++;
            }
            
            echo '</div>';
            
            // echo '<table class="table table-hover" >';
            // echo '<tbody>';
            // foreach ($this->values as $key => $value){
            // echo '<tr>';
            // //echo '<td>'.$key.'</td>';
            // echo '<td>'.$value.'</td>';
            // echo '<td><a class="predefined btn btn-small btn-primary" data-id="'.$key.'" href="#">Utiliser</a></td>';
            // echo '</tr>';
            // }
            // echo '</tbody>';
            // echo '</table>';
        }
        break;
    case 'custom_fields':
        foreach ($this->form->get('custom_fields')->getElements() as $element) {
            echo $this->customFieldGroup($element);
        }
        break;
    default:
        break;
}