<?php

if($this->updates){
	
	$history = $this->history;
        $formatter = \IntlDateFormatter::create(\Locale::getDefault(),
            \IntlDateFormatter::FULL,
            \IntlDateFormatter::FULL,
            \DateTimeZone::UTC,
            \IntlDateFormatter::GREGORIAN,
            'dd LLL, HH:mm');
	if (count($this->updates) > 0) {
            echo '<dl>';
            foreach ($this->updates as $update) {
                echo '<dt>' . $formatter->format($update->getCreatedOn()) . ' UTC</dt>';
                echo '<dd>';
                    echo nl2br($update->getText());
                echo '</dd>';
        }
        echo '</dl>';
    } else {
        echo "<p>Aucune note à afficher.</p>";
    }
} else {
    echo "<p>Aucune note à afficher.</p>";
}


