

<?php 
$this->form->setAttribute('action', $this->url('administration', array('controller'=>'models', 'action'=>'validatealarm')));
$this->form->setAttribute('class', 'form-horizontal');
$this->form->prepare();

echo $this->form()->openTag($this->form);
?>
<div class="modal-body">
<?php


echo $this->formHidden($this->form->get('id'));

echo $this->formHidden($this->form->get('parent'));

echo $this->formHidden($this->form->get('punctual'));

echo $this->formHidden($this->form->get('category'));

echo $this->formHidden($this->form->get('organisation'));

echo $this->formHidden($this->form->get('impact'));

echo $this->formHidden($this->form->get('programmed')->setAttribute('value', false));

echo $this->formHidden($this->form->get('listable')->setAttribute('value', false));

echo $this->formHidden($this->form->get('searchable')->setAttribute('value', false));

echo $this->formHidden($this->form->get('forceroot')->setAttribute('value', false));

foreach ($this->form->get('custom_fields')->getElements() as $element){
	echo $this->controlgroup($element);
}

?>
</div>
<div class="modal-footer">
<?php echo $this->formSubmit($this->form->get('submit')); ?>
<a id="cancel-form" class="btn" href="#" data-dismiss="modal" aria-hidden="true">Annuler</a>
</div>
<?php 
echo $this->form()->closeTag();
?>
