

<?php 
$this->form->setAttribute('action', $this->url('administration', array('controller'=>'models', 'action'=>'save')));
$this->form->setAttribute('class', 'form-horizontal');
$this->form->prepare();

echo $this->form()->openTag($this->form);
?>
<div class="modal-body">
<?php


echo $this->formHidden($this->form->get('id'));

echo $this->controlGroup($this->form->get('category'));

//name only usefull for a model, not for actions
if(!$this->action){
	echo $this->controlGroup($this->form->get('name'));
}
echo $this->controlGroup($this->form->get('impact'));

if(!$this->action){// une action est ponctuelle, non listable et non recherchable -> on simplifie le formulaire
	echo $this->controlGroup($this->form->get('punctual'));

	echo $this->controlGroup($this->form->get('listable'));

	echo $this->controlGroup($this->form->get('searchable'));
	
	echo $this->controlGroup($this->form->get('programmed'));

	echo $this->controlGroup($this->form->get('forceroot'));
	
	echo $this->controlGroup($this->form->get('organisation'));
	
	echo $this->controlGroup($this->form->get('zonefilters'));

	echo $this->controlGroup($this->form->get('duration'));
	
} else {
	echo $this->formHidden($this->form->get('punctual')->setAttribute('value', true));

	echo $this->formHidden($this->form->get('listable')->setAttribute('value', false));

	echo $this->formHidden($this->form->get('searchable')->setAttribute('value', false));
	
	echo $this->formHidden($this->form->get('programmed')->setAttribute('value', false));
    
    echo $this->formHidden($this->form->get('forceroot')->setAttribute('value', false));
	
	echo $this->formHidden($this->form->get('organisation'));
	
	echo $this->formHidden($this->form->get('parent'));

	echo $this->formHidden($this->form->get('duration'));
}
?>

<div class="custom-fields">
<?php 
//champs spécifiques

if($this->form->has('custom_fields')){
	echo "<h4>Valeurs des champs spécifiques :</h4>";
	foreach ($this->form->get('custom_fields')->getElements() as $element){
		echo $this->controlGroup($element);
	}
}
?>
</div>

<?php if(!$this->action)//action form cannot have files, alarms or actions
{  ?>    
<div id="model-files">
    <h4 style="display: inline;">Fichiers</h4>
    <a class="pull-right btn btn-xs btn-primary" href="#add-file" data-toggle="modal" id="addfile">Ajouter fichier</a>
    <table class="table table-hover" id="file-table">
        <tbody>
            <?php
            if($this->files){
		$countfiles = count($this->files);
		foreach ($this->files as $file){
			echo '<tr id="file_'.$file->getId().'">';
			echo '<td>'.($file->getReference() ? '#'.$file->getReference() : "N/A").'</td>';
			echo '<td><a href="'.$this->basePath().$file->getPath().'" rel="external">'
				. ($file->getName() ? $file->getName() : $file->getFilename()) . '</a></td>';
			echo '<td><a href="'.$this->basePath().$file->getPath().'" rel="external"><span class="glyphicon glyphicon-download"></span></a></td>';
			echo '<td><a class="delete-file" href="#confirm-delete-file" '
				. 'data-id="'.$file->getId().'" '
				. 'data-name="'.($file->getName() ? $file->getName() : $file->getFilename()).'" '
				. 'data-toggle="modal" '
				. 'data-href="'.$this->url('administration', array('controller' => 'models', 'action' => 'deletefile'), 
										array('query' => array('id' => $file->getId(), 'modelid' => $this->form->get('id')->getValue()))).'">'
				. '<span class="glyphicon glyphicon-trash"></span></a></td>';
			echo '</tr>';
		}
            }
            ?>
        </tbody>
    </table>
    
</div>

<div id="alerts">
	<h4 style="display:inline;">Mémos</h4>
	<a class="pull-right btn btn-xs btn-primary" href="#add-alert" data-toggle="modal" id="addalert">Ajouter mémo</a>
	<table class="table table-hover alert-table">
		<tbody>
		<?php
                $countalarms = 0;
		if($this->childs){
			foreach($this->childs as $alarm){
				if($alarm->getCategory() instanceof Application\Entity\AlarmCategory){
                                    $deltabegin = "";
                                    $deltaend = "";
                                    foreach ($alarm->getCustomFieldsValues() as $value){
                                        if($value->getCustomField()->getId() == $alarm->getCategory()->getDeltaBeginField()->getId()){
                                            $deltabegin = $value->getValue();
                                        }
                                        if($value->getCustomField()->getId() == $alarm->getCategory()->getDeltaEndField()->getId()){
                                            $deltaend = $value->getValue();
                                        }
                                    }
                                    $countalarms++;
                                    echo '<tr id="alarm-'.$alarm->getId().'">';
                                    echo '<td data-toggle="tooltip" title="Déclenchement du mémo x minutes après le début de l\'évènement">'.(strlen($deltabegin) > 0 ? $deltabegin : "0").' min</td>';
                                    echo '<td data-toggle="tooltip" title="Déclenchement du mémo x minutes après la fin de l\'évènement">'.(strlen($deltaend) > 0 ? $deltaend : "0").' min</td>';
                                    echo '<td>'.$this->eventName($alarm).'</td>';
                                    echo '<td>';
									echo '<a href="#add-alert" data-toggle="modal" class="mod-alert" data-id="'.$alarm->getId().'"><span class="glyphicon glyphicon-pencil"></span></a> ';
									echo '<a href="#" class="delete-alarm" data-id="'.$alarm->getId().'"><span class="glyphicon glyphicon-trash"></span></a>';
									echo '</td>';
                                    echo '</tr>';
				}
			}
		}
		?>
		</tbody>
	</table>
</div>

<?php if($this->form->get('id')->getValue()){?>
<div>
<h4 style="display:inline;">Fiche réflexe</h4>

<a href="#action-container" id="new-action" data-parent="<?php echo $this->form->get('id')->getValue()?>" data-toggle="modal" class="pull-right btn btn-xs btn-primary">Nouvelle action</a>
</div>
<?php } else {?>
<div class="well">Enregistrer le modèle pour configurer la fiche réflexe.</div>
<?php }?>
<table class="table" id="actions-table">
<?php 
if($this->childs) {
	$i = 0;
	$total = count($this->childs) - $countalarms;
	foreach ($this->childs as $child){
            if($child->getCategory() instanceof Application\Entity\ActionCategory){
		$i++;
		echo '<tr id="'.$child->getId().'">';
			echo '<td>'.$this->eventName($child).'</td>';
			echo '<td>'.$this->impact($child->getImpact()).'</td>';
			echo '<td><a 
						href="'.$this->url('administration', array('controller'=>'models', 'action'=>'down'), array('query'=>array('id'=>$child->getId()))).'"'. 
						'class="down'.($i == $total ? ' disabled':'').'">
						<span class="caret middle"></span></a>
					  <a 
						href="'.$this->url('administration', array('controller'=>'models', 'action'=>'up'), array('query'=>array('id'=>$child->getId()))).'"'.
						'class="up'.($i == 1 ? ' disabled' : '').'">  <span class="up-caret middle"></span></a></td>';
			echo '<td><a
				title="Modifier" 
				class="mod-action"
				href="#action-container"
				data-toggle="modal"
				data-id='.$child->getId().'
				data-name="'.$this->eventName($child).'"
				data-parent='.$this->form->get('id')->getValue().'
				><span class="glyphicon glyphicon-pencil"></span></a> 
				<a 
				title="Supprimer" 
				href="'.$this->url('administration', array('controller'=>'models', 'action'=>'delete'), array('query'=>array('id'=>$child->getId(), 'redirect'=>false))).'" 
				class="action-delete" 
				data-id='.$child->getId().' 
				data-name="'.$this->eventName($child).'"> 
				<span class="glyphicon glyphicon-trash"></span></a></td>';
		echo '</tr>';
            }
	}
 }?>
</table>
<?php }?>
</div>
<div class="modal-footer">
<?php 
if($action){
	echo $this->formSubmit($this->form->get('submit')->setAttribute('id', 'save-action'));
} else {
	echo $this->formSubmit($this->form->get('submit')->setAttribute('id', 'save-model')); 
}?>
<button id="cancel-form-<?php echo ($action ? "action" : "model") ?>" class="btn" href="#" data-dismiss="modal" aria-hidden="true">Annuler</button>
</div>
<?php 
echo $this->form()->closeTag();
?>
