<?php $this->headScript()->appendFile($this->basePath() . '/js/stupidtable.min.js')?>
<?php $this->headScript()->appendFile($this->basePath() . '/js/models.js')?>


<div class="warnings">
<?php if (isset($this->messages['successMessages'])) { ?>
	<?php foreach ($this->messages['successMessages'] as $message) { ?>
		<div class="alert alert-success">
			<a class="close" data-dismiss="alert" href="#">&times;</a>
			<?php echo $message ?>
		</div>
	<?php }?>
<?php } ?>

<?php if (isset($this->messages['errorMessages'])) { ?>
	<?php foreach ($this->messages['errorMessages'] as $message) { ?>
		<div class="alert alert-error">
			<a class="close" data-dismiss="alert" href="#">&times;</a>
			<?php echo $message ?>
		</div>
	<?php }?>
<?php } ?>
</div>

<table class="table table-striped sortable">
<thead>
	<tr>
		<th>id</th>
		<th data-sort="string">Nom</th>
		<th data-sort="string">Catégorie</th>
		<th>Impact</th>
		<th>Fiche réflexe</th>
		<th>Ponctuel</th>
		<th>Liste</th>
		<th>Recherche</th>
		<th><a class="btn btn-mini" href="#model-container" data-toggle="modal" id="add-model">Ajouter</a></th>
	</tr>
</thead>

<tbody>
	<?php 
	foreach ($this->models as $model){
		echo '<tr>';
		echo '<td>'.$model->getId().'</td>';
		echo '<td>'.$model->getName().'</td>';
		echo '<td>'.$model->getCategory()->getName().'</td>';
		echo '<td>'.$this->impact($model->getImpact()).'</td>';
		echo '<td>'.$this->actions[$model->getId()].'</td>';
		echo '<td>'.($model->isPunctual()?"<i class=\"icon-ok icon-grey\"></i>":"<i class=\"icon-remove icon-grey\"></i>").'</td>';
		echo '<td>'.($model->isListable()?"<i class=\"icon-ok icon-grey\"></i>":"<i class=\"icon-remove icon-grey\"></i>").'</td>';
		echo '<td>'.($model->isSearchable()?"<i class=\"icon-ok icon-grey\"></i>":"<i class=\"icon-remove icon-grey\"></i>").'</td>';
		echo '<td>';
		echo "<a 
				title=\"Modifier\" 
				href=\"#model-container\" 
				class=\"mod\" 
				data-id=\"".$model->getId()."\" 
				data-name=\"".$model->getName()."\" 
				data-toggle=\"modal\"><i class=\"icon-pencil\"></i></a>  ";
		echo "<a 
				title=\"Supprimer\" 
				href=\"#confirm-delete\" 
				data-href=\"".$this->url('administration', array('controller'=>'models', 'action'=>'delete'), array('query'=>array('id'=>$model->getId())))."\" 
				class=\"delete\" 
				data-id=\"".$model->getId()."\" 
				data-name=\"".$model->getName()."\" 
				data-toggle=\"modal\"><i class=\"icon-trash\"></i> </a>";
		echo '</td>';
		echo '</tr>';
	}
	?>
</tbody>

</table>

<div class="modal hide fade large" id="model-container">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3  id="model-title"></h3>
	</div>
	<div id="form"></div>
</div>

<div class="modal hide fade large" id="action-container">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3  id="action-title">Nouvelle action</h3>
	</div>
	<div id="action-form"></div>
</div>

<div class="modal hide fade" id="confirm-delete">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3>Confirmer la suppression ?</h3>
	</div>
	<div class="modal-body">
		<p>Voulez-vous vraiment supprimer le modèle <em><span id="model_name"></span></em> ?</p>
		<p>La fiche réflexe associée sera supprimée également.</p>
	</div>	
	<div class="modal-footer">
		<a class="btn btn-danger" id="delete-href">Confirmer</a>
		<a id="cancel-form" class="btn" href="#" data-dismiss="modal" aria-hidden="true">Annuler</a>
	</div>	
</div>

<?php $this->inlineScript()->captureStart();?>

$(".sortable").stupidtable();

$(".sortable").bind('aftertablesort', function(event, data){
	var th = $(this).find("th");
    th.find(".arrow").remove();
    var arrow = data.direction === "asc" ? "<i class=\"icon-arrow-down\"></i>" : "<i class=\"icon-arrow-up\"></i>";
    th.eq(data.column).append('<span class="arrow"> ' + arrow +'</span>');
});

models('<?php echo $this->url('administration')?>');

<?php $this->inlineScript()->captureEnd();?>