<table class="table table-stripped">
<thead>
	<tr>
		<th>Nom</th>
		<th><a 
			id="add-model"
			class="btn btn-mini"
			href="#model-container"
			data-catid="<?php echo $this->catid;?>"
			data-toggle="modal">Ajouter</a>
		</th>
	</tr>
</thead>
<tbody>
	<?php 
		$total = count($this->models);
		$i = 0;
		foreach ($this->models as $model){
		$i++;
		//Warning : rows are also created with jquery
		echo "<tr id=\"model-".$model->getId()."\">";
			echo "<td>".$model->getName()."</td>";
			echo '<td>
				<a
					href="'.$this->url('administration', 
								array('controller'=>'models', 'action'=>'down'),
								array('query'=>array('id'=>$model->getId()))).'"'.
					'class="down'.($i == $total ? ' disabled':'').'"> 
					<span class="caret middle"></span></a>
				<a
					href="'.$this->url('administration',
								array('controller'=>'models', 'action'=>'up'),
								array('query'=>array('id'=>$model->getId()))).'"'.
					'class="up'.($i == 1 ? ' disabled' : '').'">  
					<span class="up-caret middle"></span></a>
				<a
				title="Modifier" 
				class="mod-model"
				href="#model-container"
				data-toggle="modal"
				data-id='.$model->getId().'
				data-name="'.$model->getName().'"
				><i class="icon-pencil"></i></a> 
				<a 
				href="#confirm-delete-model"
				data-toggle="modal"
				title="Supprimer" 
				data-href="'.$this->url('administration', array('controller'=>'models', 'action'=>'delete'), array('query'=>array('id'=>$model->getId(), 'redirect'=>false))).'" 
				class="delete-model" 
				data-id='.$model->getId().' 
				data-name="'.$model->getName().'"> 
				<i class="icon-trash"></i></a></td>';
		echo "</tr>";
	}?>
</tbody>
</table>