<div id="model-windows">
<?php 

$this->headScript()->appendFile($this->basePath() . '/assets/js/models.js');

//models list window

echo $this->modalwindow("models-container",
		"<h3 id=\"models-title\"></h3>",
		"",
		null,
		"<div id=\"models-table\"></div>",
		"<a class=\"btn btn-primary\" href=\"".$this->url('administration', array('controller'=>'categories'))."\">Terminer</a>");

echo $this->modalwindow("model-container", "<h3  id=\"model-title\"></h3>", "", "<div id=\"model-form\"></div>");

echo $this->modalwindow("action-container", "<h3  id=\"action-title\">Nouvelle action</h3>", "", "<div id=\"action-form\"></div>");

echo $this->modalwindow("confirm-delete-model", 
						"<h3>Confirmer la suppression ?</h3>",
						"",
						null,
						"<p>Voulez-vous vraiment supprimer le modèle <em><span id=\"model_name\"></span></em> ?</p>
						<p>La fiche réflexe associée sera supprimée également.</p>",
						"<a class=\"btn btn-danger\" id=\"delete-model-href\">Confirmer</a>
						<a id=\"cancel-form\" class=\"btn\" href=\"#\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</a>");
 
//modal windows to modify or delete file
echo $this->modalwindow("confirm-delete-file",
					"<h3>Confirmer la suppression du fichier ?</h3>",
					"",
					null,
					"<p>Voulez-vous vraiment supprimer le fichier <em><span id=\"file_name\"></span></em> ?</p>",
					"<a class=\"btn btn-danger\" id=\"delete-file-href\">Confirmer</a>
					<a class=\"btn\" href=\"#\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</a>");

echo $this->modalwindow(
    "add-file",
    "<h3>Ajout d'un fichier</h3>",
    "",
    "<div id=\"file-upload-form\"></div>"
    );

echo $this->modalwindow(
	"add-alert",
	"<h3>Ajout d'une alerte</h3>",
	"",
	"<div id=\"alert-form\"></div>");
    
?>

</div>

<?php $this->inlineScript()->captureStart();?>

models('<?php echo $this->url('administration')?>', '<?php echo $this->url('application')?>');

fileupload('<?php echo $this->url('application')?>');

<?php $this->inlineScript()->captureEnd();?>