<tr>

<?php foreach ($fields as $field) : ?>
<td>
<?php
if ($field == 'Alerte')
{
    echo $this->flightPlanViewHelper()->renderAlert($flightplan);
}
else
{
    echo (isset($flightplan[$field])) ? $flightplan[$field] : '';
}
?>
</td>
<?php endforeach; ?>
<td>
    <?php echo $flightplan['start_date']->format('H:i'); ?>
</td>

<td>
    <?php if (isset($flightplan['end_date'])) : ?>
    <?php echo $flightplan['end_date']->format('H:i'); ?>
    <?php else: ?>
    <a class="a-end-fp"
       href="#mdl-end-fp" 
       data-air-id="<?php echo $flightplan['Aicraft-Id']; ?>" 
       data-toggle="modal" 
       data-id="<?php echo $flightplan['id']; ?>" 
       href="#">
        <button class="btn btn-xs btn-primary">
            CLORE PLN
        </button>
    </a>
    <?php endif; ?>
</td>
<td id="list-fp">
    <a class="modify-evt" 
       data-id="<?php echo $flightplan['id']; ?>">
       <span class="glyphicon glyphicon-pencil"></span>
    </a>
</td>

</tr>