<?php
    $formatterJour = \IntlDateFormatter::create('fr_FR',
            \IntlDateFormatter::FULL,
            \IntlDateFormatter::FULL,
            'UTC',
            \IntlDateFormatter::GREGORIAN,
            'dd LLLL');
    $formatterJourLong = \IntlDateFormatter::create("fr_FR",
            \IntlDateFormatter::FULL,
            \IntlDateFormatter::FULL,
            'UTC',
            \IntlDateFormatter::GREGORIAN,
            'dd LLLL yyyy');
    $formatterHeure = \IntlDateFormatter::create("fr_FR",
        \IntlDateFormatter::FULL,
        \IntlDateFormatter::FULL,
        'UTC',
        \IntlDateFormatter::GREGORIAN,
        'HH:mm');
?>

<html>
    <head>
        <style>
            body {
                font-family: "DejaVu Sans";
                font-size: 10px;
            }
            
            .text-center {
                text-align: center;
            }

            .push-left {
                float: left;
            }

            #header {
                width: 21cm;
            }

            #logo, #head-title {
                display: inline;
            }

            table td {
                text-align: left;
            }
            
            .table {
                width: 100%;
            }

            .table td:first-child {
                width: 10%;
            }

            .table_op {
              width: 100%;
              max-width: 100%;
            }

            .table_op > tbody > tr > td{
                border-bottom: 1px solid #ddd;
            }

            .table_op > thead > tr > th {
              vertical-align: bottom;
              border-bottom: 2px solid #ddd;
              font-weight: bold;
            }


            #header table tr td:first-child {
                width: 5%;
            }
            
            #header table {
                width: 90%;
            }

            .cat_title {
                font-weight: bold;
                font-size: 16px;
            }
            
            .subcat_title {
                font-weight: bold;
                font-size: 14px;
                margin-left: 20px;
            }
            
            .event_name {
                font-size: 12px;
                font-style: italic;
            }
            
            .event_title{
                font-weight: bold;
                margin:0px;
            }
            
            .event {
                padding: 0px 0px 0px 15px;
                margin: 10px 0px 10px;
                border-left: 5px solid #EEE;
            }
            
            body, div {
                font-family: sans-serif;
            }
            
        </style>
    </head>

    <body>
        <div id="header">
            <table>
                <tr>
                    <td> <img src="<?php echo __DIR__ ?>/../../../../../public/img/logo-dsna.png"></img></td>
                    <td style="text-align: right;">Généré le <?php echo $formatterJourLong->format(new \DateTime())?> à <?php echo $formatterHeure->format(new \DateTime())?></td>
                </tr>
            </table>
        </div>
        <div id="title" class="text-center">
            <h1>Rapport du <?php echo $formatterJourLong->format(new \DateTime($this->day)); ?></h1>
        </div>
        <div id="report">
        <?php
            $cat = null;
            foreach ($this->events as $event){
                    echo '<div class="cat_title">'.$event['name'].'</div>';
                    foreach ($event['events'] as $e) {
                        echo $this->partial('event.phtml', array('event' => $e, 'logs' => $this->logs));
                    }           
                    foreach ($event['childs'] as $subcat) {
                        if(count($subcat['events']) > 0 ) {
                            echo '<div class="subcat_title"> > '.$subcat['name'].'</div>';
                        }
                        foreach ($subcat['events'] as $e) {
                            echo $this->partial('event.phtml', array('event' => $e, 'logs' => $this->logs));
                        }
                    }
            }
        ?>
        </div>
        <div id="opsups">
          <h2>Prise de service des superviseurs opérationnels</h2>
          <table class="table_op">
            <thead>
            <tr>
              <th>Nom</th>
              <th>Prise de service</th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($this->opsups as $entry) {
                $opsup = $entry['opsup'];
                $date = $entry['date'];
                echo '<tr><td>';
                echo $opsup->getName() . '</td>';
                echo '<td>' . $formatterJour->format($date) . ' à ' . $formatterHeure->format($date).'</td></tr>';
            }
            ?>
            </tbody>
          </table>

        </div>
    </body>
</html>
