<?php
    $formatterJour = \IntlDateFormatter::create(\Locale::getDefault(),
            \IntlDateFormatter::FULL,
            \IntlDateFormatter::FULL,
            'UTC',
            \IntlDateFormatter::GREGORIAN,
            'dd LLLL');
    $formatterJourLong = \IntlDateFormatter::create(\Locale::getDefault(),
            \IntlDateFormatter::FULL,
            \IntlDateFormatter::FULL,
            'UTC',
            \IntlDateFormatter::GREGORIAN,
            'dd LLLL yyyy');
    $formatterHeure = \IntlDateFormatter::create(\Locale::getDefault(),
            \IntlDateFormatter::FULL,
            \IntlDateFormatter::FULL,
            'UTC',
            \IntlDateFormatter::GREGORIAN,
            'HH:mm');
?>

<html>
    <head>
        <style>
            body {
                font-family: "DejaVu Sans";
                font-size: 10px;
            }
            
            .text-center {
                text-align: center;
            }

            .push-left {
                float: left;
            }

            #header {
                width: 21cm;
            }

            #logo, #head-title {
                display: inline;
            }

            table td {
                text-align: left;
            }
            
            .table {
                width: 100%;
            }

            .table td:first-child {
                width: 10%;
            }
            
            #header table tr td:first-child {
                width: 5%;
            }
            
            #header table {
                width: 90%;
            }

            .cat_title {
                font-weight: bold;
                font-size: 14px;
            }
            
            .event_name {
                font-size: 12px;
                font-style: italic;
            }
            
            .event_title{
                font-weight: bold;
                margin:0px;
            }
            
            .event {
                padding: 0px 0px 0px 15px;
                margin: 10px 0px 10px;
                border-left: 5px solid #EEE;
            }
            
        </style>
    </head>

    <body>
        <div id="header">
            <table>
                <tr>
                    <td> <img src="<?php echo __DIR__ ?>/../../../../../public/img/logo-dsna.png"></img></td>
                    <td style="text-align: right;">Généré le <?php echo $formatterJourLong->format(new \DateTime())?> à <?php echo $formatterHeure->format(new \DateTime())?></td>
                </tr>
            </table>
        </div>
        <div id="title" class="text-center">
            <h1>Rapport du <?php echo $formatterJour->format(new \DateTime($this->day)); ?></h1>
        </div>
        <div id="report">
        <?php
            $cat = null;
            foreach ($this->events as $event){
                if($cat == null || $cat !== $event->getCategory()->getName()){
                    $cat = $event->getCategory()->getName();
                    echo '<div class="cat_title">'.$cat.'</div>';
                }
                echo '<div class="event">';
                echo '<p class="event_title"><span class="event_name">'.($this->eventName($event)).'</span>';
                if($event->isPunctual()){
                    echo ' à '.$formatterHeure->format($event->getStartDate()).".";
                } else {
                    if($event->getEndDate()){
                        echo ' du '.$formatterJour->format($event->getStartDate()).' '.$formatterHeure->format($event->getStartdate()).
                             ' au '.$formatterJour->format($event->getEndDate()).' '.$formatterHeure->format($event->getEnddate());
                    } else {
                        echo ' à partir du '.$formatterJour->format($event->getStartDate()).' '.$formatterHeure->format($event->getStartdate());
                    }
                }
                echo ' (créé par '.$event->getAuthor()->getDisplayName().', évènement '. strtolower($event->getStatus()->getName()).')';
                echo '</p>';
                echo '<table class="table">';
                foreach ($event->getCustomFieldsValues() as $value){
                    if($this->customfieldvalue($value) != ''){
                        echo '<tr>';
                        echo '<td></td>';
                        echo '<td>' . $value->getCustomfield()->getName().' : </td>';
                        echo '<td colspan="3">'.nl2br($this->customfieldvalue($value)).'</td>';
                        echo '</tr>';
                    }
                }
                foreach ($event->getUpdates() as $update){
                    echo '<tr>';
                    echo '<td></td>';
                    echo '<td>'.$this->updateAuthor($update).' le '.$formatterJour->format($update->getCreatedOn()).' à '.$formatterHeure->format($update->getCreatedOn()).' : </td>';
                    echo '<td colspan="3">'.nl2br($update->getText()).'</td>';
                    echo '</tr>';
                }
                echo '</table>';
                echo '</div>';
            }
        ?>
        </div>
    </body>
</html>
