<?php
    $formatterJour = \IntlDateFormatter::create(\Locale::getDefault(),
            \IntlDateFormatter::FULL,
            \IntlDateFormatter::FULL,
            'UTC',
            \IntlDateFormatter::GREGORIAN,
            'dd LLLL');
    $formatterHeure = \IntlDateFormatter::create(\Locale::getDefault(),
            \IntlDateFormatter::FULL,
            \IntlDateFormatter::FULL,
            'UTC',
            \IntlDateFormatter::GREGORIAN,
            'HH:mm');
?>

<html>
    <head>
        <style>
            .text-center {
                text-align: center;
            }

            .push-left {
                float: left;
            }

            #header {
                width: 21cm;
            }

            #logo, #head-title {
                display: inline;
            }

            #title {
                font-size: large;
            }

            .table th, .table td {
                border: 1px solid;
            }

            table {
                width: 100%;
            }

            table td:first-child {
                width: 10%;
            }
            table td:nth-child(2){
                width: 40%;
            }
            table td:last-child{
                width: 50%;
            }
            
            #header table tr td:first-child {
                width: 5%;
            }

            .cat_title {
                text-decoration: underline;
                font-size: medium;
            }
            
            .event_name {
                font-style: italic;
            }
            
            .event_title{
                font-weight: bold;
            }
            
        </style>
    </head>

    <body>
        <div id="header">
            <table>
                <tr>
                    <td> <img src="<?php echo __DIR__ ?>/../../../../../public/img/logo-dsna.png"></img></td>
                </tr>
            </table>
        </div>
        <div id="title" class="text-center">
            <h1>Rapport du <?php echo $formatterJour->format(new \DateTime($this->day)); ?></h1>
        </div>
        <div id="report">
        <?php
            $cat = null;
            foreach ($this->events as $event){
                if($cat == null || $cat !== $event->getCategory()->getName()){
                    $cat = $event->getCategory()->getName();
                    echo '<div class="cat_title">'.$cat.'</div>';
                }
                echo '<div class="event">';
                echo '<p class="event_title"><span class="event_name">'.$this->eventName($event).'</span>';
                if($event->isPunctual()){
                    echo ' à '.$formatterHeure->format($event->getStartDate()).".";
                } else {
                    if($event->getEndDate()){
                        echo ' du '.$formatterJour->format($event->getStartDate()).' '.$formatterHeure->format($event->getStartdate()).
                             ' au'.$formatterJour->format($event->getEndDate()).' '.$formatterHeure->format($event->getEnddate());
                    } else {
                        echo ' à partir du '.$formatterJour->format($event->getStartDate()).' '.$formatterHeure->format($event->getStartdate());
                    }
                }
                echo '</p>';
                echo '<table>';
                echo '<tr><td></td><td>Auteur</td>';
                echo '<td>'.$event->getAuthor()->getDisplayName().'</td></tr>';
                echo '<tr><td></td><td>Statut</td>';
                echo '<td>'.$event->getStatus()->getName().'</td></tr>';
                foreach ($event->getCustomFieldsValues() as $value){
                    if($this->customfieldvalue($value) != ''){
                        echo '<tr>';
                        echo '<td></td>';
                        echo '<td>' . $value->getCustomfield()->getName().'</td>';
                        echo '<td>'.nl2br($this->customfieldvalue($value)).'</td>';
                        echo '</tr>';
                    }
                }
                foreach ($event->getUpdates() as $update){
                    echo '<tr>';
                    echo '<td></td>';
                    echo '<td>'.$this->updateAuthor($update).' le '.$formatterJour->format($update->getCreatedOn()).' à '.$formatterHeure->format($update->getCreatedOn()).' :</td>';
                    echo '<td>'.nl2br($update->getText()).'</td>';
                    echo '</tr>';
                }
                echo '</table>';
                echo '</div>';
            }
        ?>
        </div>
    </body>
</html>
