<?php

$form = $this->form;
$form->prepare();

?>

<?php echo $this->form()->openTag($form) ?>

<div class="modal-body">

<?php 

echo $this->formHidden($form->get('id'));

echo $this->controlGroup($form->get('type'));

echo $this->controlGroup($form->get('lat'));

echo $this->controlGroup($form->get('lon'));

echo $this->controlGroup($form->get('typealerte'));

echo $this->controlGroup($form->get('cause')); 
?>

</div>


    
<?php echo $this->form()->closeTag() ?>
