<?php
$this->headLink()->prependStylesheet($this->basePath() . '/components/leaflet/dist/leaflet.css');
$this->headLink()->prependStylesheet($this->basePath() . '/assets/css/sarbeacons.css');
$this->headScript()->appendFile($this->basePath() . '/assets/js/headerbar.js'); 
$this->headScript()->appendFile($this->basePath() . '/components/leaflet/dist/leaflet.js');
$this->headScript()->appendFile($this->basePath() . '/assets/js/sarbeacons.js');
?>
<div class="row">
    <div class="col-sm-9 fill">
        <div id="mapid"></div>
    </div>

    <div id="tabs" class="col-sm-3">
        <ul class="nav nav-pills">
            <!-- <li class="active"><a href="#tabs-1"><span class="glyphicon glyphicon-search"></span></a></li> -->
            <li class="active"><a href="#tabs-1">Déclencher</a></li>
            <!-- <li><a href="#tabs-2"><span class="glyphicon glyphicon-screenshot"></span></a></li> -->
            <li><a href="#tabs-2">Terrains</a></li>
            <!-- <li><a href="#tabs-3" id="a-now"><span class="glyphicon glyphicon-list"></span></a></li> -->
            <li><a href="#tabs-3" id="a-now">En cours<span class="badge badge-important">0</span></a></li>
            <!-- <li><a href="#tabs-4" id="a-arch"><span class="glyphicon glyphicon-list"></span></a></li> -->
            <li><a href="#tabs-4" id="a-arch">Terminé<span class="badge badge-important">0</span></a></li>
        </ul>

        <div id="tabs-1">
            <h4>Coordonnées de l'alerte</h4>
            <div class="row">
                <div class="col-sm-5 form-group has-error">
                    <input id="inp-lat" type="search" class="form-control" placeholder="Lat" />
                     <span class="raz-coord cache glyphicon glyphicon-remove-circle"></span>
                </div>
                <div class="col-sm-5 form-group has-error">
                    <input id="inp-lon" type="text" class="form-control" placeholder="Lon" />
                     <span class="raz-coord cache glyphicon glyphicon-remove-circle"></span>
                </div>
            </div>
            <div class="row">
                <button id="btn-rech-coo" type="button" class="btn btn-warning disabled" href="#mdl-start-ip" data-toggle="modal">Démarrer le plan d'interrogation</span></button>
            </div>
            <h4>Balises</h4>
            <div class="row">
                <div class="col-sm-10 form-group has-error">
                    <input id="inp-bal" type="text" class="form-control"  placeholder="ex : 'OKIPA'" />
                     <span class="raz-bal cache glyphicon glyphicon-remove-circle"></span>
                </div>
  <!--               <div class="col-sm-2">
                    <button id="btn-rech-bal" type="button" class="btn btn-warning disabled"><span class="glyphicon glyphicon-alert"></span></button>
                </div> -->
            </div>
            <h4>Terrains</h4>
            <div class="row">
                <div class="col-sm-10 form-group has-error">
                    <input id="inp-ter" type="text" class="form-control" placeholder="ex : 'LFH464'" />
                     <span class="raz-ter cache glyphicon glyphicon-remove-circle"></span>
                </div>
<!--                 <div class="col-sm-2">
                    <button id="btn-rech-ter" type="button" class="btn btn-warning disabled"><span class="glyphicon glyphicon-alert"></span></button>
                </div> -->
            </div>
<!--             <div class="row">
                <button id="btn-trig-alt" type="button" class="btn btn-primary disabled">Démarrer le plan d'interrogation</button>
            </div> -->
        </div>
        <div id="tabs-2">
            <h4>Terrains à proximité</h4>
            <div id="f-ip" class="cache">
                <!-- <h4></h4> -->

<!--                 <button class="btn btn-action-ip" id="btn-edit-ip" title="Modifier" data-toggle="modal" data-action="edit" data-state="2" href="#mdl-edit-ip"><span class="glyphicon glyphicon-edit"></span></button>

                <button class="btn btn-action-ip" id="btn-sav-ip" title="Sauvegarder" data-action="sav" data-state="1"><span class="glyphicon glyphicon-floppy-save"></span></button>

                <button class="btn btn-action-ip" id="btn-mail-ip" title="Envoyer par e-mail" data-action="mail" data-state="1"><span class="glyphicon glyphicon-envelope"></span></button>

                <button class="btn btn-action-ip" id="btn-print-ip" title="Imprimer" data-action="print" data-state="1"><span class="glyphicon glyphicon-print"></span></button> -->
            </div>
<!--                     <h4>Résultats des recherches de terrains</h4> -->
            <div id="req-pio" class="carousel slide cache" data-ride="carousel">
                <div class ="row">
                    <div class="col-sm-2">
                        <a class="carousel-control left" href="#req-pio" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                        </a>
                    </div>
                    <div class="col-sm-8">
                        <ol class="carousel-indicators"></ol> 
                    </div>
                    <div class="col-sm-2">
                        <a class="carousel-control right" href="#req-pio" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right"></span>
                        </a>
                    </div>
                </div>
                <!-- Carousel indicators -->  
                <!-- Wrapper for carousel items -->
                <div class="carousel-inner"></div>
            </div>
        </div>
        <div id="tabs-3">
            <!-- <h4>Plan(s) d'interrogation en cours</h4> -->
            <ul id="currentip" class="list-ip">

            </ul>
        </div>

        <div id="tabs-4">
            <!-- <h4>Plan(s) d'interrogation terminé(s)</h4> -->
            <ul id="archives" class="list-ip">

            </ul>
        </div>
    </div>
</div>

<?=$this->modalWindow(  "mdl-edit-ip", 
                        "<h3 id='title-edit-ip'></h3>", 
                        "", 
                        "<div id='f-edit-ip'></div>")
                        ?>

<?=$this->modalWindow(  "mdl-show-ip", 
                        "<h3 id='title-show-ip'></h3>", 
                        "", 
                        "<div id='f-show-ip'></div>")
                        ?>

<?=$this->modalWindow(  "mdl-start-ip", 
                        "<h3 id='title-start-ip'>Démarrer un plan d'interrogation</h3>", 
                        "",
                        null,
                        "<div id='f-start-ip'></div>",
                        "<a class='btn btn-danger' id='a-start-ip-ok'>Confirmer</a>
                        <a class='btn' href='#' data-dismiss='modal' aria-hidden='true'>Annuler</a>") 
                        ?>

<?=$this->modalwindow(  "mdl-end-ip",
                        "<h3>Clore le plan d'interrogation</span></h3>",
                        "", 
                        null, 
                        "<input type='datetime' name='end-date'></input>",
                        "<a class='btn btn-danger' id='a-end-ip-ok'>Confirmer</a>
                        <a class='btn' href='#' data-dismiss='modal' aria-hidden='true'>Annuler</a>") ?>

<?php $this->inlineScript()->captureStart();?>

$("#home").removeClass("dropdown-toggle")
		  .attr('data-toggle', '')
		  .html('<span class="glyphicon glyphicon-home"></span> Évènements');

$("#create-link").remove();		  

$("#changeview").remove();

$('#search').remove();

sarbeacons('<?php echo $this->url('application'); ?>');

<?php $this->inlineScript()->captureEnd();?>