<?php
    $formatterJour = \IntlDateFormatter::create('fr_FR',
            \IntlDateFormatter::FULL,
            \IntlDateFormatter::FULL,
            'UTC',
            \IntlDateFormatter::GREGORIAN,
            'dd LLLL');
    $formatterJourLong = \IntlDateFormatter::create("fr_FR",
            \IntlDateFormatter::FULL,
            \IntlDateFormatter::FULL,
            'UTC',
            \IntlDateFormatter::GREGORIAN,
            'dd LLLL yyyy');
    $formatterHeure = \IntlDateFormatter::create("fr_FR",
        \IntlDateFormatter::FULL,
        \IntlDateFormatter::FULL,
        'UTC',
        \IntlDateFormatter::GREGORIAN,
        'HH:mm');
?>
<html>
    <head>
        <style>

            body {
                font-family: "DejaVu Sans";
                font-size: 12px;
            }

            .text-center {
                text-align: center;
            }

            .push-left {
                float: left;
            }

            #header {
                width: 21cm;
            }

            #logo, #head-title {
                display: inline;
            }

            table td {
                text-align: left;
            }

            .table {
                width: 100%;
            }

            .table td:first-child {
                width: 10%;
            }

            #header table tr td:first-child {
                width: 5%;
            }

            #header table {
                width: 90%;
            }

            .badge, button, h1, .notinpdf {
                display:none;
            }

            body, div {
                font-family: sans-serif;
            }

            h3 {
                margin-top:25px;
            }

            #intplan-pdf {
                padding:30px 65px 0px 65px;
            }

            p, h4{
                margin-left:8px;
            }

            .comment {
                white-space: pre-wrap;
                margin-left:35px;
            }

            #signature {
                margin-top:45px;
                text-align:right;
            }

        </style>
    </head>

    <body>
        <div id="header">
            <table>
                <tr>
                    <td> <img src="<?php echo __DIR__ ?>/../../../../../public/img/logo-dsna.png" /></td>
                    <td style="text-align: right;">Généré le <?php echo $formatterJourLong->format(new \DateTime())?> à <?php echo $formatterHeure->format(new \DateTime())?>
                    </td>
            </table>
        </div>
        <div id="title" class="text-center">
            <h2><?php echo $ipArray['Type'];?> démarré le <?php echo $formatterJour->format($ipArray['start_date']); ?> à <?php echo $formatterHeure->format($ipArray['start_date']); ?></h2>
        </div>
        <div id="intplan-pdf">
            <?php  echo $this->sbViewHelper()->renderIp($ipArray); ?>
            <p id = "signature">BTIV du CRNA-N</p>
        </div>
    </body>
</html>