<?php
    $formatterJour = \IntlDateFormatter::create('fr_FR',
            \IntlDateFormatter::FULL,
            \IntlDateFormatter::FULL,
            'UTC',
            \IntlDateFormatter::GREGORIAN,
            'dd LLLL');
    $formatterJourLong = \IntlDateFormatter::create("fr_FR",
            \IntlDateFormatter::FULL,
            \IntlDateFormatter::FULL,
            'UTC',
            \IntlDateFormatter::GREGORIAN,
            'dd LLLL yyyy');
    $formatterHeure = \IntlDateFormatter::create("fr_FR",
        \IntlDateFormatter::FULL,
        \IntlDateFormatter::FULL,
        'UTC',
        \IntlDateFormatter::GREGORIAN,
        'HH:mm');
?>
<!DOCTYPE html>
<html>
    <head>
        <title>SAR</title>
        <style>

            body {
                font-family: "DejaVu Sans, sans-serif";
                font-size: 12px;
            }

            .text-center {
                text-align: center;
            }

            .push-left {
                float: left;
            }

            #header {
                width: 21cm;
            }

            #logo, #head-title {
                display: inline;
            }

            table td {
                text-align: left;
            }

            .table {
                width: 100%;
            }

            .table td:first-child {
                width: 10%;
            }

            #header table tr td:first-child {
                width: 5%;
            }

            #header table {
                width: 90%;
            }

            h2{
                margin:10 0 15 0;
            }
            h5{
                margin:5 0 5 15;
            }
            p {
                margin:5px;
            }
            body, div {
                font-family: sans-serif;
            }

            #intplan-pdf {
                padding:30px 65px 0px 65px;
            }

            .comment {
                white-space: pre-wrap;
                /*margin-left:5px;*/
            }

            #signature {
                margin-top:45px;
                text-align:right;
            }

        </style>
    </head>

    <body>
        <div id="header">
            <table>
                <tr>
                    <td> <img src="<?php echo __DIR__ ?>/../../../../../public/img/logo-dsna.png" /></td>
                    <td style="text-align: right;">Généré le <?php echo $formatterJourLong->format(new \DateTime())?> à <?php echo $formatterHeure->format(new \DateTime())?>
                    </td>
            </table>
        </div>
        <div id="title" class="text-center">
            <h2><?php echo $ip['Alerte']['Type'];?> démarré le <?php echo $formatterJour->format($ip['start_date']); ?> à <?php echo $formatterHeure->format($ip['start_date']); ?></h2>
        </div>
        <div id="intplan-pdf">
            <?php //print_r($ip); ?>

            <div class = "panel list-ip-content">
                <h2 class="list-group-item-heading">Informations</h2>
                <p class="list-group-item-text">Latitude : <b><?php echo $ip['Latitude']?></b></p>
                <p class="list-group-item-text">Longitude : <b><?php echo $ip['Longitude']?></b></p>
                <p class="list-group-item-text">Type : <b><?php echo $ip['Type']?></b></p>
                <p class="list-group-item-text">Alerte : <b><?php echo (isset($ip['Alerte']['Type'])) ? $ip['Alerte']['Type'] : null; ?></b></p>
                <p class="list-group-item-text comment">Cause : <br ><b><?php echo (isset($ip['Alerte']['Cause'])) ? $ip['Alerte']['Cause'] : null; ?></b></p>
            </div>

            <div class = "panel list-ip-content">
                <h2 class="list-group-item-heading">Terrains interrogés</h2>
                <?php 
                if (isset($ip['fields'])) { 
                    foreach ($ip['fields'] as $i => $f) 
                    {
                        ?>
                        <div class = "list-fields">
                        <?php
                        if (count($f['updates']) > 0) {
                            ?>
                                <h5 class="list-group-item-heading"><?php echo $f['Nom'];?> [<?php echo $f['start_date']->format('H:i:s');?>]</h5>
                            <?php
                            foreach($f['updates'] as $updates) 
                            {
                                ?>
                                <p class="list-group-item-text comment cache"><?php echo $updates['text'];?></p>
                                <?php
                            }
                        } else {
                            ?>
                                <h5 class="list-group-item-heading"><?php echo $f['Nom'];?> [<?php echo $f['start_date']->format('H:i:s');?>]</h5>
                            <?php                        
                        }
                        ?>
                        </div>
                        <?php
                    }
                }
                ?>
            </div>

            <p id = "signature">BTIV du CRNA-N</p>
        </div>
    </body>
</html>