<?php
    $class_alert = [
        'INCERFA' => 'info',
        'ALERFA' => 'warning',
        'DETRESFA' => 'danger'
    ];

    $typealert = (isset($ip['Alerte']['Type'])) ? $ip['Alerte']['Type'] : null;
?>
    <div class = "panel list-ip-content">
        <h3 class="list-group-item-heading">Informations <a href="#mdl-start-ip" data-toggle="modal" class = "btn-edit-ip ">
        <span class="glyphicon glyphicon-pencil"></span>
        </a></h3>
        <p class="list-group-item-text">Latitude : <b><?php echo $ip['Latitude']?></b></p>
        <p class="list-group-item-text">Longitude : <b><?php echo $ip['Longitude']?></b></p>
        <p class="list-group-item-text">Type : <b><?php echo $ip['Type']?></b></p>
        <p class="list-group-item-text">Alerte : <b><?php echo (isset($typealert)) ? $typealert : NIL; ?></b></p>
        <p class="list-group-item-text comment">Cause : <br ><b><?php echo (isset($ip['Alerte']['Cause'])) ? $ip['Alerte']['Cause'] : null; ?></b></p>
    </div>

    <div class = "panel list-ip-content">
        <h3 class="list-group-item-heading">
            Terrains interrogés <a href="#" class = "btn-show-ip "><span class="glyphicon glyphicon-pencil"></span></a>
        </h3>
        <?php 
        if (isset($ip['fields'])) { 
            foreach ($ip['fields'] as $i => $f) 
            {
                ?>
                <div class = "list-fields">
                <?php
                if (count($f['updates']) > 0) {
                    ?>
                    <a href = "#">
                        <h5 class="list-group-item-heading"><?php echo $f['Nom'];?> [<?php echo $f['start_date']->format('H:i:s');?>]</h5>
                    </a>
                    <?php
                    foreach($f['updates'] as $updates) 
                    {
                        ?>
                        <p class="list-group-item-text comment cache"><?php echo $updates['text'];?></p>
                        <?php
                    }
                } else {
                    ?>
                        <h5 class="list-group-item-heading"><?php echo $f['Nom'];?> [<?php echo $f['start_date']->format('H:i:s');?>]</h5>
                    <?php                        
                }
                ?>
                </div>
                <?php
            }
        }
        ?>
    </div>

    <div class = "panel list-ip-content">
        <h3 class="list-group-item-heading ">Actions</h3>

        <a href="#" class = "btn-show-ip ">
        <!-- <span class="glyphicon glyphicon-pencil"></span> -->
        Sélectionner
        </a><br />

        <a href="#" class = "btn-print-ip ">
        <!-- <span class="glyphicon glyphicon-pencil"></span> -->
        Imprimer
        </a><br />
        <a href="#" class = "btn-mail-ip ">
        <!-- <span class="glyphicon glyphicon-pencil"></span> -->
        Courriel
        </a><br />
        <a href="#mdl-end-ip" data-toggle="modal" class = "btn-end-ip ">
        <!-- <span class="glyphicon glyphicon-pencil"></span> -->
        Clôturer
        </a>
    </div>