<?php $this->headScript()->appendFile($this->basePath() . '/assets/js/categories.js')?>
<?php $this->headScript()->appendFile($this->basePath() . '/js/stupidtable.min.js')?>


<div class="container-fluid">
    <div class="row">
        <div class="col-md-9">
        <p></p>
        	<div class="panel panel-default">
        	<div class="panel-heading">
        	<h4 class="panel-title">Catégories par défaut</h4>
        	</div>
        	<div class="panel-body">
            <table class="table table-striped sortable">
                <thead>
                    <tr>
                        <th data-sort="string" data-autosort="true">Nom</th>
                        <th>Catégorie par défaut</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Fréquence</td>
                        <td>
                            <select id="freq-select"  class="form-control">
                                <option value="0">Choisir la catégorie fréquence par défaut</option>
                                <?php
                                foreach ($this->freqcategories as $freq) {
                                    echo "<option value=\"" . $freq->getId() . "\" " .
                                    ($freq->isDefaultFrequencyCategory() ? "selected=\"selected\"" : "") .
                                    ">" . $freq->getName() . "</option>";
                                }
                                ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>Brouillage fréquence</td>
                        <td>
                            <select id="brouillage-select"  class="form-control">
                                <option value="0">Choisir la catégorie brouillage fréquence par défaut</option>
                                <?php
                                foreach ($this->brouillagecategories as $brouillage) {
                                    echo "<option value=\"" . $brouillage->getId() . "\" " .
                                    ($brouillage->isDefaultBrouillageCategory() ? "selected=\"selected\"" : "") .
                                    ">" . $brouillage->getName() . "</option>";
                                }
                                ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>Antenne</td>
                        <td>
                            <select id="antenna-select"  class="form-control">
                                <option value="0">Choisir la catégorie antenne par défaut</option>
                                <?php
                                foreach ($this->antennacategories as $antenna) {
                                    echo "<option value=\"" . $antenna->getId() . "\" " .
                                    ($antenna->isDefaultAntennaCategory() ? "selected=\"selected\"" : "") .
                                    ">" . $antenna->getName() . "</option>";
                                }
                                ?>
                            </select>
                        </td>
                </tbody>
            </table>
            </div>
            </div>
        </div>
        <div class="col-md-3">
            <p></p>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title" id="Organisations">Aide</h4>
                </div>
                <div class="panel-body">
                    Les catégories par défaut sont utilisées lors de la création automatique d'évènements depuis les pages spéciales telles que :
                    <ul>
                        <li>la page Fréquences.</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<?php $this->inlineScript()->captureStart();?>

$('document').ready(function(){
	$.material.init();
});

categories('<?php echo $this->url('administration'); ?>');


<?php $this->inlineScript()->captureEnd();?>