
<div class="modal-body">
	<?php if(count($this->fields)>0){?>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>id</th>
				<th>Nom</th>
				<th>Type</th>
				<th> </th>
				<th><a href="#" data-id="<?php echo $this->categoryid; ?>" class="btn btn-mini" id="new-field">Ajouter</a></th>
			</tr>
		</thead>
		<tbody>
		<?php 
		foreach ($fields as $field){
			echo "<tr>";
			echo "<td>".$field->getId()."</td>";
			echo "<td>".$field->getName()."</td>";
			echo "<td>".$field->getType()->getName()."</td>";
			echo "<td><a href=\"#\"><span class=\"up-caret middle\"></span></a> <a href=\"#\"><span class=\"caret middle\"></span></a></td>";
			echo "<td>";
			echo "<a href=\"#\" class=\"mod-field\" data-id=\"".$field->getId()."\" data-name=\"".$field->getName()."\"><i class=\"icon-pencil\"></i></a> ";
			echo "<a href=\"#confirm-delete-field\" 
					data-href=\"".$this->url('administration', 
											array('controller'=>'fields', 'action'=>'delete'),
											array('query'=>array('id'=>$field->getId())))."\" 
					class=\"delete-field\" 
					data-id=\"".$field->getId()."\" 
					data-name=\"".$field->getName()."\" 
					data-toggle=\"modal\"><i class=\"icon-remove-sign\"></i> </a>";
			echo "</td>";
			echo "</tr>";
		}
		?>
		<tr id="add-field">
		</tr>
		</tbody>
	</table>
	<?php } else {?>
	<p>Aucun champ spécifique à cette catégorie : <a href="#" data-id="<?php echo $this->categoryid; ?>" class="btn btn-mini" id="new-field">Ajouter</a></p>
	<table class="table table-striped">
	<tbody>
	<tr id="add-field">
	</tr>
	</tbody>
	</table>
	<?php }?>
<?php 
?>
</div>

<div class="modal-footer">
	<a href="<?php echo $this->url('administration', array('controller'=>'categories')); ?>" class="btn btn-primary">Terminer</a> 
	<a id="cancel-form" class="btn" href="#" data-dismiss="modal"
		aria-hidden="true">Annuler</a>
</div>
