

<?php 
$this->form->setAttribute('action', $this->url('administration', array('controller'=>'categories', 'action'=>'save')));
$this->form->setAttribute('class', 'form-horizontal');
$this->form->prepare();

echo $this->form()->openTag($this->form);
?>
<div class="modal-body">
<?php


echo $this->formHidden($this->form->get('id'));

echo $this->controlGroup($this->form->get('type'));

echo $this->controlGroup($this->form->get('name'));


echo $this->controlGroup($this->form->get('shortname'));
if($this->system){
    echo '<div style="display:none;">';
}
echo $this->controlGroup($this->form->get('color')->setAttribute('class', 'pick-a-color'));
		
echo $this->controlGroup($this->form->get('compactmode'));

echo $this->controlGroup($this->form->get('timeline'));

echo $this->controlGroup($this->form->get('parent'));
if($this->system) {
    echo "</div>";
}
echo $this->controlGroup($this->form->get('fieldname'));

echo $this->controlGroup($this->form->get('readroles'));

?>
</div>
<div class="modal-footer">
<?php echo $this->formSubmit($this->form->get('submit')); ?>
<a id="cancel-form" class="btn" href="#" data-dismiss="modal" aria-hidden="true">Annuler</a>
</div>
<?php 
echo $this->form()->closeTag();
?>
