
<div class="popover-title">
<?php
echo $this->title;
?>
</div>
<?php

$this->form->setAttribute('action', $this->url('administration', array('controller'=>'categories', 'action'=>'save')));
$this->form->setAttribute('class', 'form-horizontal');
$this->form->prepare();

echo $this->form()->openTag($this->form);
echo $this->formHidden($this->form->get('id'));
echo $this->controlGroup($this->formLabel($this->form->get('name')->setLabelAttributes(array('class' => 'control-label'))),
						$this->formInput($this->form->get('name')));


echo $this->controlGroup($this->formLabel($this->form->get('shortname')->setLabelAttributes(array('class' => 'control-label'))),
						$this->formInput($this->form->get('shortname')));

echo $this->controlGroup($this->formLabel($this->form->get('parent')->setLabelAttributes(array('class' => 'control-label'))),
		$this->formSelect($this->form->get('parent')));

echo $this->controlGroup($this->formLabel($this->form->get('color')->setLabelAttributes(array('class' => 'control-label'))),
						$this->formInput($this->form->get('color')->setAttribute('class', 'colorpicker')));

?>
<div class="control-group">
<div class="controls">
	<?php echo $this->formSubmit($this->form->get('submit')); ?>
	<a class="btn" href="#" id="cancel-form">Annuler</a>
</div>
</div>
<?php 
echo $this->form()->closeTag();
?>
