<?php echo $this->doctype(); ?>

<html lang="fr">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Epeires²'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/assets/css/application.css') 
                        ->prependStylesheet($this->basePath() . '/assets/css/core.css') 
                        ->prependStylesheet($this->basePath() . '/assets/css/jquery.timepicker.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/timeline.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-switch.css')
                        ->prependStylesheet($this->basePath() . '/components/bootstrap-default/css/bootstrap-responsive.css')
                        ->prependStylesheet($this->basePath() . '/components/bootstrap-default/css/bootstrap.css')
                        ->prependStylesheet($this->basePath() . '/components/jquery-ui/themes/smoothness/jquery-ui.min.css')
        				?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
			->prependFile($this->basePath() . '/assets/js/application.js')
                        ->prependFile($this->basePath() . '/assets/js/headerbar.js')
                        ->prependFile($this->basePath() . '/assets/js/alarm.js')
                        ->prependFile($this->basePath() . '/assets/js/form.js')
                        ->prependFile($this->basePath() . '/assets/js/jquery.timepicker.js')
                        ->prependFile($this->basePath() . '/assets/js/application.js')
                        ->prependFile($this->basePath() . '/js/jquery.mousewheel.js')
                        ->prependFile($this->basePath() . '/js/bootstrap-switch.js')
                        ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                        ->prependFile($this->basePath() . '/components/bootstrap/js/bootstrap.min.js')
                        ->prependFile($this->basePath() . '/js/noty/packaged/jquery.noty.packaged.min.js')
                        ->prependFile($this->basePath() . '/components/jquery-ui/ui/minified/i18n/jquery.ui.datepicker-fr.min.js')
                        ->prependFile($this->basePath() . '/components/jquery-ui/ui/minified/jquery-ui.min.js')
                        ->prependFile($this->basePath() . '/components/jquery/jquery.min.js')
        ?>

    </head>
    <body>
    	<div class="header">
    		<ul class="inline">
    				<?php echo $this->userMenu(); ?>
    				<?php if($this->zfcUserIdentity() && !$this->zoneform) :?>
    				<li><i class="icon-road"></i><b> Organisation : </b><?php echo $this->zfcUserIdentity()->getOrganisation()->getName();?></li>
    				<?php endif;?>
    				<?php if($this->zoneform) :?>
    				<li><i class="icon-filter"></i><b> Zone : </b></li>
    				<li><?php 
    						$form = $this->zoneform;
    						$form->setAttributes(array('action' => $this->url('application', array('controller'=>'events', 'action'=>'savezone')),
												'class'=>''));
    						$form->prepare();
    						echo $this->form()->openTag($form);
    						echo $this->formSelect($form->get('zone'));
    						echo $this->form()->closeTag();
    					?>
    				</li>
    				<?php  endif;?>
    				<?php if($this->zfcUserIdentity() && $this->zfcUserIdentity()->getZone()) :?>
    				<li><i class="icon-eye-open"></i><b> Chef de salle : </b><?php echo $this->opsup();?></li>
    				<?php endif;?>
    				<li><i class="icon-warning-sign"></i><b> IPO : </b><?php echo $this->ipo();?></li>
    				<li id="clock" class="pull-right"></li>
    		</ul>
    		
    	</div>
    	<div class="navbar navbar-after-top">
    		<div class="navbar-inner">
    			<ul class="nav pull-left">
    				<?php if($this->isGranted('events.create')):?>
    				<li>
    					<a href="#" id="create-link"><i class="icon-pencil"></i> <i class="icon-chevron-down"></i></a>
    				</li>
    				<?php endif;?>
    			</ul>
	        	<ul class="nav-centered nav">
	            	<li class="dropdown active">  <!-- lien par défaut, classe "active" supprimée par jquery si besoin -->
	            		<a id="home" class="dropdown-toggle" data-toggle="dropdown" href="<?php echo $this->url('application', array('controller'=>'events', 'action'=>'index'))?>"><i class="icon-home"></i> Évènements <b class="caret"></b></a>
	            		<ul class="dropdown-menu">
	            			<li class="nav-header">Tri</li>
	            			<li class="active"><a href="#" id="tri_cat">Par catégorie</a></li>
	            			<li><a id="tri_deb" href="#">Par heure de début</a></li>
	            			<li class="divider"></li>
	            			<li class="nav-header">Filtre</li>
                                        <li class="active"><a id="tri_std" href="#">Cacher les évènements archivés</a></li>
	            			<li><a href="#" id="tri_tout">Afficher tous les évènements</a></li>
	            		</ul>
	            		
	            	</li>
	            	<li class="divider-vertical"></li>
                        <?php
                        if($this->isGranted('radars.read')){
                            echo '<li><a href="'
                                . $this->url('application', array('controller'=>'radars', 'action'=>'index'))
                                . '">Radars</a></li>';
                        }
                        ?>
                        <?php
                        if($this->isGranted('frequencies.read')){
                            echo '<li><a id="frequency" href="'
                                . $this->url('application', array('controller'=>'frequencies', 'action'=>'index'))
                                . '">Radio</a></li>';
                        }
                        ?>
                        </ul>
	        	<ul class="nav pull-right">
	        		<li>
	        			<form class="navbar-search" id="search">
	        				<input name="search" class="search-query" type="text" placeholder="Chercher"></input>
	        			</form>
	        		</li>
	        		<li>
	        			<div id="zoom" class="make-switch switch-small nav-in" data-on-label="Jour" data-off-label="6h" data-off="success" data-on="info" data-text-label="Vue">
							<input type="checkbox">
						</div>
					</li>
			<!-- 	<li>
						<div id="cpt_evts">0</div>
					</li> -->
	        	</ul>
        	</div>
        </div>
        
        <div class="content">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        
        <?php 
		if(!$this->zfcuserIdentity()){
				echo $this->modalWindow("loginwindow", "<h3>Connexion</h3>", "", $this->zfcUserLoginWidget(array('redirect'=>$this->serverUrl(true))));
		} ?>
        
        <?php $this->inlineScript()->captureStart();?>
                
                setURL('<?php echo $this->url('application');?>');
		
		//init header bar
		headerbar('<?php echo $this->url('application', array('controller' => 'events'));?>');
                
                //gestion des alertes
		setURLAlarm('<?php echo $this->url('application');?>');
		updateAlarms();
                
		<?php $this->inlineScript()->captureEnd();?>
        
        
        <?php echo $this->inlineScript() ?>
    </body>
</html>
