<?php echo $this->doctype(); ?>

<html lang="fr">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('PV CdS'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/application.css') 
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui.min.css')
        				?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/application.js')
        							  ->prependFile($this->basePath() . '/js/jquery-datetimepicker.js')
        							  ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery-ui.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js')
        							   ?>

    </head>
    <body>
    	<div class="header">
    		<span id="clock"></span>
    	</div>
    	<div class="nav-centered">
        	<ul class="nav nav-tabs">
            	<li><a href="<?php echo $this->url('application', array('controller'=>'events', 'action'=>'index'))?>">Tous</a></li>
            	<li><a href="<?php echo $this->url('application', array('controller'=>'frequencies', 'action'=>'index')) ?>">Fréquences</a></li>
        	</ul>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
