<?php echo $this->doctype(); ?>

<html lang="fr" class="no-js">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('PV CdS'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/application.css') 
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui.min.css')
        				?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/application.js')
        							  ->prependFile($this->basePath() . '/js/modernizr.custom.js')
        							  ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery-ui.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js')
        							   ?>

    </head>
    <body>
    	<div class="header">
    		<span id="clock"></span>
    	</div>
    	<div class="navbar navbar-after-top">
    		<div class="navbar-inner">
    			<ul class="nav pull-left">
    				<li>
    					<a href="#" id="create-link"><i class="icon-pencil"></i> <i class="icon-chevron-down"></i></a>
    				</li>
    			</ul>
	        	<ul class="nav-centered nav">
	            	<li class="dropdown active">  <!-- lien par défaut, classe "active" supprimée par jquery si besoin -->
	            		<a class="dropdown-toggle" data-toggle="dropdown" href="<?php echo $this->url('application', array('controller'=>'events', 'action'=>'index'))?>"><i class="icon-home"></i> Filtres <b class="caret"></b></a>
	            		<ul class="dropdown-menu">
	            			<li><a href="<?php echo $this->url('application', array('controller'=>'events', 'action'=>'index'))?>">Tous</a></li>
	            			<li><a href="<?php echo $this->url('application', array('controller'=>'events', 'action'=>'index', 'filter'=>'important'))?>">Importants</a></li>
	            		</ul>
	            		
	            	</li>
	            	<li class="divider-vertical"></li>
	            	<li><a href="<?php echo $this->url('application', array('controller'=>'sar', 'action'=>'index')) ?>">SAR</a></li>
	            	<li><a href="<?php echo $this->url('application', array('controller'=>'frequencies', 'action'=>'index')) ?>">Fréquences</a></li>
	        	</ul>
	        	<form class="navbar-search pull-right">
	        		<input class="search-query span2" type="text" placeholder="Search"></input>
	        	</form>
        	</div>
        </div>
        <div class="content">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        
        <?php echo $this->inlineScript() ?>
    </body>
</html>
