<?php if($this->error) :?>
 
<div class="alert alert-error">
	<?php echo nl2br($this->error); ?>
</div>

<?php else :?>

<?php
$this->form->setAttribute('action', $this->url('application', array('controller'=>'frequencies', 'action'=>'savebrouillage')) . '?freqid='.$this->freqid);
$this->form->setAttribute('class', 'form-horizontal');
$this->form->prepare();

echo $this->form()->openTag($this->form);
?>
<div class="modal-body">
<?php


echo $this->formHidden($this->form->get('id'));

echo $this->formHidden($this->form->get('category'));

echo $this->controlGroup($this->formLabel($this->form->get('impact')->setLabelAttributes(array('class' => 'control-label'))),
		$this->formSelect($this->form->get('impact')));

echo $this->formHidden($this->form->get('punctual')->setAttribute('value', true));
	
echo $this->formHidden($this->form->get('organisation'));

echo $this->formHidden($this->form->get('status'));

echo $this->controlGroup(
		$this->formLabel($this->form->get('startdate')->setLabelAttributes(array('class'=>'control-label time-middle'))),
		$this->formDateTimeEnhanced("start") . $this->formHidden($this->form->get('startdate')), array('class'=>'compact'));

?>

<div class="custom-fields">
<?php 
//champs spécifiques

if($this->form->has('custom_fields')){
	foreach ($this->form->get('custom_fields')->getElements() as $element){
		echo $this->customFieldGroup($element);
	}
}
?>
</div>
</div>
<div class="modal-footer">
<?php 

	echo $this->formSubmit($this->form->get('submit')); 
?>
<a id="cancel-form" class="btn" href="#" data-dismiss="modal" aria-hidden="true">Annuler</a>
</div>
<?php 
echo $this->form()->closeTag();
?>
<?php endif; ?>