<?php 
$this->headScript()->appendFile($this->basePath() . '/assets/js/antenna.js');
$this->headLink()->prependStylesheet($this->basePath() . '/assets/css/radio.css');

foreach ($this->frequencyColors as $status => $color) {
	$this->headLink()->appendStylesheet($this->basePath() . '/assets/css/radio-'.$status.'-'.$color.'.css');
}

?>


<input type="checkbox" class="main-nav-check" id="main-nav-check" />

<div class="main-nav panel-left" id="fiche" data-url="frequencies/getfiche"></div>
<div class="page-wrap">
<div class="container-fluid" id="radio">
	<div class="row">
		<div class="col-sm-9" id="frequencies">
			<?php
            $i = 0;
            foreach ($this->groups as $group) {
                if ($i % 2 == 0) {
                    echo "<div class='container-fluid'><div class='row'>";
                }
                $inner = "";
                $inner .= "<ul class=\"sector-list\">";
                foreach ($group->getSectors() as $sector) {
                    if ($sector->getFrequency() && ! $sector->getFrequency()->isDecommissionned()) {
                        $inner .= "<li>" . $this->sector($sector->getFrequency(), $sector->getName(), $group->getId()) . "</li>";
                    }
                }
                $inner .= "</ul>";
                echo "<div class='col-sm-6'>";
                echo $this->block($group->getName(), $inner);
                echo "</div>";
                if ($i % 2 == 1) {
                    echo "</div></div>";
                }
                $i ++;
            }
            if (count($other) > 0) {
                if ($i % 2 == 0) {
                    echo "<div class='container-fluid'><div class='row'>";
                }
                $inner = "";
                $inner .= "<ul class=\"sector-list\">";
                foreach ($other as $frequency) {
                    if (! $frequency->isDecommissionned()) {
                        $inner .= "<li>" . $this->sector($frequency, $frequency->getOthername()) . "</li>";
                    }
                }
                $inner .= "</ul>";
                echo "<div class='col-sm-6'>";
                echo $this->block("Autres fréquences", $inner);
                echo "</div>";
                if ($i % 2 == 1) {
                    echo "</div></div>";
                }
                $i ++;
            }
            if ($i % 2 == 1) {
                echo "</div></div>";
            }
            ?>	
		</div>
		<div class="col-sm-3">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title"><?php echo $this->translate('Antennas') ?></h3>
				</div>
				<div class="panel-body">
					<table id="antennas" class="table table-striped table-bordered table-hover sortable">
						<thead>
							<tr>
								<th data-sort="string" data-autosort="true">Nom</th>
								<th>État</th>
							</tr>
						</thead>
						<tbody>
							<?php
                            foreach ($this->antennas as $antennaid => $antenna) {
                                echo '<tr id="antenna-' . $antennaid . '" data-id="' . $antennaid . '" data-shortname="' . $antenna['shortname'] . '">';
                                echo '<td>' . $antenna['name'] . ' (' . $antenna['shortname'] . ') ';
                                echo '<a href="#" data-id="'.$antennaid.'" class="open-fiche"><span class="glyphicon glyphicon-tasks"></span></a>';
                                echo '</td>';
                                echo '<td>';
                                echo '<div class="togglebutton togglebutton-red">';
                                echo '<label>';
                                echo '<input
                                        id="switch_' . $antennaid . '"
                    					data-antennaid="' . $antennaid . '"
                    					data-antenna="' . $antenna['name'] . '"
                    					data-href="' . $this->url('application', array(
                                                                            'controller' => 'frequencies',
                                                                            'action' => 'switchantenna'
                                                                        ), array(
                                                                            'query' => array(
                                                                                'antennaid' => $antennaid
                                                                            )
                                                                        )) . '"
                    					class="antenna-switch"
                                        type="checkbox" ' . ($antenna['status'] ? 'checked="checked"' : '') . ($this->isGranted('events.write') ? '' : ' disabled="disabled"') . '>';
                                
                                echo '</label>';
                                echo '</div>';
                                
                                echo '</td>';
                                echo '</tr>';
                            }
                            ?>
						</tbody>
					</table>
				</div>
			</div>

		</div>
	</div>
</div>
</div>
<div id="popover-frequencies"></div>
<?php

echo $this->modalwindow("confirm-end-event", "<h4>Antenne <em><span id=\"antenna_name\"></span></em></h4>", "", null, "<p>Voulez-vous vraiment terminer l'évènement antenne en cours ?</p>
						<p>L'heure actuelle sera utilisée comme heure de fin.</p><div id='frequencies_impacted'></div>", "<button class=\"btn btn-danger\" id=\"end-antenna-href\">Confirmer</button>
						<button class=\"btn\" href=\"#\" id=\"cancel-antenna\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</button>");
?>

<?php
echo $this->modalwindow("fne-brouillage", "<h4>Fiche brouillage fréquence <em><span id=\"frequency_name\"></span></em></h4>", "", "<div id=\"form-brouillage\"></div>");

?>

<?php $this->inlineScript()->captureStart();?>

$("#home").removeClass("dropdown-toggle")
		  .attr('data-toggle', '')
		  .html('<span class="glyphicon glyphicon-home"></span> Évènements');
		  
$("#create-link").remove();

$("#create-evt").remove();

$("#zoomform").remove();

$('#search').remove();

antenna('<?php echo $this->url('application');?>', '<?php echo $this->frequencyTestMenu; ?>');

form('<?php echo $this->url('application');?>');

<?php $this->inlineScript()->captureEnd();?>
