<?php $this->headScript()->appendFile($this->basePath() . '/js/stupidtable.min.js')?>
<?php $this->headScript()->appendFile($this->basePath() . '/assets/js/antenna.js')?>

<div class="container-fluid">
	<div class="row-fluid">
		<div class="span9" id="frequencies">
			<?php 
			$i = 0;
			foreach ($this->groups as $group){
				if($i % 2 == 0){
					echo "<div class='row-fluid'>";
				}
				$inner = "";
				$inner .= "<ul class=\"sector-list\">";
				foreach ($group->getSectors() as $sector){
					if($sector->getFrequency()){
						$inner .= "<li>".$this->sector($sector->getFrequency(), $sector->getName())."</li>";
					}
				}
				$inner .= "</ul>";
				echo "<div class='span6'>";
				echo $this->block($group->getName(), $inner);
				echo "</div>";
				if($i % 2 == 1){
					echo "</div>";
				}
				$i++;
			}
			if(count($other) > 0) {
				if($i % 2 == 0){
					echo "<div class='row-fluid'>";
				}
				$inner = "";
				$inner .= "<ul class=\"sector-list\">";
				foreach ($other as $frequency){
					$inner .= "<li>".$this->sector($frequency, $frequency->getOthername())."</li>";
				}
				$inner .= "</ul>";
				echo "<div class='span6'>";
				echo $this->block("Autres fréquences", $inner);
				echo "</div>";
				echo "</div>";
			}
			?>	
		</div>
		<div class="span3">
			<div class="block">
				<div class="navbar navbar-inner block-header">
					<div class="muted pull-left">Antennes</div>
				</div>
				<div class="block-content collapse in">
					<div class="span12">
						<table id="antennas" class="table table-striped table-bordered sortable">
							<thead>
								<tr>
									<th data-sort="string">Nom</th>
									<th>État</th>
								</tr>
							</thead>
							<tbody>
								<?php 
								foreach ($this->antennas as $antennaid => $antenna){
									echo '<tr data-id="'.$antennaid.'">';
									echo '<td>'.$antenna['name'].'</td>';
									echo '<td>';
									
									echo	'<div id="switch_'.$antennaid.'"
												data-antennaid="'.$antennaid.'"
												data-antenna="'.$antenna['name'].'"
												data-href="'.$this->url('application',
																		array('controller'=>'frequencies', 'action' => 'switchantenna'),
																		array('query' => array('antennaid' => $antennaid))).'"
												class="antenna-switch make-switch switch-small"
												data-off="danger"
												data-on="success"
												data-on-label="OPE"
												data-off-label="HS"
												data-text-label="État">';
										echo '<input type="checkbox" '.($antenna['status'] ? 'checked="checked"' : '').
											($this->isGranted('events.write') ? '' : ' disabled="disabled"').
											'>';
									echo '</div>';
									
									echo '</td>';
									echo '</tr>';
								}
								?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
			
		</div>
	</div>
</div>

<?php echo $this->modalwindow("confirm-end-event", 
						"<h3>Antenne <em><span id=\"antenna_name\"></span></em></h3>",
						"",
						null,
						"<p>Voulez-vous vraiment terminer l'évènement antenne en cours ?</p>
						<p>L'heure actuelle sera utilisée comme heure de fin.</p>",
						"<a class=\"btn btn-danger\" id=\"end-antenna-href\">Confirmer</a>
						<a class=\"btn\" href=\"#\" id=\"cancel-antenna\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</a>");
?>

<?php $this->inlineScript()->captureStart();?>

$("#home").removeClass("dropdown-toggle")
		  .attr('data-toggle', '')
		  .html('<i class="icon-home"></i> Évènements');

$("#create-link").remove();		  

$("#zoom").remove();

$('#search').remove();
		  	  
$(".sortable").stupidtable();

$(".sortable").bind('aftertablesort', function(event, data){
	var th = $(this).find("th");
    th.find(".arrow").remove();
    var arrow = data.direction === "asc" ? "<i class=\"icon-arrow-down\"></i>" : "<i class=\"icon-arrow-up\"></i>";
    th.eq(data.column).append('<span class="arrow"> ' + arrow +'</span>');
});

$("#antennas th:first").trigger('click');

antenna('<?php echo $this->url('application');?>');

<?php $this->inlineScript()->captureEnd();?>
