<?php $this->headScript()->appendFile($this->basePath() . '/components/jquery-stupid-table/stupidtable.min.js')?>
<?php $this->headScript()->appendFile($this->basePath() . '/assets/js/antenna.js')?>

<div class="container-fluid" id="radio">
	<div class="row">
		<div class="col-sm-3 panel-left" id="fiche" style="margin-left: -23%; display: none"></div>
		<div class="col-sm-9" id="frequencies" style="margin-left: 0px">
			<?php
            $i = 0;
            foreach ($this->groups as $group) {
                if ($i % 2 == 0) {
                    echo "<div class='container-fluid'><div class='row'>";
                }
                $inner = "";
                $inner .= "<ul class=\"sector-list\">";
                foreach ($group->getSectors() as $sector) {
                    if ($sector->getFrequency() && ! $sector->getFrequency()->isDecommissionned()) {
                        $inner .= "<li>" . $this->sector($sector->getFrequency(), $sector->getName()) . "</li>";
                    }
                }
                $inner .= "</ul>";
                echo "<div class='col-sm-6'>";
                echo $this->block($group->getName(), $inner);
                echo "</div>";
                if ($i % 2 == 1) {
                    echo "</div></div>";
                }
                $i ++;
            }
            if (count($other) > 0) {
                if ($i % 2 == 0) {
                    echo "<div class='container-fluid'><div class='row'>";
                }
                $inner = "";
                $inner .= "<ul class=\"sector-list\">";
                foreach ($other as $frequency) {
                    if (! $frequency->isDecommissionned()) {
                        $inner .= "<li>" . $this->sector($frequency, $frequency->getOthername()) . "</li>";
                    }
                }
                $inner .= "</ul>";
                echo "<div class='col-sm-6'>";
                echo $this->block("Autres fréquences", $inner);
                echo "</div>";
                if ($i % 2 == 1) {
                    echo "</div></div>";
                }
                $i ++;
            }
            if ($i % 2 == 1) {
                echo "</div></div>";
            }
            ?>	
		</div>
		<div class="col-sm-3">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Antennes</h3>
				</div>
				<div class="panel-body">
					<table id="antennas" class="table table-striped table-bordered table-hover sortable">
						<thead>
							<tr>
								<th data-sort="string">Nom</th>
								<th>État</th>
							</tr>
						</thead>
						<tbody>
							<?php
                            foreach ($this->antennas as $antennaid => $antenna) {
                                echo '<tr id="antenna-' . $antennaid . '" data-id="' . $antennaid . '" data-shortname="' . $antenna['shortname'] . '">';
                                echo '<td>' . $antenna['name'] . ' (' . $antenna['shortname'] . ')</td>';
                                echo '<td>';
                                
                                echo '<div id="switch_' . $antennaid . '"
                    												data-antennaid="' . $antennaid . '"
                    												data-antenna="' . $antenna['name'] . '"
                    												data-href="' . $this->url('application', array(
                                    'controller' => 'frequencies',
                                    'action' => 'switchantenna'
                                ), array(
                                    'query' => array(
                                        'antennaid' => $antennaid
                                    )
                                )) . '"
                    												class="antenna-switch make-switch switch-small"
                    												data-off="danger"
                    												data-on="success"
                    												data-on-label="OPE"
                    												data-off-label="HS"
                    												data-text-label="État">';
                                echo '<input type="checkbox" ' . ($antenna['status'] ? 'checked="checked"' : '') . ($this->isGranted('events.write') ? '' : ' disabled="disabled"') . '>';
                                echo '</div>';
                                
                                echo '</td>';
                                echo '</tr>';
                            }
                            ?>
						</tbody>
					</table>
				</div>
			</div>

		</div>
	</div>
</div>
<div id="popover-frequencies"></div>
<?php

echo $this->modalwindow("confirm-end-event", "<h3>Antenne <em><span id=\"antenna_name\"></span></em></h3>", "", null, "<p>Voulez-vous vraiment terminer l'évènement antenne en cours ?</p>
						<p>L'heure actuelle sera utilisée comme heure de fin.</p>", "<a class=\"btn btn-danger\" id=\"end-antenna-href\">Confirmer</a>
						<a class=\"btn\" href=\"#\" id=\"cancel-antenna\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</a>");
?>

<?php
echo $this->modalwindow("fne-brouillage", "<h3>Fiche brouillage fréquence <em><span id=\"frequency_name\"></span></em></h3>", "", "<div id=\"form-brouillage\"></div>");

?>

<?php $this->inlineScript()->captureStart();?>

$("#home").removeClass("dropdown-toggle")
		  .attr('data-toggle', '')
		  .html('<span class="glyphicon glyphicon-home"></span> Évènements');
		  
$("#create-link").remove();

$("#create-evt").remove();

$("#zoomform").remove(); $('#search').remove();

$(".sortable").stupidtable();

$(".sortable").bind('aftertablesort', function(event, data){ 
	var th = $(this).find("th");
	th.find(".arrow").remove();
	var arrow = data.direction === "asc" ? "<span class=\"glyphicon glyphicon-arrow-down\"></span>" : "<span class=\"glyphicon glyphicon-arrow-up\"></span>";
	th.eq(data.column).append('<span class="arrow"> ' + arrow +'</span>');
});

$("#antennas th:first").trigger('click');

antenna('<?php echo $this->url('application');?>');

form('<?php echo $this->url('application');?>');

<?php $this->inlineScript()->captureEnd();?>
