<?php
$this->headScript()->appendFile($this->basePath() . '/assets/js/atfcm.js');
?>

<div class="container-fluid">
    <div class="row">
	<div class="col-md-9">
		<p></p>
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title">Régulations </h4>
			</div>
			<div class="panel-body">
				<table class="table table-striped sortable">
                                    <thead>
                                    <tr>
                                        <th>id</th>
                                        <th data-sort="string" data-autosort="true">Nom</th>
                                        <th>Couleur</th>
                                        <th>TVs</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                        <?php 
                                        foreach ($this->cats as $cat){
                                            echo '<tr>';
                                            echo '<td>'.$cat->getId().'</td>';
                                            echo '<td>'.$cat->getName().'</td>';
                                            echo "<td><span class=\"label\" style=\"background-color:".$cat->getColor()."\">".$cat->getColor()."</span></td>";
                                            echo '<td>'.$cat->getTvs().'</td>';
                                            echo '<td><a '
                                                    . 'href="#atfcm-container" '
                                                    . 'class="mod-atfcm" '
                                                    . 'data-id="'.$cat->getId().'" '
                                                    . 'data-name="'.$cat->getName().'" '
                                                    . 'title="Modifier" '
                                                    . 'data-toggle="modal"><span class="glyphicon glyphicon-pencil"></span></a></td>';
                                            echo '</tr>';
                                        }
                                        ?>
                                    </tbody>
                                </table>
			</div>
		</div>
	</div>
        <div class="col-md-3">
            <p></p>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">Aide</h4>
                </div>
                <div class="panel-body">
                    <p>Cette page permet de configurer les régulations affectées aux catégories de type "ATFCM".</p>
                    <p>Il est nécessaire de créer au préalable les catégories via <a href="<?php echo $this->url('administration', array('controller' => 'categories', 'action' => 'index'))?>">la page de configuration des catégories</a>.</p>
                    <p>La création d'un oglet spécifique doit se faire dans la page de configuration spécifique.</p>
                    <p>La récupération des données via NM B2B nécessite que la connexion soit préalablement configurée par l'administrateur technique.</p>
                </div>
            </div>
        </div>
    </div>

</div>

			
<?php echo $this->modalwindow("atfcm-container", "<h4 id=\"atfcm-title\"></h4>", "", "<div id=\"atfcm-form\"></div>") ?>


<?php $this->inlineScript()->captureStart();?>

atfcm('<?php echo $this->url('administration'); ?>');

<?php echo $this->notifications($this->messages); ?>
                                        
<?php $this->inlineScript()->captureEnd();?>
