<?php
$form = $this->form;
//TODO BOF
$form->add([
    'type' => \Zend\Form\Element\Checkbox::class,
    'name' => 'c-absclot',
    'options' => [
        'label' => 'Absence de clôture en sortie de zone',
        // 'use_hidden_element' => false,
        // 'checked_value' => 'good',
        // 'unchecked_value' => 'bad',
    ],
]);

$form->add([
    'type' => \Zend\Form\Element\Checkbox::class,
    'name' => 'c-nonclot',
    'options' => [
        'label' => 'Non-clôture en sortie de zone',
    ],
]);

// $form->add(	
// 	['name' => 'submit',
//     	'attributes' => [
//             'type' => 'submit',
//             'value' => 'Enregistrer',
//             'class' => 'btn btn-primary btn-small'
//         ]
//     ]);

$form->setAttribute('action', $this->url('application', array('controller'=>'flightplans', 'action'=>'save')));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

?>

<?=$this->form()->openTag($form) ?>

<div class="modal-body">
<?=$this->formHidden($form->get('id'))?>
<?=$this->controlGroup($form->get('aircraftid'))?>
<?=$this->controlGroup($form->get('typeavion'))?>
<?=$this->controlGroup($form->get('startterrain'))?>
<?=$this->controlGroup($form->get('destinationterrain'))?>
<?=$this->controlGroup($form->get('estimatedtimeofarrival'), [
                                                        'class'=>'', 
                                                        'labelclass' => 'time-middle', 
                                                        'large' => false
                                                    ])?>
<?=$this->controlGroup($form->get('timeofarrival'), [
                                                        'class'=>'',
                                                        'labelclass' => 'time-middle', 
                                                        'large' => false
                                                    ])?>

<?=$this->controlGroup($form->get('typealerte'))?>
<?=$this->controlGroup($form->get('c-absclot'))?>
<?=$this->controlGroup($form->get('c-nonclot'))?>
<?=$this->controlGroup($form->get('comment'))?>
</div>

<div class="modal-footer">
<?php //echo $this->formSubmit($form->get('submit'))?>
</div>    

<?=$this->form()->closeTag() ?>