<?php 
if (count($flightplans) == 0) echo "Pas de plan de vol pour cette journée.";
else {
?> 

<thead>
	<tr>
	<?php foreach ($fields as $field) : ?>
		<th <?php echo ($field == 'Aircraft-Id') ? 'data-sort="string"' : ''; ?>><?php echo $field; ?></th>
	<?php endforeach; ?>
		<th>Début</th>
		<th>Fin</th>
		<th></th>
	</tr>
</thead>

<tbody id = "list-fp">
<?php foreach ($flightplans as $fp) : ?>
	<tr>
	    <?php foreach ($fields as $field) : ?>
	    <td>
	    <?php
	    if ($field == 'Aircraft-Id') $airId = $fp[$field];
	    if ($field == 'Alerte') 
	    {
	    	$tAlertes = ['INCERFA', 'ALERTFA', 'DETRESSFA'];
	    	$bAlertes = ['info', 'warning', 'danger'];

	    	foreach ($tAlertes as $index => $alt) 
	    	{
	    		$act = '';
				$title = (isset($fp['Cause'])) ? $fp['Cause'] : '';
	    		if(isset($fp['Type']) && $alt == $fp['Type']) {
	    			
	    			$act = 'active-alt';
	    		} 	
		    	?>
		        <a title="<?php echo $title; ?>"" class="a-trig-alt <?php echo $act; ?>" href="#mdl-trig-fp" data-id="<?php echo $fp['id']; ?>" data-air-id="<?php echo $airId; ?>" data-type="<?php echo $alt;?>" data-toggle="modal">
		        	<button class="btn btn-xs btn-<?php echo $bAlertes[$index]; ?>"><?php echo $alt[0]; ?></button>
		        </a>
	        <?php
	    	}
	    } 
	    else
	    {
	        echo (isset($fp[$field])) ? $fp[$field] : '';
	    }
	    ?>
	    </td>
	    <?php endforeach; ?>
	    <td>
	    	<?php echo $fp['start_date']->format('H:i');; ?>
	    </td>

	    <td>
	    	<?php if (isset($fp['end_date'])) : ?>
	    	<?php echo $fp['end_date']->format('H:i'); ?>
	    	<?php else: ?>
	    	<a class="a-trig-end" data-id="<?php echo $fp['id']; ?>" href="#">clore</a>
	    	<?php endif; ?>
	    </td>
	    <td id="list-fp">
	        <a class="modify-evt" data-id="<?php echo $fp['id']; ?>"><span class="glyphicon glyphicon-pencil"></span></a>
	    </td>
	</tr>
<?php endforeach; ?>
</tbody>
<?php 
} 
?>