<?php
$this->headScript()->appendFile($this->basePath() . '/components/jquery-form/jquery.form.js');
$this->headScript()->appendFile($this->basePath() . '/assets/js/headerbar.js');
$this->headScript()->appendFile($this->basePath() . '/assets/js/notams.js');
$this->headScript()->appendFile($this->basePath() . '/assets/js/flightplan.js');
$this->headLink()->prependStylesheet($this->basePath() . '/assets/css/form.css');
$this->headLink()->prependStylesheet($this->basePath() . '/assets/css/afis.css');
$this->headLink()->prependStylesheet($this->basePath() . '/assets/css/flightplan.css');
?>

<?php
if( $this->hasAccess && $this->isGranted('flightplans.read') && (
    $this->isGranted('events.create') ||
    $this->isGranted('events.write')
    )
):
?>

<div id="create-evt" data-toggle="modal" data-backdrop="static" class="modal fade in" data-spy="affix" data-offset-top="80">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="loading"></div>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="form-title">Nouvel évènement</h4>
            </div>
            <div id="event">
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <?php if(count($alertcats) == 0): ?>
    <p class="text-warning">Aucune catégorie d'événement 'Alerte' n'existe, impossible de continuer.</p>
    <?php else: ?>

    <?php if(count($cats) == 0): ?>
    <p class="text-warning">Aucune catégorie d'événement 'Plan de Vol' n'existe, impossible de continuer.</p>
    <?php else: ?>

    <div class="row col-sm-10 col-sm-offset-1">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class='row'>
                    <div class='col-md-4'>
                        <a href="#" id="a-date-back">
                            <span class="glyphicon glyphicon-backward"></span>
                        </a>

                        <input id="i-date" type="text" class="date input-small" />

                        <a href="#" id="a-date-forward">
                            <span class="glyphicon glyphicon-forward"></span>
                        </a>
                        <a href="#" id="a-date-today">
                            <span class="glyphicon glyphicon-refresh"></span>
                        </a>
                    </div>
                    <div class="checkbox col-md-4 fp-filter">
                        <label>
                            <input class="form-control" type='checkbox' name='hide-ended-fp' />
                            <span class="checkbox-material"></span>
                            Cacher les vols clos
                        </label>
                    </div>
                    <div class="checkbox col-md-4 fp-filter">
                        <label>
                            <input class="form-control" type='checkbox' name='hide-ended-alt' />
                            <span class="checkbox-material"></span>
                            Cacher les alertes closes
                        </label>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-body" id="pan-show-fp">

            <?php if (count($flightplans) == 0 && count($flightplansWAlt) == 0) : ?>
            <div class="alert alert-info">
                Aucun vol.
            </div>
            <?php else : ?>

            <?php if (count($flightplansWAlt) > 0) : ?>
            <h4>Vols en alerte</h4>
            <table class="table table-striped table-hover sortable">
                <thead>
                    <tr>
                        <th></th>
                        <?php
                        foreach ($fields as $field) {
                            echo "<th data-sort='string'>".$field."</th>";
                        }
                        ?>
                        <th></th>
                    </tr>
                </thead>
                <tbody id = "list-fp">
                <?php
                foreach ($flightplansWAlt as $fp) {
                    echo $this->flightPlanViewHelper()->renderFlightPlan($fp, $fields);
                }
                ?>
                </tbody>
            </table>
            <?php endif; ?>

            <?php if (count($flightplansWAlt) > 0) : ?>
            <h4>Vols sans alerte</h4>
            <?php endif; ?>
            <?php if (count($flightplans) > 0) : ?>
            <table class="table table-striped table-hover sortable">
                <thead>
                    <tr>

                    <?php
                    foreach ($fields as $field) {
                        echo "<th data-sort='string'>".$field."</th>";
                    }
                    ?>
                        <th></th>
                    </tr>
                </thead>
                <tbody id = "list-fp">
                <?php
                foreach ($flightplans as $fp) {
                    echo $this->flightPlanViewHelper()->renderFlightPlan($fp, $fields);
                }
                ?>
                </tbody>
            </table>
            <?php endif; ?>
            <?php endif; ?>

            </div>
        </div>
    </div>

     <?php endif; ?>
     <?php endif; ?>
</div>
<?php endif; ?>

<?php
echo $this->modalWindow(
    "mdl-hist-fp",
    "<h1 id='title-hist-fp'>Historique</h1>",
    "",
    null,
    "<div id='p-hist-fp'></div>",
    "<a class='btn btn-primary' href='#' data-dismiss='modal' aria-hidden='true'>Fermer</a>",
    "",
    ""
);
echo $this->modalWindow(
    "mdl-edit-fp",
    "<h3 id='title-edit-fp'></h3>",
    "",
    "<div id='f-edit-fp'></div>",
    "",
    "",
    "modal-lg"
);
echo $this->modalwindow(
    "mdl-del-fp",
    "<h3>Confirmer la suppression</h3>",
    "",
    null,
    "<p>Voulez-vous vraiment supprimer le vol <strong><span id ='s-del-fp-airid'></span></strong> ?</p>",
    "<a class='btn btn-danger' id='a-del-fp-ok'>Confirmer</a>
    <a class='btn' href='#' data-dismiss='modal' aria-hidden='true'>Annuler</a>");

echo $this->modalwindow(
    "mdl-trig-fp",
    "<h3>Déclenchement d'une phase d'alerte</h3>",
    "",
    null,
    "<div class='panel-body' id='f-trig-alt'></div>",
    "<a class='btn btn-danger' id='a-trig-alt-ok'>Confirmer</a>
    <a class='btn' href='#' data-dismiss='modal' aria-hidden='true'>Annuler</a>");

echo $this->modalwindow(
    "mdl-edit-alt",
    "<h3>Modification d'une phase d'alerte</h3>",
    "",
    null,
    "<div class='panel-body' id='f-edit-alt'></div>",
    "<a class='btn btn-danger' id='a-edit-alt-ok'>Confirmer</a>
    <a class='btn' href='#' data-dismiss='modal' aria-hidden='true'>Annuler</a>");

echo $this->modalwindow(
    "mdl-end-fp",
    "<h3>Cloture d'un plan de vol</h3>",
    "",
    null,
    "<p><input type='datetime' name='end-date'></p>
    <textarea name='note-end-fp' placeholder=\"Commentaire sur la cloture\" class=\"form-control t-causealt\"'></textarea>",
    "<a class='btn btn-danger' id='a-end-fp-ok'>Confirmer</a>
    <a class='btn' href='#' data-dismiss='modal' aria-hidden='true'>Annuler</a>");

echo $this->modalwindow(
    "mdl-reopen-fp",
    "<h3>Annulation de la clôture du plan de vol</h3>",
    "",
    null,
    "Confirmer la réouverture du plan de vol ?
    <textarea name='note-reopen-fp' placeholder='Commentaire' class='form-control'></textarea>",
    "<a class='btn btn-danger' id='a-reopen-fp-ok'>Confirmer</a>
    <a class='btn' href='#' data-dismiss='modal' aria-hidden='true'>Annuler</a>");

echo $this->modalwindow(
    "mdl-end-alt",
    "<h3>Clôture de l'alerte</h3>",
    "",
    null,
    "<p><input type='datetime' name='end-alt-date'></p>
    <textarea name='note-end-alt' placeholder=\"Commentaire sur la cloture\" class=\"form-control t-causealt\"'></textarea>",
    "<a class='btn btn-danger' id='a-end-alt-ok'>Confirmer</a>
    <a class='btn' href='#' data-dismiss='modal' aria-hidden='true'>Annuler</a>");

echo $this->modalwindow(
    "mdl-reopen-alt",
    "<h3>Annulation de la clôture de l'alerte</h3>",
    "",
    null,
    "Confirmer la réouverture de l'alerte ?
    <textarea name='note-reopen-alt' placeholder='Commentaire' class='form-control'></textarea>",
    "<a class='btn btn-danger' id='a-reopen-alt-ok'>Confirmer</a>
    <a class='btn' href='#' data-dismiss='modal' aria-hidden='true'>Annuler</a>");

echo $this->modalWindow(
    "mdl-show-not",
    "<h3 id='title-show-not'></h3>",
    "",
    null,
    "<div class='loading'></div>".
    '<div class="list-group" id="show-not">
        <div>
        <a data-toggle="collapse" data-parent="#show-not" href="">
        </a> <strong class="rapid-not-info"></strong>
        <p class="collapse">

        </p>
        <hr>
        </div>
    </div>',
    '<div><a id="refresh-not" class="btn btn-primary" href="#" aria-hidden="true">RAFRAICHIR</a><a class="btn btn-primary" href="#" data-dismiss="modal" aria-hidden="true">FERMER</a></div>',
    'modal-lg'
);
echo $this->modalwindow(
    "confirm-delete-file",
    "<h4>Confirmer la suppression du fichier ?</h4>",
    "",
    null,
    "<p>Voulez-vous vraiment supprimer le fichier <em><span id=\"file_name\"></span></em> ?</p>",
    "<button class=\"btn btn-danger\" id=\"delete-file-href\">Confirmer</button>
    <button class=\"btn\" href=\"#\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</button>");
;
echo $this->modalwindow(
    "add-file",
    "<h4>Ajout d'un fichier</h4>",
    "",
    "<div id=\"file-upload-form\"></div>"
    );

echo $this->modalwindow(
    "add-alarm",
	"<h3 id=\"alarm-title\">Ajout d'un mémo</h3>",
	"",
	"<div id=\"alarm-form\"></div>");

echo $this->modalwindow(
    'add-note-modal',
    "<h4>Ajout d'une note</h4>",
    "",
    "<form id=\"add-note\" class=\"form-horizontal\" action=\"<?php echo $this->url('application', array('controller' => 'events', 'action' => 'addnote'))?>\">"
    . "<div class=\"modal-body\">"
        . "<div class=\"form-group\">"
            . "<label class=\"control-label col-sm-2\">Contenu : </label>"
            . "<div class=\"col-sm-10\">"
                . "<textarea class=\"form-control\" name=\"new-update\" placeholder=\"Ajouter une note.\"></textarea>"
            . "</div>"
        . "</div>"
    . "</div>"
    . "<div class=\"modal-footer\">"
        . "<input type=\"submit\" class=\"btn btn-sm btn-primary\" value=\"Ajouter la note\"></input>"
    . "</div>"
    . "</form>");

echo $this->modalwindow(
    'add-postit-modal',
    "<h4>Ajout d'un postit</h4>",
    "",
    "<form id=\"add-postit\" class=\"form-horizontal\" action=\"<?php echo $this->url('application', array('controller' => 'events', 'action' => 'addpostit'))?>\">"
    . "<div class=\"modal-body\">"
    . "<div class=\"form-group\">"
    . "<label class=\"control-label col-sm-2\">Titre : </label>"
    . "<div class=\"col-sm-10\">"
    . "<input type='text' class=\"form-control\" name=\"name\" placeholder=\"Titre.\"></input>"
    . "</div>"
    . "</div>"
    . "<div class=\"form-group\">"
    . "<label class=\"control-label col-sm-2\">Contenu : </label>"
    . "<div class=\"col-sm-10\">"
    . "<textarea class=\"form-control\" name=\"content\" placeholder=\"Contenu.\"></textarea>"
    . "</div>"
    . "</div>"
    . "</div>"
    . "<div class=\"modal-footer\">"
    . "<input type=\"submit\" class=\"btn btn-sm btn-primary\" value=\"Enregistrer\"></input>"
    . "</div>"
    . "</form>");

$this->inlineScript()->captureStart();

if ($this->hasAccess && $this->isGranted('flightplans.write') && (
    $this->isGranted('events.create') ||
    $this->isGranted('events.write')
    ))
{

}
else
{
    echo '$("#create-link").hide();';
}

?>
$("#changeview").remove();
$('#search').remove();
$('input[name=hide-ended-fp]').prop('checked', <?php echo $this->filters['fp'] ?>)
$('input[name=hide-ended-alt]').prop('checked', <?php echo $this->filters['alt'] ?>)
<?php
if($this->cats) {
    $catsString = "";
    $i = 0;
    foreach ($this->cats as $cat) {
        if(strlen($catsString) > 0) {
            $catsString .= "&";
        }
        $catsString .= 'cats[' . $i . ']=' . $cat;
        $i++;
    }
    echo 'cats = "'.$catsString.'";';
} else {
    echo 'cats = null;';
}
?>
//init form
form('<?php echo $this->url('application');?>', cats);

flightplan('<?php echo $this->url('application'); ?>', '<?php echo $this->current_date; ?>');

<?php echo $this->notifications($this->messages); ?>

<?php $this->inlineScript()->captureEnd(); ?>
