<?php 
$this->headScript()->appendFile($this->basePath() . '/assets/js/jquery.ui.timeline.js');
$this->headScript()->appendFile($this->basePath() . '/components/jquery-form/jquery.form.js');
$this->headScript()->appendFile($this->basePath() . '/assets/js/fileupload.js');
$this->headScript()->appendFile($this->basePath() . '/assets/js/search.js');
$this->headScript()->appendFile($this->basePath() . '/assets/js/flightplan.js');
$this->headLink()->prependStylesheet($this->basePath() . '/assets/css/form.css');
$this->headLink()->prependStylesheet($this->basePath() . '/assets/css/flightplan.css');
?>

<?php if($this->isGranted('events.create') || $this->isGranted('events.write')):?>
    <div id="create-evt" data-toggle="modal" data-backdrop="static" class="modal fade in" data-spy="affix" data-offset-top="80">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="loading"></div>
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="form-title">Nouvel évènement</h4>
                </div>
                <div id="event">
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>


<div class="container-fluid">
    <div class="row col-sm-10 col-sm-offset-1">
        <div class="panel panel-default">
            <?php if($cat == 0): ?>
            <p class="text-warning">Aucun catégorie Plan de vol n'existe, impossible de continuer.</p>
            <?php endif; ?>
            <div class="panel-heading">
                <div>
                    <a href="#" id="a-date-back">
                        <span class="glyphicon glyphicon-backward"></span>
                    </a>

                    <input id="i-date" type="text" class="date input-small"></input>

                    <a href="#" id="a-date-forward">
                        <span class="glyphicon glyphicon-forward"></span>
                    </a>
                    <a href="#" id="a-date-today">
                        <span class="glyphicon glyphicon-refresh"></span>
                    </a>
                </div>
            </div>
            <div class="panel-body">
                <table class="table table-striped table-hover sortable nosar">

                </table>
            </div>
        </div>
    </div>

    <div class="row col-sm-10 col-sm-offset-1">
        <div class="panel panel-default">
            <div class="panel-body">
                <table class="table table-striped table-hover sortable sar">

                </table>
            </div>
        </div>
    </div>
</div>

<?=$this->modalWindow(  "mdl-edit-fp", 
                        "<h4 id='title-edit-fp'></h4>",
                        "", 
                        "<div id='f-edit-fp'></div>",
                        "",
                        "",
                        "modal-lg"); ?>

<?=$this->modalwindow(  "mdl-del-fp",
                        "<h3>Confirmer la suppression ?</h3>",
                        "", 
                        null, 
                        "<p>Voulez-vous vraiment supprimer le vol <em><span id ='s-del-fp-airid'></span></em> ?</p>",
                        "<a class='btn btn-danger' id='a-del-fp-ok'>Confirmer</a>
                        <a class='btn' href='#' data-dismiss='modal' aria-hidden='true'>Annuler</a>") ?>

<?=$this->modalwindow(  "mdl-trig-fp",
                        "<h3>Déclencher une alerte ?</h3>",
                        "", 
                        null, 
                        "<p>Voulez-vous vraiment déclencher une alerte de type <em><span id ='s-trig-alt'></span></em> pour le vol <em><span id ='s-trig-airid'></span></em>?</p><textarea id = 't-causealt'></textarea>" ,
                        "<a class='btn btn-danger' id='a-trig-alt-ok'>Confirmer</a>
                        <a class='btn' href='#' data-dismiss='modal' aria-hidden='true'>Annuler</a>") ?>

<?=$this->modalwindow(  "mdl-end-fp",
                        "<h3>Clore <span id = 's-end-airid'></span></h3>",
                        "", 
                        null, 
                        "<input type='datetime' name='end-date'></input>",
                        "<a class='btn btn-danger' id='a-end-fp-ok'>Confirmer</a>
                        <a class='btn' href='#' data-dismiss='modal' aria-hidden='true'>Annuler</a>") ?>

<?php $this->inlineScript()->captureStart(); ?>

$("#home").removeClass("dropdown-toggle")
          .attr('data-toggle', '')
          .html('<span class="glyphicon glyphicon-home"></span> Évènements');

if (<?php echo $cat; ?> == 0) {
    $("#create-link").hide();
} else {
    $("#create-link")
        .hide()
        .clone(true)
        .show()
        .prependTo('.content')
        .data('id', <?php echo $cat; ?>)
        .addClass('category');
}

$("#changeview").remove();

$("#zoomform").remove();

$('#search').remove();

$(".sortable").stupidtable();

$(".sortable").bind('aftertablesort', function(event, data){
    var th = $(this).find("th");
    th.find(".arrow").remove();
    var arrow = data.direction === "asc" ? "<span class=\"glyphicon glyphicon-arrow-down\"></span>" : "<span class=\"glyphicon glyphicon-arrow-up\"></span>";
    th.eq(data.column).append('<span class="arrow"> ' + arrow +'</span>');
});

//sort the table by name
$("table th:first").trigger('click');

//init form
form('<?php echo $this->url('application');?>', 'timeline');

flightplan('<?php echo $this->url('application'); ?>');

<?php $this->inlineScript()->captureEnd(); ?>