<?php $this->headScript()->appendFile($this->basePath() . '/components/jquery-stupid-table/stupidtable.min.js')?>
<?php $this->headScript()->appendFile($this->basePath() . '/assets/js/radars.js')?>
    
    
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <p></p>
                
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title" id="reflex">Fiches réflexes des radars </h4>
                    </div>
                    <div class="panel-body">
                        <table class="table table-striped sortable">
                            <thead>
                            <tr>
                                <th data-sort="string">Radar</th>
                                <th>Fiche réflexe</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            foreach ($this->radars as $radar){
                                echo '<tr>';
                                echo '<td data-id="'.$radar->getId().'">'.$radar->getName().'</td>';
                                echo '<td>'.($radar->getModel() ? $radar->getModel()->getName() : 'Aucun modèle associé.').'</td>';
                                echo '<td><a href="#model-container" '
                                    . 'data-toggle="modal" '
                                    . 'data-name="'.$radar->getName().'" '
                                    . 'data-id="'.$radar->getId().'" '
                                    . 'class="change-model"><span class="glyphicon glyphicon-pencil"></span></a></td>';
                                echo '</tr>';
                            }
                            ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

<?php echo $this->modalwindow("model-container", "<h4 id=\"model-title\"></h4>", "", "<div id=\"model-form\"></div>") ?>

<?php $this->inlineScript()->captureStart();?>
    
    $('.sidenav').affix();
    
    radars('<?php echo $this->url('administration'); ?>');

<?php echo $this->notifications($this->messages); ?>

<?php $this->inlineScript()->captureEnd();?>