

<?php
$this->form->setAttribute('action', $this->url('administration', array('controller'=>'switchobjects', 'action'=>'savecategory')));
$this->form->setAttribute('class', 'form-horizontal');
$this->form->prepare();

echo $this->form()->openTag($this->form);
?>
<div class="modal-body">
    <?php


    echo $this->formHidden($this->form->get('id'));

    echo $this->controlGroup($this->form->get('name'));

    ?>

    <div class="form-group">
        <label class="control-label col-sm-3" for="objects">Objets : </label>
        <div class="col-sm-9 col-lg-8">
            <div class="row">
                <div class="col-sm-6">
                    Objets :
                    <ul id="objects" class="list-group" style="min-height:50px">
                        <?php
                        foreach ($this->objects as $object) {
                            echo '<li class="list-group-item shadow-z-1" id="objects_'.$object->getId().'">';
                            echo ($object->getParent() ? ' > '.$object->getParent()->getName().' ': '').$object->getName().'</li>';
                        }
                        ?>
                    </ul>
                </div>
                <div class="col-sm-6">
                    Objets disponibles :
                    <ul id="availableobjects" class="list-group" style="min-height: 100px">
                        <?php
                        foreach ($this->availableobjects as $object){
                            echo '<li class="list-group-item shadow-z-1" id="objects_'.$object->getId().'">';
                            echo ($object->getParent() ? ' > '.$object->getParent()->getName().' ': '').$object->getName().'</li>';
                        }
                        ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>

</div>
<div class="modal-footer">
    <?php

    echo $this->formSubmit($this->form->get('submit'));
    ?>
    <button id="cancel-form" class="btn" href="#" data-dismiss="modal" aria-hidden="true">Annuler</button>
</div>
<?php
echo $this->form()->closeTag();
?>
