<?php $this->headScript()->appendFile($this->basePath() . '/assets/js/switchobjects.js')?>
<?php 

	function trObject($object, $deleteUrl, $decommissionurl = null){
		echo '<tr>';
		echo '<td>'.$object->getId().'</td>';
		echo '<td>'.$object->getName().'</td>';
		echo '<td>'.$object->getShortname().'</td>';
		echo '<td>'.$object->getOrganisation()->getName().'</td>';
		echo '<td>'.($object->getParent() ? $object->getParent()->getName() : '').'</td>';
		echo '<td>';
		echo "<a
				title=\"Modifier\"
				href=\"#object-container\"
				class=\"mod-object\"
				data-id=\"".$object->getId()."\"
				data-name=\"".$object->getName()."\"
				data-type=\"".$object->getType()."\"
				data-toggle=\"modal\"><span class=\"glyphicon glyphicon-pencil\"></span></a>  ";
		if($decommissionurl) {
            echo "<a
				title=\"Archiver\"
				href=\"#confirm-decommission-object\"
				data-href=\"" . $decommissionurl . "\"
				class=\"decommission-object\"
				data-id=\"" . $object->getId() . "\"
				data-name=\"" . $object->getName() . "\"
				data-toggle=\"modal\"><span class=\"glyphicon glyphicon-hdd\"></span></a>  ";
        }
		echo "<a
				title=\"Supprimer\"
				href=\"#confirm-delete-object\"
				data-href=\"".$deleteUrl."\"
				class=\"delete-object\"
				data-id=\"".$object->getId()."\"
				data-name=\"".$object->getName()."\"
				data-toggle=\"modal\"><span class=\"glyphicon glyphicon-trash\"></span></a>";
		echo '</td>';
		echo '</tr>';
	}
?>

<div class="container-fluid">
	<div class="row">
		<div class="col-md-3" id="sidebar">
			<ul class="nav sidenav">
          <?php
          $index = 1;
          foreach ($this->types as $type) {
            echo '<li><a href="#'.preg_replace("/[^a-zA-Z]/", "", $type).'">'.$index++.'. '.$type.'</a></li>';
          }
          foreach ($this->types as $type) {
              echo '<li><a href="#old'.preg_replace("/[^a-zA-Z]/", "", $type).'">'.$index++.'. Anciens '.$type.'</a></li>';
          }
          ?>
			</ul>
		</div>
		<div class="col-md-6">
			<p></p>
        <?php
        if(count($this->types) == 0) {
          echo "<p> Aucun objet existant : ";
            echo '<a class="btn btn-xs btn-primary add-object" href="#object-container" data-toggle="modal"  data-type="">Créer un objet</a></p>';
        }

        $index = 1;
        foreach ($this->types as $type) {
          echo '<div class="panel panel-default">';
          echo '<div class="panel-heading">';
          echo '<h4 class="panel-title" id="'.preg_replace("/[^a-zA-Z]/", "", $type).'">'.$index++.'. '.$type.' en service</h4>';
          echo '</div>';
          echo '<div class="panel-body">';
          echo '<table class="table table-striped sortable">';
          echo '<thead>
                        	<tr>
                        		<th data-sort="int">id</th>
                        		<th data-sort="string" data-autosort="true">Nom</th>
                        		<th data-sort="string">Nom court</th>
                        		<th>Organisation</th>
                        		<th>Parent</th>
                        		<th><a class="btn btn-xs btn-primary add-object" href="#object-container" data-toggle="modal"  data-type="'.$type.'">Ajouter</a></th>
                        	</tr>
                   </thead>
                   <tbody>';
          $objects = $this->repo->findBy(array('type'=>$type, 'decommissionned'=>false), array('name'=>'ASC'));
          foreach ($objects as $object){
            trObject(
                $object,
                    $this->url('administration', array('controller'=>'switchobjects', 'action'=>'delete'), array('query'=>array('id'=>$object->getId()))),
                    $this->url('administration', array('controller'=>'switchobjects', 'action'=>'decommission'), array('query'=>array('id'=>$object->getId())))
            );
          }
          echo '</tbody>
                </table>
				        </div>
			        </div>';
        }

        foreach ($this->types as $type) {
            echo '<div class="panel panel-default">';
            echo '<div class="panel-heading">';
            echo '<h4 class="panel-title" id="old'.preg_replace("/[^a-zA-Z]/", "", $type).'">'.$index++.'. Anciens '.$type.'</h4>';
            echo '</div>';
            echo '<div class="panel-body">';
            echo '<table class="table table-striped sortable">';
            echo '<thead>
                        	<tr>
                        		<th data-sort="int">id</th>
                        		<th data-sort="string" data-autosort="true">Nom</th>
                        		<th data-sort="string">Nom court</th>
                        		<th>Organisation</th>
                        		<th>Parent</th>
                        		<th></th>
                        	</tr>
                   </thead>
                   <tbody>';
            $objects = $this->repo->findBy(array('type'=>$type, 'decommissionned'=>true), array('name'=>'ASC'));
            foreach ($objects as $object){
                trObject(
                    $object,
                    $this->url('administration', array('controller'=>'switchobjects', 'action'=>'delete'), array('query'=>array('id'=>$object->getId())))
                );
            }
            echo ' </tbody>
                    </table>
				</div>
			</div>';
        }
        ?>


		</div>
    <div class="col-md-3">
      <p></p>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">Aide</h4>
        </div>
        <div class="panel-body">
          <p>Cette page permet de créer des objets possédant un statut On/Off qui peuvent ensuite être affichés sous la forme de liste de boutons commutables.</p>
          <p>Il est possible de définir un parent à un objet. Dans ce cas, l'activation d'un enfant aura pour conséquence l'activation du parent et la désactivation du parent désactivera tous les enfants.</p>
          <p>À noter :<ul><li>un enfant ne sera affiché que si son parent est aussi affiché ;</li><li>attention à ne pas configurer plusieurs niveaux, seuls les enfants directement rattachés à un parent sont affichés.</li></ul></p>
        </div>
      </div>
    </div>
	</div>
</div>

<?php echo $this->modalwindow("object-container", "<h3 id=\"object-title\">Nouvel objet</h3>", "", "<div id=\"object-form\"></div>")?>

<?php echo $this->modalwindow("confirm-delete-object",
						"<h4>Confirmer la suppression ?</h4>",
						"", 
						null,
                        "<div class=\"alert alert-warning\">La suppression définitive d'un objet impacte les évènements existants liés à cet objet."
                        ." Si des évènements liés à ce objet existent, il est préférable de l'archiver (<span class='glyphicon glyphicon-hand-right'></span> Modifier puis cocher la case Hors Service).</div>"
						."<p>Voulez-vous vraiment supprimer l'objet  <em><span class=\"object-name\"></span></em> ?</p>",
						"<a class=\"btn btn-danger\" id=\"delete-object-href\">Confirmer</a>
						<button class=\"btn\" href=\"#\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</button>") ?>

<?php echo $this->modalwindow("confirm-decommission-object",
    "<h4>Confirmer l'archivage ?</h4>",
    "",
    null,
    "<p>Voulez-vous vraiment archiver l'objet <em><span class=\"object-name\"></span></em> ?</p>",
    "<a class=\"btn btn-danger\" id=\"decommission-object-href\">Confirmer</a>
						<button class=\"btn\" href=\"#\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</button>") ?>

<?php $this->inlineScript()->captureStart();?>

$('.sidenav').affix();

$('body').scrollspy({target:'#sidebar', offset:120});

switchobjects('<?php echo $this->url('administration')?>');

<?php echo $this->notifications($this->messages); ?>

<?php $this->inlineScript()->captureEnd();?>