

<?php 
$this->form->setAttribute('action', $this->url('administration', array('controller'=>'tabs', 'action'=>'save')));
$this->form->setAttribute('class', 'form-horizontal');
$this->form->prepare();

echo $this->form()->openTag($this->form);
?>
<div class="modal-body">
<?php

echo $this->formHidden($this->form->get('id'));

echo $this->controlGroup($this->form->get('type'));

echo $this->controlGroup($this->form->get('name'));

echo $this->controlGroup($this->form->get('shortname'));

echo $this->controlGroup($this->form->get('place'));

echo $this->controlGroup($this->form->get('isDefault'));

echo $this->controlGroup($this->form->get('onlyroot'));

echo $this->controlGroup($this->form->get('horizontal'));

echo $this->controlGroup($this->form->get('categories'));

echo $this->controlGroup($this->form->get('readroles'));

?>

</div>
<div class="modal-footer">
<?php 
	echo $this->formSubmit($this->form->get('submit'));
?>
<button id="cancel-form" class="btn" href="#" data-dismiss="modal" aria-hidden="true">Annuler</button>
</div>
<?php 
echo $this->form()->closeTag();
?>
