<?php $this->headScript()->appendFile($this->basePath() . '/js/stupidtable.min.js');
      $this->headScript()->appendFile($this->basePath() . '/assets/js/tabs.js');
?>

<div class="container-fluid">
    <div class="row-fluid">
	<div class="span9">
		<div class="block">
			<div class="navbar navbar-inner block-header">
				<div class="muted pull-left">Onglets </div>
			</div>
			<div class="block-content collapse in">
				<div class="span12">
				<table class="table table-striped sortable">
                                    <thead>
                                    <tr>
                                        <th>id</th>
                                        <th data-sort="string">Nom</th>
                                        <th>Nom court</th>
                                        <th>Catégories associées</th>
                                        <th>Rôles autorisés</th>
                                        <th>Catégories racines seulement</th>
                                        <th><a class="btn btn-mini" href="#tab-container" data-toggle="modal" id="add-tab">Ajouter</a></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                        <?php 
                                        foreach ($this->tabs as $tab){
                                            echo '<tr>';
                                            echo '<td>'.$tab->getId().'</td>';
                                            echo '<td>'.$tab->getName().'</td>';
                                            echo '<td>'.$tab->getShortname().'</td>';
                                            echo '<td>';
                                            foreach ($tab->getCategories() as $cat){
                                            	echo $cat->getName().'<br/>';
                                            }
                                            echo '</td>';
                                            echo '<td>';
                                            foreach ($tab->getReadroles() as $role){
                                            	echo $role->getName().'<br/>';
                                            }
                                            echo '</td>';
                                            echo '<td><i class="'.($tab->isOnlyroot() ? 'icon-ok' : 'icon-remove' ).'"></i></td>';
                                            echo '<td><a '
                                                    . 'href="#tab-container" '
                                                    . 'class="mod-tab" '
                                                    . 'data-id="'.$tab->getId().'" '
                                                    . 'data-name="'.$tab->getName().'" '
                                                    . 'title="Modifier" '
                                                    . 'data-toggle="modal"><i class="icon-pencil"></i></a></td>';
                                            echo '</tr>';
                                        }
                                        ?>
                                    </tbody>
                                </table>
				</div>
			</div>
		</div>
	</div>
        <div class="span3">
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Aide</div>
                </div>
                <div class="block-content collapse in">
                    <p>Cette page permet de configurer de nouveaux onglets, positionnés après les onglets Radio et Radar.</p>
                    <p>Il est nécessaire de créer au préalable les catégories via <a href="<?php echo $this->url('administration', array('controller' => 'categories', 'action' => 'index'))?>">la page de configuration des catégories</a>.</p>
                </div>
            </div>
        </div>
    </div>

</div>

			
<?php echo $this->modalwindow("tab-container", "<h3 id=\"tab-title\"></h3>", "", "<div id=\"tab-form\"></div>") ?>


<?php $this->inlineScript()->captureStart();?>

tab('<?php echo $this->url('administration'); ?>');

$(".sortable").stupidtable();

$(".sortable").bind('aftertablesort', function(event, data){
	var th = $(this).find("th");
    th.find(".arrow").remove();
    var arrow = data.direction === "asc" ? "<i class=\"icon-arrow-down\"></i>" : "<i class=\"icon-arrow-up\"></i>";
    th.eq(data.column).append('<span class="arrow"> ' + arrow +'</span>');
});

$("table th:eq(1)").trigger('click');

<?php if (isset($this->messages['success'])) { ?>
	<?php foreach ($this->messages['success'] as $message) { ?>
		var n = noty({text:'<?php echo $message ?>', 
					type:'success',
					layout: 'bottomRight',});
	<?php }?>
<?php } ?>

<?php if (isset($this->messages['error'])) { ?>
	<?php foreach ($this->messages['error'] as $message) { ?>
		var n = noty({text:'<?php echo $message ?>', 
					type:'error',
					layout: 'bottomRight',});
	<?php }?>
<?php } ?>
                                        
<?php $this->inlineScript()->captureEnd();?>
