<?php $this->headScript()->appendFile($this->basePath() . '/assets/js/switchlist.js');
$this->headScript()->appendFile($this->basePath() . '/components/jquery-form/jquery.form.js');
$this->headScript()->appendFile($this->basePath() . '/assets/js/fileupload.js');
$this->headLink()->prependStylesheet($this->basePath() . '/assets/css/form.css');
?>
<?php
function addSwitchButton($name, $id, $helper, $inversed) {
  $html = '<div class="togglebutton togglebutton-red'.($inversed ? '-inversed' : '').'">';
  $html .= '<label>';
  $html .= '<input ';
	$html .= 'id="switch_'.$id.'" ';
	$html .= 'data-objectid="'.$id.'" ';
	$html .= 'data-object="'.$name.'" ';
	$html .= 'data-href="'.$helper->url('application',
                              array('controller'=>'switchlisttab', 'action' => 'switchobject'),
                             array('query' => array('objectid' => $id))).'" ';
	$html .= 'class="object-switch" type="checkbox" ';
  $html .=  ($helper->isGranted('events.write') ? '' : ' disabled="disabled"');
  $html .= '></label>';
  $html .= '</div>';
  return $html;
}
?>

<?php if($this->isGranted('events.create') || $this->isGranted('events.write')):?>
  <div id="create-evt" data-toggle="modal" data-backdrop="static" class="modal fade in" data-spy="affix" data-offset-top="80">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="loading"></div>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="form-title">Nouvel évènement</h4>
        </div>
        <div id="event">
        </div>
      </div>
    </div>
  </div>
<?php endif; ?>

<?php if( $this->switchobjects && $this->form) : ?>
<input type="checkbox" class="main-nav-check" id="main-nav-check" />

<div class="main-nav panel-left" id="fiche" data-url="/switchlisttab/getfiche"></div>
<div class="page-wrap">
    <div class="container-fluid" id="objects">
        <p></p>
        <div class="row" style="height: calc(100vh - 120px)">


            <div class="switch-content" style="flex-direction: <?php echo $this->direction; ?>">

                <?php
                function soCmp($a, $b) {
                  return $a->getPlace() - $b->getPlace();
                }
                $sortedSO = call_user_func(function(array $a){usort($a, "soCmp");return $a;}, $this->switchobjectsObjects);
                foreach ($sortedSO as $so) {
                  if($so->getParent() == null) {
                    echo '<div class="list-group switch-group">';
                    echo '<div class="list-group-item switchobject-line" id="object-'.$so->getId().'"><div class="switchobject-name">'.$so->getName();
                    echo ' <a href="#" data-id="'.$so->getId().'" class="open-fiche"><span class="glyphicon glyphicon-tasks"></span></a>';
                    echo ' <a href="#" data-id="'.$so->getId().'" class="modify-evt"><span class="glyphicon glyphicon-pencil"></span></a>';
                    echo '</div>';
                    echo '<div class="switchobject-button">'.addSwitchButton($so->getName(), $so->getId(), $this, $this->inversed).'</div>';
                    echo '</div>';
                    $children = call_user_func(function(array $a){usort($a, "soCmp");return $a;}, $so->getChildren()->toArray());
                    foreach ($children as $child) {
                      $found = array_filter($sortedSO, function($uniqueobject) use ($child){
                        return $uniqueobject->getId() == $child->getId();
                      });
                      if($found) {
                        echo '<div class="list-group-item switchobject-line" id="object-'.$child->getId().'"><div class="switchobject-name">';
                        echo ' > '.$child->getName();
                        echo' <a href="#" data-id="'.$child->getId().'" class="open-fiche"><span class="glyphicon glyphicon-tasks"></span></a>';
                        echo '</div>';
                        echo '<div class="switchobject-button">'.addSwitchButton($child->getName(), $child->getId(), $this, $this->inversed).'</div>';
                        echo "</div>";
                      }
                    }
                    echo "</div>";
                  }
                }
                ?>

            </div>

        </div>
    </div>
</div>
<?php else : ?>
<div class="alert alert-danger">
  Aucun objet ou aucune catégorie support configurée. Veuillez contacter votre administrateur.
</div>
<?php endif; ?>
<?php
if($this->switchobjects && $this->form) {
    $this->form->setAttribute('class', 'form-horizontal');
    $this->form->prepare();
    
    $form = $this->form()->openTag($this->form);
    
    $form .= '<div class="modal-body">';
    $form .= '<div id="message"></div>';
    foreach ($this->form->get('custom_fields')->getElements() as $element) {
        $form .= $this->controlGroup($element);
    }
    $form .= '</div>';
    $form .= '<div class="modal-footer">';
    $form .= '<button class="btn btn-danger" id="end-object-href" type="submit">Confirmer</button>';
    $form .= "<button class=\"btn\" href=\"#\" id=\"cancel-object\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</button>";
    
    $form .= '</div>';
    $form .= $this->form()->closeTag();
    
    
    echo $this->modalwindow("confirm-end-event",
        "<h3>Objet <em><span id=\"object_name\"></span></em></h3>",
        "",
        null,
        $form);
}
?>
<?php
echo $this->modalwindow(
"add-file",
"<h4>Ajout d'un fichier</h4>",
"",
"<div id=\"file-upload-form\"></div>"
);

echo $this->modalwindow("add-alarm",
"<h3 id=\"alarm-title\">Ajout d'un mémo</h3>",
"",
"<div id=\"alarm-form\"></div>");

echo $this->modalwindow('add-note-modal',
"<h4>Ajout d'une note</h4>",
"",
"<form id=\"add-note\" class=\"form-horizontal\" action=\"<?php echo $this->url('application', array('controller' => 'events', 'action' => 'addnote'))?>\">"
  . "<div class=\"modal-body\">"
    . "<div class=\"form-group\">"
      . "<label class=\"control-label col-sm-2\">Contenu : </label>"
      . "<div class=\"col-sm-10\">"
        . "<textarea class=\"form-control\" name=\"new-update\" placeholder=\"Ajouter une note.\"></textarea>"
        . "</div>"
      . "</div>"
    . "</div>"
  . "<div class=\"modal-footer\">"
    . "<input type=\"submit\" class=\"btn btn-sm btn-primary\" value=\"Ajouter la note\"></input>"
    . "</div>"
  . "</form>");
?>
<?php $this->inlineScript()->captureStart();?>

$("#create-link").hide();

$("#changeview").remove();

$('#search').remove();

switchlist('<?php echo $this->url('application'); ?>', '<?php echo $this->tabid; ?>');

<?php
if($this->cats) {
$catsString = "";
$i = 0;
foreach ($this->cats as $cat) {
if(strlen($catsString) > 0) {
$catsString .= "&";
}
$catsString .= 'cats[' . $i . ']=' . $cat;
$i++;
}
echo 'cats = "'.$catsString.'";';
} else {
echo 'cats = null;';
}
?>

form('<?php echo $this->url('application');?>', cats, <?php echo (int) $this->sunrise ?>, '<?php echo $this->url('application', array('controller' => "sunrisesunset")) ?>');

fileupload('<?php echo $this->url('application')?>');

<?php echo $this->notifications($this->messages); ?>

<?php $this->inlineScript()->captureEnd();?>
