<?php

$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('administration', array('controller'=>'users', 'action'=>'changepassword')));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');

?>

<?php echo $this->form()->openTag($form) ?>

<div class="modal-body">

<?php 

echo $this->formInput($form->get('id'));

echo $this->controlGroup($this->formLabel($form->get('newCredential')->setLabelAttributes(array('class' => 'control-label'))),
	$this->formInput($form->get('newCredential')) . $this->formElementErrors($form->get('newCredential')));

echo $this->controlGroup($this->formLabel($form->get('newCredentialVerify')->setLabelAttributes(array('class' => 'control-label'))),
	$this->formInput($form->get('newCredentialVerify')) . $this->formElementErrors($form->get('newCredentialVerify')));
?>
</div>

<div class="modal-footer">
<?php
echo $this->formSubmit($this->form->get('submit'));
?>
</div>

    
<?php echo $this->form()->closeTag() ?>
