<?php

$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('administration', array('controller'=>'users', 'action'=>'saveuser')));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');

?>

<?php echo $this->form()->openTag($form) ?>

<div class="modal-body">

<?php 

echo $this->formInput($form->get('id'));

echo $this->controlGroup($form->get('username'));

echo $this->controlGroup($form->get('displayName'));

echo $this->controlGroup($form->get('email'));

if(!$this->userid){
	echo $this->controlGroup($form->get('password'));
}
echo $this->controlGroup($form->get('userroles'));

echo $this->controlGroup($form->get('organisation'));

echo $this->controlGroup($form->get('zone'));

?>

</div>

<div class="modal-footer">
<?php
echo $this->formSubmit($this->form->get('submit'));
?>
</div>

    
<?php echo $this->form()->closeTag() ?>
