<?php $this->headScript()->appendFile($this->basePath() . '/js/stupidtable.min.js')?>
<?php $this->headScript()->appendFile($this->basePath() . '/js/users.js')?>

<table class="table table-striped sortable">
<thead>
	<tr>
		<th>id</th>
		<th data-sort="string">Nom</th>
		<th data-sort="string">Email</th>
		<th>Roles</th>
		<th><a class="btn btn-mini" href="#user-container" data-toggle="modal" id="add-user">Ajouter</a></th>
	</tr>
</thead>

<tbody>
	<?php 
	foreach ($this->users as $user){
		echo '<tr>';
		echo '<td>'.$user->getId().'</td>';
		echo '<td>'.$user->getUsername().'</td>';
		echo '<td>'.$user->getEmail().'</td>';
		echo '<td>';
			foreach($user->getRoles() as $role){
				echo $role->getName()." ";
			}
		echo '</td>';
		echo '<td>';
		echo "<a 
				title=\"Modifier\" 
				href=\"#user-container\" 
				class=\"mod-user\" 
				data-id=\"".$user->getId()."\" 
				data-name=\"".$user->getUsername()."\" 
				data-toggle=\"modal\"><i class=\"icon-pencil\"></i></a>  ";
		echo "<a 
				title=\"Supprimer\" 
				href=\"#confirm-delete-user\" 
				data-href=\"".$this->url('administration', array('controller'=>'users', 'action'=>'deleteuser'), array('query'=>array('id'=>$user->getId())))."\" 
				class=\"delete-user\" 
				data-id=\"".$user->getId()."\" 
				data-name=\"".$user->getUsername()."\" 
				data-toggle=\"modal\"><i class=\"icon-trash\"></i> </a>";
		echo '</td>';
		echo '</tr>';
	}
	?>
</tbody>

</table>

<?php echo $this->modalWindow("user-container", "<h3>Nouvel utilisateur</h3>", "", "<div id=\"user-form\"></div>")?>

<?php echo $this->modalwindow("confirm-delete-user",
						"<h3>Confirmer la suppression ?</h3>",
						"", 
						null, 
						"<p>Voulez-vous vraiment supprimer l'utilisateur <em><span id=\"user-name\"></span></em> ?</p>",
						"<a class=\"btn btn-danger\" id=\"delete-user-href\">Confirmer</a>
						<a class=\"btn\" href=\"#\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</a>") ?>	


<?php $this->inlineScript()->captureStart();?>

users('<?php echo $this->url('administration')?>');

$(".sortable").stupidtable();

$(".sortable").bind('aftertablesort', function(event, data){
	var th = $(this).find("th");
    th.find(".arrow").remove();
    var arrow = data.direction === "asc" ? "<i class=\"icon-arrow-down\"></i>" : "<i class=\"icon-arrow-up\"></i>";
    th.eq(data.column).append('<span class="arrow"> ' + arrow +'</span>');
});


<?php if (isset($this->messages['successMessages'])) { ?>
	<?php foreach ($this->messages['successMessages'] as $message) { ?>
		var n = noty({text:'<?php echo $message ?>', 
					type:'success',
					layout: 'bottomRight',});
	<?php }?>
<?php } ?>

<?php if (isset($this->messages['errorMessages'])) { ?>
	<?php foreach ($this->messages['errorMessages'] as $message) { ?>
		var n = noty({text:'<?php echo $message ?>', 
					type:'error',
					layout: 'bottomRight',});
	<?php }?>
<?php } ?>


<?php $this->inlineScript()->captureEnd();?>