

<?php 
$this->form->setAttribute('action', $this->url('administration', array('controller'=>'centre', 'action'=>'savegroup')));
$this->form->setAttribute('class', 'form-horizontal');
$this->form->prepare();

echo $this->form()->openTag($this->form);
?>
<div class="modal-body">
<?php


echo $this->formHidden($this->form->get('id'));

echo $this->controlGroup($this->form->get('zone'));

echo $this->controlGroup($this->form->get('name'));

?>

	<div class="form-group">
		<label class="control-label col-sm-3" for="sectors">Secteurs : </label>
		<div class="col-sm-9 col-lg-8">
			<div class="row">
				<div class="col-sm-6">
                    Secteurs :
                    <ul id="sectors" class="list-group">
                    <?php
                    foreach ($this->sectors as $sector) {
                        echo '<li class="list-group-item shadow-z-1" id="sectors_'.$sector->getId().'">'.$sector->getName().'</li>';
                    }
                    ?>
                    </ul>
				</div>
				<div class="col-sm-6">
                    Secteurs disponibles :
					<ul id="avalaiblesectors" class="list-group">
                        <?php
                        foreach ($this->avalaiblesectors as $sector){
                            echo '<li class="list-group-item shadow-z-1" id="sectors_'.$sector->getId().'">'.$sector->getName().'</li>';
                        }
                        ?>
                    </ul>
				</div>
			</div>
		</div>
	</div>

</div>
<div class="modal-footer">
<?php 

	echo $this->formSubmit($this->form->get('submit'));
?>
<button id="cancel-form" class="btn" href="#" data-dismiss="modal" aria-hidden="true">Annuler</button>
</div>
<?php 
echo $this->form()->closeTag();
?>
