

<?php 
$this->form->setAttribute('action', $this->url('administration', array('controller'=>'centre', 'action'=>'saveorganisation')));
$this->form->setAttribute('class', 'form-horizontal');
$this->form->prepare();

echo $this->form()->openTag($this->form);
?>
<div class="modal-body">
<?php


echo $this->formHidden($this->form->get('id'));

echo $this->controlGroup($this->form->get('name'));

echo $this->controlGroup($this->form->get('longname'));

echo $this->controlGroup($this->form->get('shortname'));

echo $this->controlGroup($this->form->get('address'));

echo $this->controlGroup($this->form->get('iponumber'));

echo $this->controlGroup($this->form->get('ipoemail'));

?>

  <div class="panel panel-default">
    <div class="panel-heading">Envoi d'email (facultatif, écrase les valeurs stockées dans le fichier de configuration)</div>
    <div class="panel-body">
        <?php
        echo $this->controlGroup($this->form->get('emailAccount'));
        echo $this->controlGroup($this->form->get('emailFrom'));
        echo $this->controlGroup($this->form->get('emailPassword'));
        ?>
    </div>
  </div>

</div>
<div class="modal-footer">
<?php 

	echo $this->formSubmit($this->form->get('submit'));
?>
<button id="cancel-form" class="btn" href="#" data-dismiss="modal" aria-hidden="true">Annuler</button>
</div>
<?php 
echo $this->form()->closeTag();
?>
