<?php $this->headScript()->appendFile($this->basePath() . '/js/stupidtable.min.js')?>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span7">
			<div class="block">
				<div class="navbar navbar-inner block-header">
					<div class="muted pull-left">Organisations </div>
				</div>
				<div class="block-content collapse in">
					<div class="span12">
					<table class="table table-striped sortable">
						<thead>
							<tr>
								<th data-sort="string">Id<span class="arrow"> <i class="icon-arrow-down"></i></span></th>
								<th data-sort="string">Nom</th>
								<th data-sort="string">Nom abrégé</th>
								<th>Adresse</th>
							</tr>
						</thead>
						<tbody>
							<?php 
							foreach ($this->centres as $centre){
								echo '<tr>';
									echo '<td>'.$centre->getId().'</td>';
									echo '<td>'.$centre->getName().'</td>';
									echo '<td>'.$centre->getShortname().'</td>';
									echo '<td>'.$centre->getAdress().'</td>';
								echo '</tr>';
							}							
							?>
						</tbody>
					</table>
					</div>
				</div>
			</div>
		</div>
		
		<div class="span5">
			<div class="block">
				<div class="navbar navbar-inner block-header">
					<div class="muted pull-left">Zones de qualifications</div>
				</div>
				<div class="block-content collapse in">
					<div class="span12">
					<table class="table table-striped sortable">
						<thead>
							<tr>
								<th data-sort="string">Id<span class="arrow"> <i class="icon-arrow-down"></i></span></th>
								<th data-sort="string">Organisation</th>
								<th data-sort="string">Nom</th>
								<th>Nom abrégé</th>
							</tr>
						</thead>
						<tbody>
							<?php 
							foreach ($this->qualifzones as $zone){
								echo '<tr>';
									echo '<td>'.$zone->getId().'</td>';
									echo '<td>'.$zone->getOrganisation()->getName().'</td>';
									echo '<td>'.$zone->getName().'</td>';
									echo '<td>'.$zone->getShortname().'</td>';
								echo '</tr>';
							}							
							?>
						</tbody>
					</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span6">
			<div class="block">
				<div class="navbar navbar-inner block-header">
					<div class="muted pull-left">Secteurs</div>
				</div>
				<div class="block-content collapse in">
					<div class="span12">En construction</div>
				</div>
			</div>
		</div>
		<div class="span6">
			<div class="block">
				<div class="navbar navbar-inner block-header">
					<div class="muted pull-left">Regroupements de secteurs</div>
				</div>
				<div class="block-content collapse in">
					<div class="span12">En construction</div>
				</div>
			</div>
		</div>
	</div>
</div>

<?php $this->inlineScript()->captureStart();?>

$(".sortable").stupidtable();

$(".sortable").bind('aftertablesort', function(event, data){
	var th = $(this).find("th");
    th.find(".arrow").remove();
    var arrow = data.direction === "asc" ? "<i class=\"icon-arrow-down\"></i>" : "<i class=\"icon-arrow-up\"></i>";
    th.eq(data.column).append('<span class="arrow"> ' + arrow +'</span>');
});

<?php $this->inlineScript()->captureEnd();?>