<?php $this->headScript()->appendFile($this->basePath() . '/assets/js/centre.js')?>

<div class="container-fluid">
	<div class="row">
		<div class="col-md-3" id="sidebar">
			<ul class="nav sidenav">
				<li>
					<a href="#Organisations">
						1. Organisations
					</a>
				</li>
				<li>
					<a href="#Zones">
						2. Zones de qualification
					</a>
				</li>
				<li>
					<a href="#Regroupements">
						3. Regroupements de secteurs
					</a>
				</li>
				<li>
					<a href="#Secteurs">
						4. Secteurs
					</a>
				</li>
				<li>
					<a href="#Attentes">
						5. Attentes
					</a>
				</li>
                <li>
                    <a href="#OldSecteurs">
                        6. Anciens secteurs
                    </a>
                </li>
                <li>
                    <a href="#OldAttentes">
                        7. Anciennes attentes
                    </a>
                </li>
			</ul>
		</div>
		<div class="col-md-9">
			<p></p>
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title" id="Organisations">1. Organisations </h4>
				</div>
				<div class="panel-body">
					<table class="table table-striped sortable">
						<thead>
							<tr>
								<th data-sort="int">Id</th>
								<th data-sort="string" data-autosort="true">Nom</th>
								<th data-sort="string">Nom abrégé</th>
								<th>Adresse</th>
                                <th>Numéro IPO</th>
                                <th>Email IPO</th>
								<th><a href="#organisation-container" id="add-organisation" data-toggle="modal" class="btn btn-xs btn-primary">Ajouter</a></th>
							</tr>
						</thead>
						<tbody>
							<?php 
							foreach ($this->centres as $centre){
								echo '<tr>';
									echo '<td>'.$centre->getId().'</td>';
									echo '<td>'.$centre->getName().'</td>';
									echo '<td>'.$centre->getShortname().'</td>';
									echo '<td>'.nl2br($centre->getAddress()).'</td>';
                                    echo '<td>'.$centre->getIpoNumber().'</td>';
                                    echo '<td>'.$centre->getIpoEmail().'</td>';
									echo "<td>";
										echo "<a 
												title=\"Modifier\"
												href=\"#organisation-container\"
												class=\"mod-organisation\"
												data-id=\"".$centre->getId()."\"
												data-name=\"".$centre->getName()."\" data-toggle=\"modal\"><span class=\"glyphicon glyphicon-pencil\"></span></a> ";
										echo "<a 
												title=\"Supprimer\"
												href=\"#confirm-delete-organisation\"
												data-href=\"".$this->url('administration', array('controller' => 'centre', 'action' => 'deleteorganisation'))."?id=".$centre->getId()."\"
												class=\"delete-organisation\"
												data-id=\"".$centre->getId()."\"
												data-name=\"".$centre->getName()."\" data-toggle=\"modal\"><span class=\"glyphicon glyphicon-trash\"></span> </a>";
									echo "</td>";
								echo '</tr>';
							}							
							?>
						</tbody>
					</table>
				</div>
			</div>

			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title" id="Zones">2. Zones de qualifications</h4>
				</div>
				<div class="panel-body">
					<table class="table table-striped sortable">
						<thead>
							<tr>
								<th data-sort="int">Id</th>
								<th data-sort="string">Organisation</th>
								<th data-sort="string" data-autosort="true">Nom</th>
								<th>Nom abrégé</th>
								<th><a href="#qualif-container" id="add-qualif" data-toggle="modal" class="btn btn-xs btn-primary">Ajouter</a></th>
							</tr>
						</thead>
						<tbody>
							<?php 
							foreach ($this->qualifzones as $zone){
								echo '<tr>';
									echo '<td>'.$zone->getId().'</td>';
									echo '<td>'.$zone->getOrganisation()->getName().'</td>';
									echo '<td>'.$zone->getName().'</td>';
									echo '<td>'.$zone->getShortname().'</td>';
									echo "<td>";
										echo "<a
												title=\"Modifier\"
												href=\"#qualif-container\"
												class=\"mod-qualif\"
												data-id=\"".$zone->getId()."\"
												data-name=\"".$zone->getName()."\" data-toggle=\"modal\"><span class=\"glyphicon glyphicon-pencil\"></span></a> ";
										echo "<a
												title=\"Supprimer\"
												href=\"#confirm-delete-qualif\"
												data-href=\"".$this->url('administration', array('controller' => 'centre', 'action' => 'deletequalif'))."?id=".$zone->getId()."\"
												class=\"delete-qualif\"
												data-id=\"".$zone->getId()."\"
												data-name=\"".$zone->getName()."\" data-toggle=\"modal\"><span class=\"glyphicon glyphicon-trash\"></span> </a>";
									echo "</td>";
								echo '</tr>';
							}							
							?>
						</tbody>
					</table>
				</div>
			</div>


			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title" id="Regroupements">3. Regroupements de secteurs</h4>
				</div>
				<div class="panel-body">
					<table class="table table-striped sortable">
						<thead>
							<tr>
								<th data-sort="int">Id</th>
								<th data-sort="string">Zone</th>
								<th data-sort="string" data-autosort="true">Nom</th>
								<th>Secteurs</th>
								<th><a href="#group-container" id="add-group" data-toggle="modal" class="btn btn-xs btn-primary">Ajouter</a></th>
							</tr>
						</thead>
						<tbody>
							<?php 
							foreach ($this->groups as $group){
								echo '<tr>';
									echo '<td>'.$group->getId().'</td>';
									echo '<td>'.$group->getZone()->getName().'</td>';
									echo '<td>'.$group->getName().'</td>';
									echo '<td>';
									foreach ($group->getSectors() as $sector){
										echo $sector->getName()." ";
									}
									echo '</td>';
									echo "<td>";
										echo "<a
												title=\"Modifier\"
												href=\"#group-container\"
												class=\"mod-group\"
												data-id=\"".$group->getId()."\"
												data-name=\"".$group->getName()."\" data-toggle=\"modal\"><span class=\"glyphicon glyphicon-pencil\"></span></a> ";
										echo "<a
												title=\"Supprimer\"
												href=\"#confirm-delete-group\"
												data-href=\"".$this->url('administration', array('controller' => 'centre', 'action' => 'deletegroup'))."?id=".$group->getId()."\"
												class=\"delete-group\"
												data-id=\"".$group->getId()."\"
												data-name=\"".$group->getName()."\" data-toggle=\"modal\"><span class=\"glyphicon glyphicon-trash\"></span> </a>";
									echo "</td>";
								echo '</tr>';
							}							
							?>
						</tbody>
					</table>
				</div>
			</div>

			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title" id="Secteurs">4. Secteurs</h4>
				</div>
				<div class="panel-body">
                    <?php
                    $alert = array();
                    foreach ($this->sectors as $sector){
                        if(!$sector->isDecommissionned() &&
                            (!$sector->getFrequency() || ($sector->getFrequency() && $sector->getFrequency()->isDecommissionned()))){
                            $alert[] = $sector->getName();
                        }
                    }
                    if(count($alert) > 0){
                        echo '<div class="alert alert-warning">';
                        echo "Attention : les secteurs suivants n'ont pas de fréquence associée ou la fréquence associée est hors service :";
                        foreach ($alert as $a) {
                            echo " ".$a;
                        }
                        echo '.</div>';
                    }
                    ?>
					<table class="table table-striped sortable">
						<thead>
							<tr>
								<th data-sort="int">Id</th>
								<th data-sort="string">Zone</th>
								<th data-sort="string" data-autosort="true">Nom</th>
								<th>Fréquence</th>
								<th>Regroupements</th>
								<th><a href="#sector-container" id="add-sector" data-toggle="modal" class="btn btn-xs btn-primary">Ajouter</a></th>
							</tr>
						</thead>
						<tbody>
							<?php 
							foreach ($this->sectors as $sector){
							    if(!$sector->isDecommissionned()) {
                                    echo '<tr>';
                                    echo '<td>' . $sector->getId() . '</td>';
                                    echo '<td>' . $sector->getZone()->getName() . '</td>';
                                    echo '<td>' . $sector->getName() . '</td>';
                                    echo '<td>' . ($sector->getFrequency() ? $sector->getFrequency()->getValue() : "") . '</td>';
                                    echo '<td>';
                                    foreach ($sector->getSectorsgroups() as $group) {
                                        echo $group->getName() . " ";
                                    }
                                    echo '</td>';
                                    echo "<td>";
                                    echo "<a
												title=\"Modifier\"
												href=\"#sector-container\"
												class=\"mod-sector\"
												data-id=\"" . $sector->getId() . "\"
												data-name=\"" . $sector->getName() . "\" data-toggle=\"modal\"><span class=\"glyphicon glyphicon-pencil\"></span></a> ";
                                    echo "<a
												title=\"Supprimer\"
												href=\"#confirm-delete-sector\"
												data-href=\"" . $this->url('administration', array(
                                            'controller' => 'centre',
                                            'action' => 'deletesector'
                                        )) . "?id=" . $sector->getId() . "\"
												class=\"delete-sector\"
												data-id=\"" . $sector->getId() . "\"
												data-name=\"" . $sector->getName() . "\" data-toggle=\"modal\"><span class=\"glyphicon glyphicon-trash\"></span> </a>";
                                    echo "</td>";
                                    echo '</tr>';
                                }
							}							
							?>
						</tbody>
					</table>
				</div>
			</div>
		
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title" id="Attentes">5. Attentes</h4>
				</div>
				<div class="panel-body">
					<table class="table table-striped sortable">
						<thead>
							<tr>
							<th data-sort="int">Id</th>
							<th data-sort="string" data-autosort="true">Nom</th>
							<th data-sort="string">Organisation</th>
							<th data-sort="string">Zone de qualification</th>
							<th><a href="#stack-container" class="btn btn-xs btn-primary" id="add-stack" data-toggle="modal">Ajouter</a></th>
							</tr>
						</thead>
						<tboby>
						<?php 
						foreach ($this->stacks as $stack){
                            if(!$stack->isDecommissionned()) {
                                echo "<tr>";
                                echo "<td>" . $stack->getId() . "</td>";
                                echo "<td>" . $stack->getName() . "</td>";
                                echo "<td>" . $stack->getZone()->getOrganisation()->getName() . "</td>";
                                echo "<td>" . $stack->getZone()->getName() . "</td>";
                                echo "<td>";
                                echo "<a
									title=\"Modifier\"
									href=\"#stack-container\"
									class=\"mod-stack\"
									data-id=\"" . $stack->getId() . "\"
									data-name=\"" . $stack->getName() . "\" data-toggle=\"modal\"><span class=\"glyphicon glyphicon-pencil\"></span></a> ";
                                echo "<a
									title=\"Supprimer\"
									href=\"#confirm-delete-stack\"
									data-href=\"" . $this->url('administration', array(
                                        'controller' => 'centre',
                                        'action' => 'deletestack'
                                    )) . "?id=" . $stack->getId() . "\"
									class=\"delete-stack\"
									data-id=\"" . $stack->getId() . "\"
									data-name=\"" . $stack->getName() . "\" data-toggle=\"modal\"><span class=\"glyphicon glyphicon-trash\"></span> </a>";
                                echo "</td>";
                                echo "</tr>";
                            }
						}
						?>
						</tboby>
					</table>
				</div>
			</div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title" id="OldSecteurs">6. Anciens secteurs</h4>
                </div>
                <div class="panel-body">
                    <table class="table table-striped sortable">
                        <thead>
                        <tr>
                            <th data-sort="int">Id</th>
                            <th data-sort="string">Zone</th>
                            <th data-sort="string" data-autosort="true">Nom</th>
                            <th>Fréquence</th>
                            <th>Regroupements</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        foreach ($this->sectors as $sector){
                            if($sector->isDecommissionned()) {
                                echo '<tr>';
                                echo '<td>' . $sector->getId() . '</td>';
                                echo '<td>' . $sector->getZone()->getName() . '</td>';
                                echo '<td>' . $sector->getName() . '</td>';
                                echo '<td>' . ($sector->getFrequency() ? $sector->getFrequency()->getValue() : "") . '</td>';
                                echo '<td>';
                                foreach ($sector->getSectorsgroups() as $group) {
                                    echo $group->getName() . " ";
                                }
                                echo '</td>';
                                echo "<td>";
                                echo "<a
												title=\"Modifier\"
												href=\"#sector-container\"
												class=\"mod-sector\"
												data-id=\"" . $sector->getId() . "\"
												data-name=\"" . $sector->getName() . "\" data-toggle=\"modal\"><span class=\"glyphicon glyphicon-pencil\"></span></a> ";
                                echo "<a
												title=\"Supprimer\"
												href=\"#confirm-delete-sector\"
												data-href=\"" . $this->url('administration', array(
                                        'controller' => 'centre',
                                        'action' => 'deletesector'
                                    )) . "?id=" . $sector->getId() . "\"
												class=\"delete-sector\"
												data-id=\"" . $sector->getId() . "\"
												data-name=\"" . $sector->getName() . "\" data-toggle=\"modal\"><span class=\"glyphicon glyphicon-trash\"></span> </a>";
                                echo "</td>";
                                echo '</tr>';
                            }
                        }
                        ?>
                        </tbody>
                    </table>
                </div>
            </div>
            
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title" id="OldAttentes">7. Anciennes attentes</h4>
                </div>
                <div class="panel-body">
                    <table class="table table-striped sortable">
                        <thead>
                        <tr>
                            <th data-sort="int">Id</th>
                            <th data-sort="string" data-autosort="true">Nom</th>
                            <th data-sort="string">Organisation</th>
                            <th data-sort="string">Zone de qualification</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tboby>
                            <?php
                            foreach ($this->stacks as $stack){
                                if($stack->isDecommissionned()) {
                                    echo "<tr>";
                                    echo "<td>" . $stack->getId() . "</td>";
                                    echo "<td>" . $stack->getName() . "</td>";
                                    echo "<td>" . $stack->getZone()->getOrganisation()->getName() . "</td>";
                                    echo "<td>" . $stack->getZone()->getName() . "</td>";
                                    echo "<td>";
                                    echo "<a
									title=\"Modifier\"
									href=\"#stack-container\"
									class=\"mod-stack\"
									data-id=\"" . $stack->getId() . "\"
									data-name=\"" . $stack->getName() . "\" data-toggle=\"modal\"><span class=\"glyphicon glyphicon-pencil\"></span></a> ";
                                    echo "<a
									title=\"Supprimer\"
									href=\"#confirm-delete-stack\"
									data-href=\"" . $this->url('administration', array(
                                            'controller' => 'centre',
                                            'action' => 'deletestack'
                                        )) . "?id=" . $stack->getId() . "\"
									class=\"delete-stack\"
									data-id=\"" . $stack->getId() . "\"
									data-name=\"" . $stack->getName() . "\" data-toggle=\"modal\"><span class=\"glyphicon glyphicon-trash\"></span> </a>";
                                    echo "</td>";
                                    echo "</tr>";
                                }
                            }
                            ?>
                        </tboby>
                    </table>
                </div>
            </div>
        </div>
	</div>
</div>

<?php echo $this->modalwindow("organisation-container", "<h4 id=\"organisation-title\"></h4>", "", "<div id=\"organisation-form\"></div>") ?>

<?php echo $this->modalwindow("confirm-delete-organisation",
						"<h4>Confirmer la suppression ?</h4>",
						"", 
						null, 
						"<p>Voulez-vous vraiment supprimer l'organisation <em><span id=\"organisation-name\"></span></em> ?</p>
						<p>Tous les éléments associés seront supprimés également (zones, secteurs, ...).</p>",
						"<a class=\"btn btn-danger\" id=\"delete-organisation-href\">Confirmer</a>
						<button class=\"btn\" href=\"#\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</button>") ?>
						
<?php echo $this->modalwindow("qualif-container", "<h4 id=\"qualif-title\"></h4>", "", "<div id=\"qualif-form\"></div>") ?>

<?php echo $this->modalwindow("confirm-delete-qualif",
						"<h4>Confirmer la suppression ?</h4>",
						"", 
						null, 
						"<p>Voulez-vous vraiment supprimer la zone de qualification <em><span id=\"qualif-name\"></span></em> ?</p>
						<p>Tous les éléments associés seront supprimés également (secteurs, ...).</p>",
						"<a class=\"btn btn-danger\" id=\"delete-qualif-href\">Confirmer</a>
						<button class=\"btn\" href=\"#\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</button>") ?>				

<?php echo $this->modalwindow("group-container", "<h4 id=\"group-title\"></h4>", "", "<div id=\"group-form\"></div>") ?>

<?php echo $this->modalwindow("confirm-delete-group",
						"<h4>Confirmer la suppression ?</h4>",
						"", 
						null, 
						"<p>Voulez-vous vraiment supprimer le regroupement de secteurs <em><span id=\"group-name\"></span></em> ?</p>",
						"<a class=\"btn btn-danger\" id=\"delete-group-href\">Confirmer</a>
						<button class=\"btn\" href=\"#\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</button>") ?>	

<?php echo $this->modalwindow("sector-container", "<h3 id=\"sector-title\"></h3>", "", "<div id=\"sector-form\"></div>") ?>

<?php echo $this->modalwindow("confirm-delete-sector",
						"<h4>Confirmer la suppression ?</h4>",
						"", 
						null,
                        "<div class=\"alert alert-warning\">La suppression définitive d'un secteur impacte les évènements existants liés à ce secteur."
                        ." Si des évènements liés à ce secteur existent, il est préférable de l'archiver (<span class='glyphicon glyphicon-hand-right'></span> Modifier puis cocher la case Hors Service).</div>"
                        ."<p>Voulez-vous vraiment supprimer le secteur <em><span id=\"sector-name\"></span></em> ?</p>",
						"<a class=\"btn btn-danger\" id=\"delete-sector-href\">Confirmer</a>
						<button class=\"btn\" href=\"#\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</button>") ?>	

<?php echo $this->modalwindow("stack-container", "<h4 id=\"stack-title\"></h4>", "", "<div id=\"stack-form\"></div>") ?>

<?php echo $this->modalwindow("confirm-delete-stack",
						"<h4>Confirmer la suppression ?</h4>",
						"", 
						null,
                        "<div class=\"alert alert-warning\">La suppression définitive d'une attente impacte les évènements existants liés à cette attente."
                        ." Si des évènements liés à cette attente existent, il est préférable de l'archiver (<span class='glyphicon glyphicon-hand-right'></span> Modifier puis cocher la case Hors Service).</div>"
						."<p>Voulez-vous vraiment supprimer l'attente <em><span id=\"stack-name\"></span></em> ?</p>",
						"<a class=\"btn btn-danger\" id=\"delete-stack-href\">Confirmer</a>
						<button class=\"btn\" href=\"#\" data-dismiss=\"modal\" aria-hidden=\"true\">Annuler</button>") ?>	

<?php $this->inlineScript()->captureStart();?>

$(".sidenav").affix();

$('body').scrollspy({target: '#sidebar', offset:120});

centre('<?php echo $this->url('administration'); ?>');

<?php echo $this->notifications($this->messages); ?>

<?php $this->inlineScript()->captureEnd();?>