<div class="container-fluid">
	<div class="row-fluid">
		<div class="span4">
			<div class="block">
				<div class="navbar navbar-inner block-header">
					<div class="muted pull-left">Graphique des évènements</div>
				</div>
				<div class="block-content collapse in">
					<div class="span12">TESET</div>
				</div>
			</div>
		</div>

		<div class="span8">
			<div class="block">
				<div class="navbar navbar-inner block-header">
					<div class="muted pull-left">Liste des évènements de la semaine</div>
				</div>
				<div class="block-content collapse in">
					<div class="span12">TESET</div>
				</div>
			</div>
		</div>
		
		
	</div>
</div>