

<?php 
$this->form->setAttribute('action', $this->url('application', array('controller'=>'events', 'action'=>'savealarm')));
$this->form->setAttribute('class', 'form-horizontal');
$this->form->prepare();

echo $this->form()->openTag($this->form);
?>
<div class="modal-body">
<?php


echo $this->formHidden($this->form->get('id'));

echo $this->formHidden($this->form->get('parent'));

echo $this->controlGroup($this->formLabel($this->form->get('startdate')->setLabelAttributes(array('class'=>'control-label time-middle'))),
			$this->formDateTimeEnhanced(true, "startalarm") . $this->formHidden($this->form->get('startdate')), array('class'=>'compact'));

foreach ($this->form->get('custom_fields')->getElements() as $element){
	echo $this->customFieldGroup($element);
}

?>
</div>
<div class="modal-footer">
<?php echo $this->formSubmit($this->form->get('submit')); ?>
<a id="cancel-form" class="btn" href="#" data-dismiss="modal" aria-hidden="true">Annuler</a>
</div>
<?php 
echo $this->form()->closeTag();
?>
