

<?php 
$this->form->setAttribute('action', $this->url('application', array('controller'=>'alarm', 'action'=>'save')));
$this->form->setAttribute('class', 'form-horizontal');
$this->form->prepare();

echo $this->form()->openTag($this->form);
?>
<div class="modal-body">
<?php


echo $this->formHidden($this->form->get('id'));

echo $this->formHidden($this->form->get('parent'));

echo $this->formHidden($this->form->get('punctual'));

echo $this->formHidden($this->form->get('category'));

echo $this->formHidden($this->form->get('status'));

echo $this->formHidden($this->form->get('organisation'));

echo $this->formHidden($this->form->get('impact'));

echo $this->formHidden($this->form->get('scheduled'));

echo $this->controlGroup($this->form->get('startdate'), array('class'=>'compact', 'labelclass' => 'time-middle'));

foreach ($this->form->get('custom_fields')->getElements() as $element){
	echo $this->controlGroup($element);
}

?>
</div>
<div class="modal-footer">
<div class="form-group">
<div class="col-lg-offset-6 col-lg-6 btn-wrapper">
<?php echo $this->formSubmit($this->form->get('submit')); ?>
<button id="cancel-form" class="btn" href="#" data-dismiss="modal" aria-hidden="true">Annuler</button>
</div>
</div>
</div>
<?php 
echo $this->form()->closeTag();
?>
