<?php echo $this->doctype(); ?>

<html lang="fr">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Epeires²'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/assets/css/application.css') 
                        ->prependStylesheet($this->basePath() . '/assets/css/admin.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/google_material_font.css')
                        ->prependStylesheet($this->basePath() . '/components/bootstrap-material-design/dist/css/ripples.min.css')
                        ->prependStylesheet($this->basePath() . '/components/bootstrap-material-design/dist/css/material-palette.min.css')
                        ->prependStylesheet($this->basePath() . '/components/bootstrap-material-design/dist/css/roboto.min.css')
                        ->prependStylesheet($this->basePath() . '/components/bootstrap/dist/css/bootstrap.min.css')
        				?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/assets/js/application.js')
                                      ->prependFile($this->basePath() . '/components/bootstrap/dist/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/components/noty/js/noty/packaged/jquery.noty.packaged.min.js')
                                      ->prependFile($this->basePath() . '/components/jquery-ui/jquery-ui.min.js')
                                      ->prependFile($this->basePath() . '/components/jquery/dist/jquery.min.js')
        							   ?>

    </head>
    <body>

	<?php echo $this->navbartop('red', null); ?>
	
	<div class="content">
		<div class="warnings">
		<?php if (isset($this->messages['successMessages'])) { ?>
			<?php foreach ($this->messages['successMessages'] as $message) { ?>
				<div class="alert alert-success">
					<a class="close" data-dismiss="alert" href="#">&times;</a>
					<?php echo $message ?>
				</div>
			<?php }?>
		<?php } ?>

		<?php if (isset($this->messages['errorMessages'])) { ?>
			<?php foreach ($this->messages['errorMessages'] as $message) { ?>
				<div class="alert alert-error">
					<a class="close" data-dismiss="alert" href="#">&times;</a>
					<?php echo $message ?>
				</div>
			<?php }?>
		<?php } ?>
		</div>
	
        <?php echo $this->content; ?>
    
    </div> <!-- /container -->
        
    <?php 
	if(!$this->zfcuserIdentity()){
			echo $this->modalWindow("loginwindow", "<h3>Connexion</h3>", "", $this->zfcUserLoginWidget(array('redirect'=>'application')));
	} ?>
        
    <?php echo $this->inlineScript() ?>
    </body>
</html>
