<?php echo $this->doctype(); ?>

<html lang="fr">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('PV CdS'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/application.css') 
                        ->prependStylesheet($this->basePath() . '/css/admin.css')
                        ->prependStylesheet($this->basePath() . '/css/spectrum.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui.min.css')
        				?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/application.js')
        							  ->prependFile($this->basePath() . '/js/spectrum.js')
        							  ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/noty/themes/default.js')
                                      ->prependFile($this->basePath() . '/js/noty/layouts/bottomRight.js')
                                      ->prependFile($this->basePath() . '/js/noty/jquery.noty.js')
                                      ->prependFile($this->basePath() . '/js/jquery-ui.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js')
        							   ?>

    </head>
    <body>
    	<div class="header">
    		<ul class="inline">
    				<?php echo $this->userMenu(); ?>
    				<li id="clock" class="pull-right"></li>
    		</ul>
    	</div>
	
	
	<div class="content">
		<div class="warnings">
		<?php if (isset($this->messages['successMessages'])) { ?>
			<?php foreach ($this->messages['successMessages'] as $message) { ?>
				<div class="alert alert-success">
					<a class="close" data-dismiss="alert" href="#">&times;</a>
					<?php echo $message ?>
				</div>
			<?php }?>
		<?php } ?>

		<?php if (isset($this->messages['errorMessages'])) { ?>
			<?php foreach ($this->messages['errorMessages'] as $message) { ?>
				<div class="alert alert-error">
					<a class="close" data-dismiss="alert" href="#">&times;</a>
					<?php echo $message ?>
				</div>
			<?php }?>
		<?php } ?>
		</div>
	
        <?php echo $this->content; ?>
    
    </div> <!-- /container -->
        
    <?php 
	if(!$this->zfcuserIdentity()){
			echo $this->modalWindow("loginwindow", "<h3>Connexion</h3>", "", $this->zfcUserLoginWidget(array('redirect'=>$this->serverUrl(true))));
	} ?>
        
    <?php echo $this->inlineScript() ?>
    </body>
</html>
